### ISSUE TITLE
Middleware issue uncovered in 0.31.0 signer/v4, not seen in 0.30

### ISSUE THREAD

**Issue by stevefchambers** [aws/aws-sdk-go-v2#1011]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution

Upgraded to 0.31.0 from 0.30.0, ran into the following issue, not seen in 0.30.0. Created by change on 12/24/20

go version go1.14.5 darwin/amd64

Can't run linter goanalysis_metalinter: bodyclose:
failed prerequisites:
analysis skipped:

could not import github.com/aws/aws-sdk-go-v2/config (/Users/user/go/pkg/mod/github.com/aws/aws-sdk-go-v2/config@v0.3.0/provider.go:9:2: could not import github.com/aws/aws-sdk-go-v2/credentials/ec2rolecreds (/Users/user/go/pkg/mod/github.com/aws/aws-sdk-go-v2/credentials@v0.1.5/ec2rolecreds/provider.go:13:2:
could not import github.com/aws/aws-sdk-go-v2/ec2imds (/Users/user/go/pkg/mod/github.com/aws/aws-sdk-go-v2/ec2imds@v0.1.5/api_client.go:57:3: cannot use awsmiddleware.AddUserAgentKey("ec2imds") (value of type func("github.com/aws/smithy-go/middleware".Stack) error) as func("github.com/awslabs/smithy-go/middleware".Stack) error value in argument to append)))]]"

failed to load package ec2imds: could not load export data: no export data for "github.com/aws/aws-sdk-go-v2/ec2imds""
failed to load package ec2imds: could not load export data: no export data for "github.com/aws/aws-sdk-go-v2/ec2imds""

**Comment by skotambkar** [comment]
Thanks for reaching out. The issue is due to incorrect dependencies version usage. 

Please update your go mod file to use the latest versions of package config to v0.4.0 and package credentials to v0.2.0.

Additionally with  SDK version v0.31.0 , we have moved the `ec2imds` package under `feature/ec2imds` path. 

Please review the [change-log](https://github.com/aws/aws-sdk-go-v2/blob/main/CHANGELOG.md) in order to correctly assert all the changes required with the new update.  Would also like to point out that the v2 SDK requires a minimum version of Go 1.15.

**Comment by stevefchambers** [comment]
Thanks for the comment. That fixed it

Also noted go version
