### ISSUE TITLE
How to Verify the peering is established ?

### ISSUE THREAD

**Issue by gowrisankar22** [aws/aws-sdk-go-v2#1058]
Hello,

I have a below scenario,

1. I have a first vpc called **VPC-A**
2. I have a second vpc called **VPC-B** where my Kubernetes operator is running.
3. Using golang SDK v2 from my VPC-B I want to check peering with VPC-A is established, so that I can implement the same in my k8s operator.

Can help me with how easily we can do it?

BRs, Gowrisankar

**Comment by gowrisankar22** [comment]
any update on this?

**Comment by KaibaLopez** [comment]
Sorry @gowrisankar22 , this kind of flew under my radar.
I think the best way for us to help you with this would be if you can show us code you've tried and the problems you've faced. 
Otherwise, if you're asking for complete stand alone samples the best place to put a request at would be the [aws-docs-sdk-examples](https://github.com/awsdocs/aws-doc-sdk-examples) repository.
