### ISSUE TITLE
Body in PutObjectInput

### ISSUE THREAD

**Issue by wunderbarb** [aws/aws-sdk-go-v2#1108]
**Describe the issue with documentation**
in service/s3, `PutObjectInput.Body` is declared as `io.Reader` although it seems to request an `io.ReadSeeker`

**To Reproduce (observed behavior)**
Use a pure `io.Reader` without Seeker when calling `PutObject` generates **operation error S3: PutObject, failed to compute payload hash: failed to seek body to start, request stream is not seekable**
When using a type that supports Reader, Closer and Seeker, no more error.   In V1, it was declared as an io.ReadCloseSeeker.
S3
**Expected behavior**
As declared, I would have expected that `Body` only requires `io.Reader` interface support.

**Screenshots**

**Additional context**

**Comment by billyzaelani** [comment]
I've also tried it. Confirmed that the `PutObjectInput.Body` is `io.ReadSeeker`.

If they want to continue with their current major version, fix the documentation in `PutObjectInput.Body`. But still unpleasant because we miss the compile-time checking.

If they change `PutObjectInput.Body` to `io.ReadSeeker`, they need to increment the major version. I don't know about this solution. Maybe fix the documentation is the way to go.

**Comment by jasdel** [comment]
Thanks for reporting this issue @billyzaelani . A workaround for this is to specify the `UNSIGNED-PAYLOAD` for the object to be upload. This will prevent the SDK from attempting to compute the SHA256 hash of the body. Using the [v4.AddUnsignedPayloadMiddleware](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws/signer/v4#AddUnsignedPayloadMiddleware) and [v4.RemoveComputePayloadSHA256Middleware](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws/signer/v4#RemoveComputePayloadSHA256Middleware) middleware helpers.

```go
resp, err := client.PutObject(context.TODO(), &s3.PutObjectInput{
    // Params
}, s3.WithAPIOptions(
    v4.AddUnsignedPayloadMiddleware,
    v4.RemoveComputePayloadSHA256Middleware,
))
```

This will instruct the SDK to not compute the SHA256 hash of the body, and instead use the `UNSIGNED-PAYLOAD` value instead. Note PutObject operation call still will require the `ContentLenth` parameter to be set, because The S3 API requires that parameter for all object PUTs.

**Comment by dectl** [comment]
This issue still persists, cannot pass bytes.Buffer to Body.

**Comment by jasdel** [comment]
While working on documentation to address this I released my above example was wrong. Doing those instructions will still fail, but with an error due to the SDK not populating the request correctly.

PR #1176 includes both documentation, and helper utility to allow you to swap out the SDK's compute payload hash for unsigned payload behavior.

**Comment by Thomasdezeeuw** [comment]
It seems the documentation change to fix this in https://github.com/aws/aws-sdk-go-v2/pull/1176 was undone by https://github.com/aws/aws-sdk-go-v2/pull/787.

/cc @jasdel

**Comment by didil** [comment]
In case anyone else runs into this issue, this is now documented here https://docs.aws.amazon.com/sdk-for-go/v2/developer-guide/sdk-utilities-s3.html#unseekable-streaming-input
You need to use:
```
s3.WithAPIOptions(
    v4.SwapComputePayloadSHA256ForUnsignedPayloadMiddleware,
)
```

**Comment by vivere-dally** [comment]
I encountered this issue with `UploadPart` as well

**Comment by MarkusFreitag** [comment]
As @Thomasdezeeuw already mentioned [3 years ago](https://github.com/aws/aws-sdk-go-v2/pull/1176#issuecomment-1438299254), the added documentation hint has unfortunately been overwritten by a [codegen commit](https://github.com/aws/aws-sdk-go-v2/pull/787).
Is it possible to add it back, in a way it will stay there even in case of future codegen tasks?
