### ISSUE TITLE
middleware `retry` breaks passing metadata up

### ISSUE THREAD

**Issue by wangzlei** [aws/aws-sdk-go-v2#1154]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
https://github.com/aws/aws-sdk-go-v2/blob/main/aws/retry/middleware.go#L86-L105
Middleware `retry` changes the structure of metadata, breaks the Metadata Get/Has functionality.
Please see more details in https://aws.github.io/aws-sdk-go-v2/docs/middleware/#passing-metadata-up-the-stack

**Version of AWS SDK for Go?**
The latest version

**Version of Go (`go version`)?**
any

**To Reproduce (observed behavior)**
following https://aws.github.io/aws-sdk-go-v2/docs/middleware/#passing-metadata-up-the-stack

**Expected behavior**
https://aws.github.io/aws-sdk-go-v2/docs/middleware/#passing-metadata-up-the-stack

**Additional context**

**Comment by jasdel** [comment]
Thanks for reporting this issue @wangzlei. The last retry attempt's metadata should be added to the returned `metadata` value, in addition to the individual attempts. This change will allow the metadata get/has functionality to work as expected without reaching into the set of retry attempts.

A workaround to this issue, until fixed in SDK, is to use the [GetAttemptResults](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws/retry#GetAttemptResults) helper and read the last attempt from the list.
