### ISSUE TITLE
Query Parameters At End of S3 API Call

### ISSUE THREAD

**Issue by thatMacAdmin** [aws/aws-sdk-go-v2#1158]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

When using the S3 client to connect to a custom S3 endpoint it seems to append query parameters which are causing the request to fail.

When I use a putObject request using the Golang V2 SDK it sends a request structured in this way
PUT https://s3.mycustomendpoint.com/bucket-name/pkgs/myfile.extension?x-id=PutObject HTTP/1.1"

However if I make the same request with Boto3 SDK it does this:
PUT https://s3.mycustomendpoint.com/bucket-name/pkgs/myfile.extension HTTP/1.1"

The Boto3 code succeeded without issues. How can I structure my golang S3 client to not append those x-id query parameters. I have looked through all references, code and StackOverflow items I can find but have come up blank. The same happens if I use Postman to test the API call. If the parameter is added as a header entry it is fine, the issue only seems to crop up when it is appended as a query parameter.

**Comment by skmcgrail** [comment]
This is not a Go SDK specific behavior, but is modeled as part of the S3 Smithy model for every operation. For example [PutObject](https://github.com/aws/aws-sdk-go-v2/blob/main/codegen/sdk-codegen/aws-models/s3.2006-03-01.json#L10053) definitions includes the required path parameters and query that should be used when constructing the operation. This is not present in the boto3/botocore models you mentioned due to that SDK using the previous modeling service modeling language description.

Since this is a valid parameter we are passing to S3, I would suggest that you create an issue and work with the upstream custom endpoint provider that you are using to address the correcting this behavior to prevent requests failing with this query string parameter.
