### ISSUE TITLE
rdsutils.BuildAuthToken missing in SDK v2

### ISSUE THREAD

**Issue by szymon3** [aws/aws-sdk-go-v2#1169]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
func BuildAuthToken for RDS Proxy (from rdsutils module), known from SDK v1, is missing in SDK v2.
Is there any alternative way to retrieve token using SDK v2?

**Version of AWS SDK for Go?**
1.2.0

**Version of Go (`go version`)?**
go version go1.16 darwin/amd64

**To Reproduce (observed behavior)**
-

**Expected behavior**
I expect to have a function which will return me a token for RDS Proxy.

**Additional context**
I saw that functionality was copied from SDK v1, but later was removed in one of commits (https://github.com/aws/aws-sdk-go-v2/commit/eecb706f5d1e3ca44aafca5c042ea275f4050764#diff-457ec6738454cb66ee5a04f7b14c84ecf31f37cb2f42f428cc28dc099970f8cd).

**Comment by skmcgrail** [comment]
Thank you for bringing this to our attention @szymon3 it looks like we missed pulling this feature back over after we performed the client refresh last year.

**Comment by haochunchang** [comment]
For those who got here before reading v2 developer guide,
When I want to use `rdsutils.BuildAuthToken` for IAM database authentication, I got the import error when using:
```go
import "github.com/aws/aws-sdk-go-v2/service/rds/rdsutils"
```
Since the [documentation](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/rds/rdsutils?utm_source=gopls#pkg-overview) path is: [service](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service) > [rds](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/rds) > [rdsutils](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2@v0.24.0/service/rds/rdsutils)

However, the import statement in v2 should be:
```go
import "github.com/aws/aws-sdk-go-v2/feature/rds/auth"
```
as specified in the v2 developer guide: https://aws.github.io/aws-sdk-go-v2/docs/sdk-utilities/rds/

Hopefully this saves some time for you.
