### ISSUE TITLE
service/docdb/types: DBCluster is missing support for TagList 

### ISSUE THREAD

**Issue by xinau** [aws/aws-sdk-go-v2#1262]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
The [DocumentDB cluster type](https://github.com/aws/aws-sdk-go-v2/blob/0ec7bfef61501ead2a7c42e208b3452ff36e318a/service/docdb/types/types.go#L56) doesn't include support tags on the resource even though they can be seen and specified in AWS. The `types` module includes a type [`Tag`](https://github.com/aws/aws-sdk-go-v2/blob/0ec7bfef61501ead2a7c42e208b3452ff36e318a/service/docdb/types/types.go#L795) but this isn't used anywhere inside the types module.

**Version of AWS SDK for Go?**
`v1.5.0`

**To Reproduce (observed behavior)**
The DocumentDB cluster struct doesn't include a list of tags.
https://github.com/aws/aws-sdk-go-v2/blob/4a50e355e38285ae39efeb73fd5ef517c4f45cae/service/docdb/types/types.go#L56-L170

**Expected behavior**
A list of tags should be available on the resource similar to other RDS and other resources.

**Comment by RanVaknin** [comment]
Hi @xinau ,

Sorry for the very late response. For some reason our automation didn't run and this issue was not marked for review.

You don't see the `Tag` type on this `DBCluster` struct because the Service team that defined the API didn't define it as such.
The SDKs are auto-generated from the API models of each service team so we can't really add / remove members from structs. Those decision are happening upstream with the service team.

If you want to get the list of tags for a DB cluster you can just call [`ListTagsForResource`](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/docdb#Client.ListTagsForResource) and supply the ARN of the cluster.

Since this issue is old and I'm not sure is still relevant, I feel confident we can close this thread. If you are still running into issues, please open a new one.

All the best 😄 
Ran
