### ISSUE TITLE
Is AWS Go SDK v2 SQS Client concurrent safe?

### ISSUE THREAD

**Issue by dc0d** [aws/aws-sdk-go-v2#1287]
For example, is it safe to call `DeleteMessage` from multiple goroutines?

I had this question and could not find an answer in the documentation on `pkg.go.dev` - to be specific the [sqs](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sqs#Client) package.

But from the documentation on [`aws.github.io`](https://aws.github.io/aws-sdk-go-v2/docs/making-requests/#concurrently-using-service-clients) it seems that the service clients are safe to be called concurrently from different goroutines.

If that's the case, maybe describing it inside the `pkg.go.dev` documentation would be prudent.

**Comment by KaibaLopez** [comment]
Hi @dc0d ,
So first,  let me clarify something just so we are on the same page here.
The service clients are concurrent safe, in the sense that you can use the same client to do multiple service api calls without any problem as long as those calls are not _conflicting_. To elaborate a bit on that:

In [the sample](https://aws.github.io/aws-sdk-go-v2/docs/making-requests/#concurrently-using-service-clients) it shows how one client can do 2 `PutObject` with 2 different keys with no problem. But, if you were to have them both use the same key, then it would have unexpected behavior, same with `DeleteMessage`.
You can safely call `DeleteMessage` on 2 different messages concurrently, but it's up to you to make sure they don't try to delete the same message.

Now, because this is not really _"service specific"_ behavior it is described in the more generic [`developer guide`](https://aws.github.io/aws-sdk-go-v2/docs/making-requests/#concurrently-using-service-clients) rather than the [sqs](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sqs#Client) package docs.

Anyways, does that make sense? Did I misunderstand anything or do you disagree and still think this should be included in each service documentation (can't promise it will, just want to know precisely what you're proposing)? Let me know.

**Comment by dc0d** [comment]
You are right. This is simply about the documentation in `pkg.go.dev`. That's the default place for packages/modules documentation.

There are many examples of indicating if a struct/method/function is safe to be called concurrently, in the documentation of the standard library, like the [`sync.Pool`](https://golang.org/pkg/sync/#Pool) package: `A Pool is safe for use by multiple goroutines simultaneously.`.

So, the properties/behaviors of the constructs in a package/module should be described clearly in the documentation (`pkg.go.dev`).

Developer's guide should be about overall descriptions, examples and walkthroughs.

**Comment by dc0d** [comment]
When a Retryer factory is passed to the config, If a method of the client is called from different goroutines, concurrently, is it using the same instance of the Retryer? Or the Retryer is being instantiated for each method call on that client separately?

**Comment by jasdel** [comment]
@dc0d The retry factor [aws.Config.Retryer](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws#Config.Retryer) will be called each time a API client that is initialized, hen an `aws.Config` is provided where `Retryer` member is not-nil.

The implementation detail of the retry factory function will determine if the same instance of the retryer is used by all API clients or not. With that said though, the factor should be returning either a concurrency safe Retryer. Mainly because the API client that uses the retryer are commonly used concurrently.

The retryer implementation provided by the SDK (Standard and Adaptive)  are all concurrency safe.
