### ISSUE TITLE
Is there a waiter available for V2 RDS DeleteDBInstance ?

### ISSUE THREAD

**Issue by peitili** [aws/aws-sdk-go-v2#1344]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

**Describe the question**

For the RDS V2 API, there is a waiter for DB creation NewDBInstanceAvailableWaiter, however if I want to delete DB instances, is there a waiter for that?

**Comment by KaibaLopez** [comment]
Hi @peitili ,
It is not currently in our models, so it's not something we can implement. So, short answer is no.

**Comment by peitili** [comment]
> Hi @peitili ,
> It is not currently in our models, so it's not something we can implement. So, short answer is no.


@KaibaLopez 
Thanks. If we want to wait for DeleteDBInstance result, what options do we have?

**Comment by haines** [comment]
@peitili because the waiters receive the client as a parameter, and all their dependencies are public, it's possible to define your own waiters when they're not included out of the box - I resorted to copy-pasting and modifying an existing one to work around the [lack of an EC2 instance running waiter](https://github.com/aws/aws-sdk-go-v2/issues/1159#issuecomment-851892819) previously. I suspect that's your best option for now.

**Comment by KaibaLopez** [comment]
Yea, I'm afraid that's the best sort of workaround at the moment.

**Comment by quinyx-tjeerd** [comment]
This has been released yesterday, which seems to be what you were looking for:
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/rds@v1.7.0#DBInstanceDeletedWaiter
