### ISSUE TITLE
Unable to cache pre-signed url as X-AMZ-DATE changes on every request

### ISSUE THREAD

**Issue by emilhakobian** [aws/aws-sdk-go-v2#1353]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
aws-sdk-go-v2

### Version of Go (`go version`)?
go version go1.15.5 darwin/amd64

### What issue did you see?
Unable to set X-AMZ-Date
I want to cache a pre-signed URL for a certain amount of time (let's say 1 hour). Because signing date always changing it is not possible. 
1. The browser sends a request to the server for a pre-sign url
2. Server returns URL 
3. Next time when a browser sends a request to the server I want to return the same url
### Steps to reproduce

If you have have an runnable example, please include it.
`
psClient := s3.NewPresignClient(s3Client)
	input := &s3.GetObjectInput{
		Bucket: aws.String(bucketName),
		Key:    aws.String(objectKey),
	}
res, err := psClient.PresignGetObject(context.TODO(), input,
		func(options *s3.PresignOptions) {
			options.Expires = time.Second * 300
		}) 
if err != nil {
		log.Println(err)
		fmt.Println()
	}
`

**Comment by KaibaLopez** [comment]
Hi @emilhakobian ,
I think there's something I am missing here... I don't quite follow what you are trying to do or why you can't do it with the current sdk.

Like is your expectation that for the time the url is valid, this call will keep returning the same url?
```golang
res, err := psClient.PresignGetObject(context.TODO(), input, func(options *s3.PresignOptions) { options.Expires = time.Second * 300 })
```
Because if so, then this is not something we'd implement.
Also, you say :
> I want to cache a pre-signed URL for a certain amount of time (let's say 1 hour).

But I don't think there is anything stopping you from doing that, you can generate a presigned url , cache it and keep using it while it is active, you don't need to make a PresignGetObject call every time. Sure, it will have an expiration date for which the maximum will depend on the type of credentials you are using ([see here for more info ](https://aws.amazon.com/premiumsupport/knowledge-center/presigned-url-s3-bucket-expiration/)) but while it is valid, it should work, you would just have to check that it isn't expired.

**Comment by pnegahdar** [comment]
I think what the prior commenter meant is if you set a consistent `X-Amz-Date` (e.g. by flooring the current time to the last midnight) you get consistent URLs so you no longer need to cache them yourself. Currently there seems to be no way to access this parameter.
