### ISSUE TITLE
Search results popup clip at the top of the window

### ISSUE THREAD

**Issue by RickStanley** [aws/aws-sdk-go-v2#1366]
**Describe the issue with documentation**
When search in the search input and hitting enter, the popup (of suggestions) shows up, but clipped.

**To Reproduce (observed behavior)**
1. Focus input search box;
2. Type a keyword, for example: "upload" and hit enter;
3. See clipped popup.

**Expected behavior**
See entire popup results on screen.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/23178554/128096604-495b11ec-d61c-46e4-a109-7548c597700f.png)

**Additional context**
- Using Firefox v90.0.2 (64-Bit), with only uBlock Origin extension (disabled for what it's worth);
- Window size (viewport): 1536 x 739
- OS: Windows 10

**Comment by RickStanley** [comment]
I have to scroll to the top to be able to see the results. I think it would be better, at least for laptop and desktop, if the popup showed on the right side and expanded from top to bottom.

**Comment by RickStanley** [comment]
On second thought, I'm not sure I'm supposed to report this kind of issue here. Please, let me know! 😅

**Comment by skmcgrail** [comment]
This is the correct repository for this issue since we host our developer documentation in a separate branch here. I am having a difficult time reproducing this issue on Firefox v90.0.2 on macOS. Will continue to research and investigate if any similar issues have been reported to the upstream Hugo project.
