### ISSUE TITLE
Asynchronous SDK calls

### ISSUE THREAD

**Issue by jonsmirl** [aws/aws-sdk-go-v2#139]
Is there any way to make an SDK call and not wait for it to finish? For example I am making an iotdataplane call that randomly takes between 100ms and 3 seconds to complete. Don't know why so long to complete, the delay is something inside of AWS since my parameters to call are always the same.

This is the last call my lambda makes.  The error return from this call is meaningless. I'd like to make this iotdataplane call and then exit my lambda instead of waiting around 3 seconds for an error message, if any, that I will just toss. If the call fails the device will detect the failure and retry.

**Comment by jasdel** [comment]
Hi @jonsmirl thanks for reaching out to us. The SDK does not have a built in mechanism to perform async calls. The SDK's API calls are blocking. With that said you could wrap the api call in a goroutine making its execution nonblocking to the initial context. Though, from your description of your usecase I think that would actually case a hidden bug in your lambda application. 

In general with Go, if the main function returns all outstanding goroutines will be terminated, with little reguard for their state. I think your usecase requires that the application wait for the API call to return in order to ensure that it was made at all. Without waiting it is possible for the scheduler to of never scheduled the goroutine for your API call by the time the main function returns.

**Comment by jasdel** [comment]
Though I think with some modifications to the SDK's request handlers you could instruct the SDK to ignore the response, and add a very short time to if it is not critical for the API call to be successfully made.  I'll see if I can put together a simple sample of how the sdks request can be modified to ignore the http response.
