### ISSUE TITLE
s3/Client.GetObject:  potential goroutine leak

### ISSUE THREAD

**Issue by wunderbarb** [aws/aws-sdk-go-v2#1434]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ X] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [X ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [X ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
When `Client.GetObject` has an error, it seems that there leaking goroutines.  There are no documented means to close them. 

**Version of AWS SDK for Go?**
github.com/aws/aws-sdk-go-v2/service/s3 v1.16.0

**Version of Go (`go version`)?**
1.16.4

**To Reproduce (observed behavior)**
See attached test file (renamed as go.txt).

**Expected behavior**
Test_exp1:  `GoObject` is successful.  After `goo.Body.Close()`, no remaining goroutines as expected.
Test_exp2:  `GetObject` fails.  Remaining goroutines.   
Test_exp3:  `GetObject` fails.  Even cancel function does not remove remaining goroutines.

I would expect that the failure would also close the remaining goroutines.
**Additional context**
Add any other context about the problem here
[main_test.go.txt](https://github.com/aws/aws-sdk-go-v2/files/7227168/main_test.go.txt)
.

**Comment by skmcgrail** [comment]
There are multiple moving parts here that need to be broken down:

* The default HTTP client used by the SDK has HTTP Keep-Alive enabled, meaning connections remain open for reuse by the clients. Thus you see the Go routines spawned by the `net/http` library remain executing and block on I/O on the socket file descriptor.
* `Test_exp1` has no Go routines remaining since you are not completely consuming the entire body. By not consuming the body the connection is being thrown away and can't be reused. Adding a `_, _ = io.Copy(io.Discard, goo.Body)` to your function before calling close confirms that connection remains open for reuse.
* `Test_exp2` and `Test_exp3` remain open due to connection HTTP Keep-Alive, which is expected. The SDK has a middlware that consumes and closes the body on error responses which prevents the connections from being abandoned and closed like in `Test_exp1` as explained.
* You can disable HTTP Keep-Alive to confirm this is the behavior you are seeing:
```
awsCfg, err := config.LoadDefaultConfig(context.Background(), config.WithHTTPClient(awshttp.NewBuildableClient().WithTransportOptions(func(transport *http.Transport) {
    transport.DisableKeepAlives = true
})))
```
