### ISSUE TITLE
Forcing infrastructure related design on modelling?

### ISSUE THREAD

**Issue by kenneth488** [aws/aws-sdk-go-v2#1457]
**Is your feature request related to a problem? Please describe.**
Migration from v1 of AWS go SDK to v2 gave me a few chills when looking through the implementation regarding some decisions made around how data is marshalled/un-marshalled. I strongly believe that the decision forcing developers to use a tag such as 'dynamodbav:' in their data modelling is very bad practise, since the data modelling, in most cases, should be decoupled from the behavior of the infrastructure. The service should utilise the possibilities within the languages already provided, such as the tags predefined in go, to support a more agile approach to development. 

**Describe the solution you'd like**
As in v1 of the SDK, the 'json:' tag gives precise indication of the wanted name conversion for the field, or make it possible for us to provide a custom encoder when calling the marshaller. 

**Describe alternatives you've considered**
Implementing a custom encoder and methods for marshalling. 

**Additional context**
I might be missing something important here on why this decision was made. If so, I would very much love to hear all about it :-)

Have an awesome day!

Thanks!

**Comment by kenneth488** [comment]
Related: https://github.com/aws/aws-sdk-go-v2/pull/1453

**Comment by jasdel** [comment]
Thanks for creating this issue @kenneth488. The best way to configure the AttributeValue marshaler in your application for `json` sourced key names, is to create a custom encoder/decoder and specify the `Tagkey` option. The AttributeValue marshaler will use this `TagKey` option for the name of AttributeValueMap keys when serializing struct members.

```go
ddbAvDecoder := attributevalue.NewDecoder(func(o *attributevalue.DecoderOptions) {
    o.TagKey = "json"
})

ddbAvEncoder := attributevalue.NewEncoder(func(o *attributevalue.EncoderOptions) {
    o.TagKey = "json"
})
```

The SDK will still use `dynamodbav` for all non key options such as `omitempty` and `omitnull`.  The V2 SDK's AttributeValue marshaler intentionally does not read `json` struct tag keys by default. Instead it uses the unique `dynamodbav` key to drive struct tag based options. `dynamodbav` is used instead of `json` to create a consistent expectation of how the AttributeValue marshaler will behave. The v1 SDK had several edge cases with AttributeValue marshaler's usage of `json` tag that caused unexpected behavior, especially with regard to `omitempty`, and zero value marshaling.  In addition `json` tag has expected predefined behavior based on the behavior of the Go standard library's `json` package that conflict with the behavior of the AttributeValue marshaler.

The best way to use the AttributeValue marshaler with additional tags such as `json`, `yaml`, etc is to use the `TagKey` option.
