### ISSUE TITLE
Asynchronous SDK calls support

### ISSUE THREAD

**Issue by sedefsavas** [aws/aws-sdk-go-v2#1489]
### Describe the feature

Similar to SDK for Java and C++, SDK Go should support asynchronous (unblocking) calls.

If this is in the roadmap, when will this get implemented?

### Is your Feature Request related to a problem?

I am hitting API limits and to solve it using throttling.  Also, waiting on methods does not well align with Kubernetes reconciling design which is adopted by many Kubernetes products. In short, if an AWS resource has not created yet, instead of waiting, we want to return and retry until it gets created. 

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Go SDK version used

Release (2021-11-06)

### Go version used

1.16.2

**Comment by KaibaLopez** [comment]
Hi @sedefsavas ,
I need a bit more context for this, there are a lot of asyncronous calls that the SDK supports and some others that because of the nature of the services are not... But this issue is too generic for me to offer any help.
Can you provide a minimal code sample of what you are trying to do? And since you mentioned, maybe showing me how you'd do it on the C++ SDK would also help me figure this out.
