### ISSUE TITLE
Reduce Abstraction Noise

### ISSUE THREAD

**Issue by MarkMoretto** [aws/aws-sdk-go-v2#1586]
### Describe the feature

Hi,

When perusing through the [aws package](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws), I find it distracting and unnecessary for there to be to much emphasis on...type conversions?  The first section of the AWS Go package is titled: "Value and Pointer Conversion Utilities."

???

Converting from a string to a string pointer, or bool to bool, or whatever, shouldn't be the focus of the AWS library; adding useful features for helping Go devs leverage their prowess in the cloud via AWS should be the focus.

### Is your Feature Request related to a problem?

I guess.  See "describe the problem" for more info.

### Proposed Solution

Get rid of all the unnecessary "utilities" and just provide a comprehensive package that doesn't require something like this import confetti:

```go
import (
	"context"
	"log"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/credentials/stscreds"
	"github.com/aws/aws-sdk-go-v2/service/sts"
)
```

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Go SDK version used

2

### Go version used

1.18beta1

**Comment by jasdel** [comment]
Thanks for taking the time to create this issue @MarkMoretto. Could you provide more background of the issue that you're running into?

The `aws` package provides common utilities that commonly used along side the SDK's API client modules. Most of the type conversion utilities are due to in ability to take address of literal value in Go, (e.g. `&"abc123"`). Most API client parameters are pointers due to the zero value of a scalar type may be significant.

The other packages such as `config`, `service/...` and `credentials/...` are separate modules allowing independent versioning of unique behavior, along with preventing circular dependencies between packages. For example, the `aws` package  contains `Config` which is used by all API clients and populated by the `config` module. The `config` package depends on the `credentials` packages for built in credentials provider, and credentials provider can depend on other API clients such as `service/sts`. This means nothing in the SDK can depend on the contents of the `config` package. Only user applications can depend on `config` or there will be circular dependencies such as `service/sts` -> `config` -> `credentials/stscreds` -> `service/sts`. Similar issues with `aws` package. Other packages can depend on `aws`, but `aws` cannot depend on any `credentials`, `service/...` or `config` package

Any suggestions you have for adjustments to this layouts are welcome, but we won't be able to make breaking changes to the package layouts.

**Comment by MarkMoretto** [comment]
Thanks!
