### ISSUE TITLE
S3 GetBucketNotificationConfiguration returns filter rules in camel case

### ISSUE THREAD

**Issue by MisterMX** [aws/aws-sdk-go-v2#1595]
### Documentation

- [X] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution

### Describe the bug

When calling [`GetBucketNotificationConfiguration`](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3#Client.GetBucketNotificationConfiguration) all `prefix` filters have a camel case `Prefix` name although the SDK specifies only lower case `prefix` and `suffix` as allowed values.

```json
{
    "QueueConfigurations": [
        {
            "Id": "...",
            "QueueArn": "...",
            "Events": [
                "s3:ObjectCreated:*"
            ],
            "Filter": {
                "Key": {
                    "FilterRules": [
                        {
                            "Name": "Prefix",
                            "Value": "some-prefix"
                        }
                    ]
                }
            }
        }
    ]
}
```

For more details see https://github.com/crossplane/provider-aws/issues/1165

### Expected behavior

The SDK should return a `BucketNotificationConfiguration` with filter names only in lower case as specified.

### Current behavior

Filter names have camel case values `Prefix` and `Suffix`.

### Steps to Reproduce

1. Create a SQS queue
2. Create a bucket
3. Put a notification configuration with the created SQS queue and a `prefix` filter
4. Call `GetNotificationConfiguration`

### Possible Solution

Perform a `strings.ToLower` on every filter rule name before return the configuration.

### AWS Go SDK version used

github.com/aws/aws-sdk-go-v2/service/s3 `v1.18.0`

### Compiler and Version used

go version go1.17.6 linux/amd64

### Operating System and version

Lubuntu 20.04 LTS

**Comment by jasdel** [comment]
Thanks for reporting this issue @MisterMX. This looks like a bug, in how the Amazon S3 API model defines the [FilterRuleNames](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3@v1.25.0/types#FilterRuleName). This are defined as lower case like you pointed. I'll report this upstream to the S3 team to update their model. In addition, the S3 PI reference docs for [FilterRuleName document the lower cased names](https://docs.aws.amazon.com/AmazonS3/latest/API/API_FilterRule.html).  One of the best ways to let the S3 team know about this issue is to submit `Feedback` via the upper right hand corner link on the page.

In the mean time, the best workaround for this is to define your own set of constants for the `FilterRuleName` that match the expected casing of the values received.

```go
const (
	FilterRuleNamePrefix FilterRuleName = "Prefix"
	FilterRuleNameSuffix FilterRuleName = "Suffix"
)
```
