### ISSUE TITLE
[Question / Feature Request] File based Credential Cache using CredentialsCache?

### ISSUE THREAD

**Issue by Skarlso** [aws/aws-sdk-go-v2#1633]
### Describe the feature

Hello!

Do I understand correctly, that right now, the `CredentialsCache` is only in memory?

Or am I missing something or just can't find it in the documentation. If so, can the credential cache be used as a file based cache out of the box for MFA tokens not being asked over and over for various api calls? To understand as a reference, v1 needed the Expired interface and some extra work from client libraries to create a file based cache and use a provider which could expire.

For example: https://github.com/aws/aws-sdk-go/issues/1329 And as part of that an Expired interface was added: https://github.com/aws/aws-sdk-go/pull/2375/files

This is still the case concerning v2, right?

thanks

### Is your Feature Request related to a problem?

No

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Go SDK version used

Release (2022-03-18)

### Go version used

1.18

**Comment by jasdel** [comment]
Correct credential cache is only in memory. The SDK does not cache AWS credentials in a file. Only the AWS CLI will due this due to its nature of individual command invocation.

With regard to MFA, if an assume role requires MFA token, and the credentials need to be refreshed (or obtained for first time) that handling must be implemented via the a [token provider in code](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/credentials/stscreds#hdr-Assume_Role_with_MFA_Token_Provider). The SDK will throw an error at runtime if a token provider has not been configured, and one is needed.

**Comment by Skarlso** [comment]
Thank you for your answer @jasdel!
