### ISSUE TITLE
Why are S3 trailing checksums only supported over TLS?

### ISSUE THREAD

**Issue by stefansundin** [aws/aws-sdk-go-v2#1667]
### Describe the bug

I was first going to submit this bug report with a different title, namely that there is an error returned when attempting to use `ChecksumAlgorithm` together with an http endpoint, but then I saw these two comments in the code:

https://github.com/aws/aws-sdk-go-v2/blob/4dfb7e6d6686a15d47cfcec7d336334ed69b6ac6/service/internal/checksum/middleware_compute_input_checksum.go#L172-L196

Typo above btw, `ComputetPayloadHash` should be `ComputePayloadHash`.

https://github.com/aws/aws-sdk-go-v2/blob/4dfb7e6d6686a15d47cfcec7d336334ed69b6ac6/service/internal/checksum/middleware_compute_input_checksum.go#L275-L280

However, I manually edited these two checks and the upload was successful, which means it is an artificial limitation in the SDK. I'm curious why this is the case.

### Expected Behavior

I expect `ChecksumAlgorithm` to work regardless if an http or https endpoint is used.

### Current Behavior

If you attempt to use `ChecksumAlgorithm` with an http endpoint, this is the error you receive at the moment:

> operation error S3: PutObject, https response error StatusCode: 400, RequestID: XXX, HostID: XXX, api error InvalidArgument: x-amz-content-sha256 must be UNSIGNED-PAYLOAD, STREAMING-UNSIGNED-PAYLOAD-TRAILER, STREAMING-AWS4-HMAC-SHA256-PAYLOAD, STREAMING-AWS4-HMAC-SHA256-PAYLOAD-TRAILER, STREAMING-AWS4-ECDSA-P256-SHA256-PAYLOAD, STREAMING-AWS4-ECDSA-P256-SHA256-PAYLOAD-TRAILER or a valid sha256 value.

### Reproduction Steps

```go
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	s3Types "github.com/aws/aws-sdk-go-v2/service/s3/types"
)

func main() {
	cfg, err := config.LoadDefaultConfig(context.TODO(), func(o *config.LoadOptions) error {
		var lm aws.ClientLogMode = aws.LogRequestWithBody | aws.LogResponseWithBody
		o.ClientLogMode = &lm
		return nil
	})
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	client := s3.NewFromConfig(cfg, func(o *s3.Options) {
		o.Region = "us-west-2"
		// ChecksumAlgorithm can't be used together with an http endpoint:
		o.EndpointResolver = s3.EndpointResolverFromURL("http://s3.us-west-2.amazonaws.com/")
		// It works with the https endpoint:
		// o.EndpointResolver = s3.EndpointResolverFromURL("https://s3.us-west-2.amazonaws.com/")
	})

	putObjectOutput, err := client.PutObject(context.TODO(), &s3.PutObjectInput{
		Bucket: aws.String("bucketname"),
		Key:    aws.String("test"),
		Body:   bytes.NewReader([]byte("hello world")),
		// Uncomment this and the http endpoint will work:
		ChecksumAlgorithm: s3Types.ChecksumAlgorithmSha256,
	})
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	output, err := json.MarshalIndent(putObjectOutput, "", "  ")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	fmt.Println(string(output))
}
```

### Possible Solution

1. Explain why TLS is currently required.
2. Remove the requirement if it makes sense.
3. If the requirement can't be removed, then maybe throw an error instead of sending the request?

### Additional Information/Context

Editing the code makes the upload work and the checksum is successfully sent as a trailer over unencrypted HTTP.

I am not really going to upload files to S3 over unencrypted HTTP, but I am developing a program that interfaces with S3 and I need to know when the SDK reads the object body twice (once to calculate the checksum for a regular header, and then once again when sending it over the network). So I am trying to test all different combinations and this is just one esoteric combination that I thought of and figured I'd try to get some clarification on. Thanks!

### AWS Go SDK version used

v1.16.2

### Compiler and Version used

go version go1.18 darwin/arm64

### Operating System and version

macOS 12.3.1

**Comment by stefansundin** [comment]
I think I just thought of the "why". Compared to a regular unencrypted upload, an MITM attack in this case can actually change the contents of the payload since the checksum will not be included in the signature. So it makes sense to not support this case.

It might be a good idea to have the S3 service return an error. I was able to bypass the safeguard in the SDK out of ignorance.

And I think it would be good to have the SDK return an error with this combination, instead of attempting the upload and failing:

```go
	client := s3.NewFromConfig(cfg, func(o *s3.Options) {
		o.Region = "us-west-2"
		o.EndpointResolver = s3.EndpointResolverFromURL("http://s3.us-west-2.amazonaws.com/")
	})

	putObjectOutput, err := client.PutObject(context.TODO(), &s3.PutObjectInput{
		Bucket:            aws.String("bucketname"),
		Key:               aws.String("test"),
		Body:              bytes.NewReader([]byte("hello world")),
		ChecksumAlgorithm: s3Types.ChecksumAlgorithmSha256,
	})
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
```

```
operation error S3: PutObject, https response error StatusCode: 400, RequestID: , HostID: , api error InvalidArgument: x-amz-content-sha256 must be UNSIGNED-PAYLOAD, STREAMING-UNSIGNED-PAYLOAD-TRAILER, STREAMING-AWS4-HMAC-SHA256-PAYLOAD, STREAMING-AWS4-HMAC-SHA256-PAYLOAD-TRAILER, STREAMING-AWS4-ECDSA-P256-SHA256-PAYLOAD, STREAMING-AWS4-ECDSA-P256-SHA256-PAYLOAD-TRAILER or a valid sha256 value.
```

**Comment by skmcgrail** [comment]
Thanks for reaching out to us @stefansundin, there is actually a few moving pieces here and you have actually uncovered a very specific bug in how we handle switching back to sending the checksum as a standard HTTP header in cases where the body can be rewinded.

If the endpoint is not HTTPS we will actually check to see if the provided `io.Reader` is seekable or not. If it is seekable we will compute the requested checksum algorithm and will send the checksum value as a standard http header, and perform the standard sigv4 signing procedure on the body and send it to the endpoint (in this example you gave just the standard HTTP scheme endpoint). What is happening here though is that we attempt to optimize and share the computation of the sha256 checksum between sigv4 and the s3 checksum header. Unfortunately the expected encoding scheme used in both header locations are actually different between `X-Amz-Content-Sha256` and `X-Amz-Checksum-Sha256`. The former expects it to be hex encoded, and the later expects it to be base64 encoded. The error you are receiving is because we were incorrectly setting the `X-Amz-Content-Sha256` to a base64 encoded value in cases where the checksum requested was also sha256 AND the checksum couldn't be sent via a streaming trailer using aws-chunked with unsigned payload.

Headers from your example code with the incorrect encoding for the `X-Amz-Content-Sha256`:
```
X-Amz-Checksum-Sha256: uU0nuZNNPgilLlLX2n2r+sSE7+N6U4DukIj3rOLvzek=
X-Amz-Content-Sha256: uU0nuZNNPgilLlLX2n2r+sSE7+N6U4DukIj3rOLvzek=
```

What the headers should be:
```
X-Amz-Checksum-Sha256: uU0nuZNNPgilLlLX2n2r+sSE7+N6U4DukIj3rOLvzek=
X-Amz-Content-Sha256: b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9
```

With that set correctly you would be able to successfully send this request to the service.

Bug is here: https://github.com/aws/aws-sdk-go-v2/blob/main/service/internal/checksum/middleware_compute_input_checksum.go#L425

**Comment by skmcgrail** [comment]
@stefansundin Today's release contained a fix to address the issue of the `X-Amz-Content-Sha256` being incorrectly encoded which was causing the request sent to the service to result in a 400.

You can either `go get github.com/aws/aws-sdk-go-v2/service/internal/checksum@v1.1.5` to update the module in question to the patched version, or `go get github.com/aws/aws-sdk-go-v2/service/s3@v1.26.7` to update service client directly which will also pull in the updated checksum module dependency.

**Comment by stefansundin** [comment]
Okay, that's great. I just tested it and it appears to work!

So to summarize:
- `ChecksumAlgorithm` is supported over HTTP.
- Over HTTP it just won't use a HTTP trailer because that wouldn't be safe over an unencrypted connection. Since the checksum wouldn't be signed in an HTTP trailer, a MITM attack could modify the checksum and thus also the contents if this was allowed.
- HTTPS is a requirement to have the SDK calculate the checksum during the upload.

**Comment by skmcgrail** [comment]
A little bit more nuanced, but I think this highlights that it is worth creating a developer guide documentation page to help clarify the behaviors when using the S3 client and checksums.

* If a user specifies an explicit checksum value in either the `ChecksumCRC32`, `ChecksumCRC32C`, `ChecksumSHA1`, or `ChecksumSHA256` fields then the SDK will send that value specified using a standard HTTP request header using the appropriate `x-amz-checksum-*` header for each. This is not affected by whether the `HTTP` or `HTTPS` scheme is used. The request will be signed with SigV4 or SigV4a regardless of the scheme, the only distinction here is whether the payload body hash is computed or not for the `x-amz-content-sha256`. For HTTP schemes this will be the computed sha256 hash for the PutObject body, otherwise for HTTPS this will be `UNSIGNED-PAYLOAD`. If the payload body hash needs to be computed for sending it using HTTP scheme, then the body must be seekable so we can compute the hash and reseek the body.
* If `ChecksumAlgorithm` field is specified then the SDK will compute the corresponding checksum for the request and will send it in the appropriate `x-amz-checksum-*`. The only distinction is where this header will specifically be sent based on the endpoint scheme. 
  * If the scheme is HTTPS the computed checksum will be sent in a trailer header block using aws-chunked encoding. It will also do so use an unsigned payload variant called `STREAMING-UNSIGNED-PAYLOAD-TRAILER` which does not require signing each aws-chunked. The Go SDK only supports this variant of aws-chunked, which is why computed checksums sent via a aws-chunked trailer requires an HTTPS endpoint in this SDK. For trailer streaming the content-length of the PutObject body to be sent must still be known. So either the PutObject request specifies `ContentLength` field, the body implements  `interface{ Len() int }`, or the body is seekable so we can figure out the length to be sent. We may add support for the signed aws-chunked variants (e.g. `STREAMING-AWS4-HMAC-SHA256-PAYLOAD-TRAILER`) in the future so we can send a signed checksum trailer to an HTTP endpoint. That feature is supported in SDKs that had already supported signed aws-chunked payloads previously. 
  * If the scheme is HTTP then we fallback to to a behavior similar to the checksum provided case, but instead we compute the value (thus the body must be seekable), and we attach it as a header similar to the provided checksum case.

**Comment by stefansundin** [comment]
Thanks for the detailed explanation. 👍
