### ISSUE TITLE
GetRoleCredentialsOutput RoleCredentials.Expiration units not documented

### ISSUE THREAD

**Issue by SpencerBrown** [aws/aws-sdk-go-v2#1671]
### Describe the issue

Please update [this line of doc in the code](https://github.com/aws/aws-sdk-go-v2/blob/service/sso/v1.11.3/service/sso/types/types.go#L34)

to say:

```
// The date on which temporary security credentials expire, in milliseconds since the Unix epoch
```

This would save other people's time in figuring out what units this is in. 

### Links

(https://github.com/aws/aws-sdk-go-v2/blob/service/sso/v1.11.3/service/sso/types/types.go#L34

### AWS Go SDK version used

v1.16.2

**Comment by skmcgrail** [comment]
Hey @SpencerBrown since this documentation comes from the service's API model we can't directly modify that in our SDK. The best way to ensure this feedback gets the right place so that it can be corrected in both the service's API reference guide and all SDKs is via the `Provide Feedback` button on the [[Portal API Reference](https://docs.aws.amazon.com/singlesignon/latest/PortalAPIReference/Welcome.html)](https://docs.aws.amazon.com/singlesignon/latest/PortalAPIReference/API_RoleCredentials.html). This will ensure your feedback gets routed appropriately.
