### ISSUE TITLE
CreateBucket always returns 409 BucketAlreadyExists error

### ISSUE THREAD

**Issue by neakor** [aws/aws-sdk-go-v2#1740]
### Describe the bug

Using the following code to create a bucket always results in a 409 `BucketAlreadyExists` error even though the bucket most definitely does not exist.
```go
region := "us-west-2"
creds := credentials.NewStaticCredentialsProvider(
  "KEY_ID",
  "SECRET",
  "", // Token is empty since it is obtained after API calls.
)
cfg, err := config.LoadDefaultConfig(context.
  TODO(),
  config.WithCredentialsProvider(creds),
  config.WithRegion(region),
)
if err != nil {
  return err
}

service := s3.NewFromConfig(cfg)
_, err := a.service.CreateBucket(
  context.TODO(),
  &s3.CreateBucketInput{
    Bucket:  aws.String("my-bucket"),
    CreateBucketConfiguration: &types.CreateBucketConfiguration{
      LocationConstraint: types.BucketLocationConstraint(region),
    },
  }
)
if err != nil {
  return err
}
```

Actual error:
```console
operation error S3: CreateBucket, https response error StatusCode: 409, RequestID: REDACTED, HostID: REDACTED, BucketAlreadyExists:
```

### Expected Behavior

Create bucket should succeed and create the actual S3 bucket.

### Current Behavior

```console
operation error S3: CreateBucket, https response error StatusCode: 409, RequestID: REDACTED, HostID: REDACTED, BucketAlreadyExists:
```

### Reproduction Steps

Please see description.

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2 v1.16.5
github.com/aws/aws-sdk-go-v2/config v1.15.11
github.com/aws/aws-sdk-go-v2/credentials v1.12.6
github.com/aws/aws-sdk-go-v2/service/codebuild v1.19.6
github.com/aws/aws-sdk-go-v2/service/codepipeline v1.13.6
github.com/aws/aws-sdk-go-v2/service/codestarconnections v1.13.6
github.com/aws/aws-sdk-go-v2/service/iam v1.18.7
github.com/aws/aws-sdk-go-v2/service/s3 v1.26.11
github.com/aws/aws-sdk-go-v2/service/ssm v1.27.2

### Compiler and Version used

go version go1.18.2 darwin/arm64

### Operating System and version

MacOS 12.4

**Comment by neakor** [comment]
Found this reply https://github.com/cloudposse/terraform-aws-tfstate-backend/issues/54#issuecomment-788802919 indicating that the issue is because the bucket name already exists in some other customer's account. I think we can improve the error message here. This has been very confusing.

**Comment by RanVaknin** [comment]
Hi @neakor ,

The error messages provided by the SDK are auto generated from the S3 service model. This means that the SDK team has no control over how verbose an error message might be. 
I personally think that `BucketAlreadyExists` is a pretty self explanatory error message as a google search of that error will lead you to the S3 docs that would specify the following:


> BucketAlreadyExists | The requested bucket name is not available. The bucket namespace is shared by all users of the system. Specify a different name and try again. | 409 Conflict
> -- | -- | --
> 
> 
>   


With that being said, AWS is always looking for contributions and feedback from users, so I encourage you to submit a revision through the [documentation portal](https://docs-feedback.aws.amazon.com/feedback.jsp?hidden_service_name=S3&topic_url=https://docs.aws.amazon.com/AmazonS3/latest/API/API_CreateBucket.html#API_CreateBucket_SeeAlso) and mention that a more verbose error message is needed.

Since it seems like you have figured out the error I'll go ahead and close this issue. If something else arises feel free to re-open or cut another issue. 

Thanks!
