### ISSUE TITLE
Migrate to ses v2 to fix: Message length is more than 10485760 bytes long: '12078147'

### ISSUE THREAD

**Issue by RichardLindhout** [aws/aws-sdk-go-v2#1774]
### Describe the feature

I want to send email via the ses v2 api which has greater limits.

### Use Case

I want to send big files without getting errors (in the current version)
```
ERR could not send email: Message length is more than 10485760 bytes long: '12078147'. error="operation error SES: SendRawEmail, https response error StatusCode: 400, RequestID: 6449f1fe-aa0f-4c7a-a47e-95b383270cd3, api error InvalidParameterValue: Message length is more than 10485760 bytes long: '12078147'." aws_error_code=InvalidParameterValue
```

### Proposed Solution

Make SES support the v2 api so we can bigger files

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

	github.com/aws/aws-sdk-go-v2 v1.16.7
	github.com/aws/aws-sdk-go-v2/config v1.15.14
	github.com/aws/aws-sdk-go-v2/feature/s3/manager v1.11.20
	github.com/aws/aws-sdk-go-v2/service/s3 v1.27.1
	github.com/aws/aws-sdk-go-v2/service/ses v1.14.9

### Go version used

1.18

**Comment by RanVaknin** [comment]
Hi @RichardLindhout ,

We already have [SES v2](https://github.com/aws/aws-sdk-go-v2/tree/main/service/sesv2) in the GO SDK. You only need to specify the correct module as an import:

![image](https://user-images.githubusercontent.com/50976344/184937883-ab9839aa-c31e-4a1f-a833-078862e8a9ce.png)



Also, I believe v2 has the same 10mb restriction with an option to ask for an increase to 40mb.
Not sure if the 40mb comes baked into the api by default. **[Source](https://aws.amazon.com/about-aws/whats-new/2021/09/amazon-ses-emails-message-40mb/)**

I'm going to go ahead and close this issue since the feature you have requested already exists.
Let me know if you have any other questions.

Thanks!
~Ran
