### ISSUE TITLE
s3上传zip.File失败

### ISSUE THREAD

**Issue by bzdanny** [aws/aws-sdk-go-v2#1804]
### Describe the bug

github.com/aws/aws-sdk-go-v2/service/s3中
使用s3.PutObject上传文件
如果在PutObjectInput的Body赋值zip.File.Open
这S3抛出error

### Expected Behavior

err=nil

### Current Behavior

Failed to compute node presentation

### Reproduction Steps
```go
func xxx(file *zip.File){
open,err:=file.Open()
params := &s3.PutObjectInput{
		Bucket:      buketName,
		Key:           aws.String(file.Name),
		Body:        open,
		ContentType: contentType,
		ACL:         types.ObjectCannedACLPublicRead,
	}
}
```
### Possible Solution
```go
func xxx(file *zip.File){
open,err:=file.Open()
buf := &bytes.Buffer{}
_, _ = buf.ReadFrom(open)
b := buf.Bytes()
params := &s3.PutObjectInput{
		Bucket:      buketName,
		Key:           aws.String(file.Name),
		Body:        bytes.NewReader(b),
		ContentType: contentType,
		ACL:         types.ObjectCannedACLPublicRead,
	}
}

```
这样上传是正常的

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/service/s3 v1.27.3
github.com/aws/aws-sdk-go-v2/service/s3 v1.27.0
github.com/aws/aws-sdk-go-v2/service/s3 v1.26.8

### Compiler and Version used

1.18,1.19

### Operating System and version

mac

**Comment by RanVaknin** [comment]
Hi @bzdanny ,

I'm having to use a translation service to answer your question so I'm not 100% sure I understand the issue at hand.
What I **think** you are saying is that when `Body:        open` it is throwing an error.

The reason is that the S3 service requires a `contentLength` to be set.  Since `open` in this case is of type `io.ReadCloser` this interface does not implement the `len()` function that is required to calculate the `contentLength`.

In order for ContentLength to be calculated you need one of the following
- Calculate and set the content length manually:
```go
func xxx(file *zip.File){
open,err:=file.Open()
params := &s3.PutObjectInput{
		Bucket:      buketName,
		Key:           aws.String(file.Name),
		Body:        open,
                ContentLength: file.FileInfo().Size(),
		ContentType: contentType,
		ACL:         types.ObjectCannedACLPublicRead,
	}
}
```
**- OR -** 
- The Provided body will need to implement the `len()` method
This is what you did, since your reader has a `len()` method on it.

**- OR -** 
- The Provided body will need to implement the `Seeker` interface


Let me know if this answers your question.
Thanks,
~Ran

===============================

**这是翻译后的答案，可能不准确**

我不得不使用翻译服务来回答你的问题，所以我不是 100% 确定我是否理解眼前的问题。
我**想**你的意思是，当 `Body: open` 它会抛出一个错误。

原因是 S3 服务需要设置 “内容长度”。由于本例中的 `open` 类型为 `io.readCloser`，因此此接口不实现计算 `contentLength` 所需的 `len () `函数。

为了计算 `contentLength`，你需要以下其中一项
-手动计算和设置内容长度：
```go
func xxx(file *zip.File){
open,err:=file.Open()
params := &s3.PutObjectInput{
		Bucket:      buketName,
		Key:           aws.String(file.Name),
		Body:        open,
                ContentLength: file.FileInfo().Size(),
		ContentType: contentType,
		ACL:         types.ObjectCannedACLPublicRead,
	}
}
```
**-或-** 
-提供的主体需要实现 `len () `方法
这就是你所做的，因为你的读者有一个 `len () `方法。

**-或-** 
-提供的主体需要实现 `Seeker` 接口

如果这是否回答了你的问题，请告诉我。
谢谢，
~Ran

**Comment by bzdanny** [comment]
The problem has been solved   Thinks
