### ISSUE TITLE
CloudWatch GetMetricDataOutput:MetricDataResult missing metric dimensions and namespace

### ISSUE THREAD

**Issue by autopticio** [aws/aws-sdk-go-v2#1812]
### Describe the bug

GetMetricDataOutput comments specify that the metric name, dimensions and namespace will be returned with MetricDataResult but the MetricDataResult type does not include dimensions and namespace.

https://github.com/aws/aws-sdk-go-v2/blob/main/service/cloudwatch/api_op_GetMetricData.go
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/cloudwatch@v1.21.0/types#MetricDataResult

### Expected Behavior

MetricDataResult should contain dimensions and namespace as noted. It is acceptable if we need to pass extra flags to request this additional detail.

Without the dimensions and namespace we can't separate the metrics and datapoints in the results.

### Current Behavior

MetricDataResult does not contain dimensions and namespace and it should.

### Reproduction Steps

using the following expressions to test code to get the metric data:
```go
func (metrics *CloudWatchMetricEngine) getCloudWatchMetricsTest(mainCtx context.Context) ([]*common.TS, error) {
    ctx, cancel := context.WithTimeout(mainCtx, 30000*time.Second)
    defer cancel()
    searchExp := `SEARCH(' CPUUtilization ', 'Average', 300)`
    theExampleMetricDataQuery := types.MetricDataQuery{
        Id: aws.String("expecting_metric_search_result"),
        // Label: aws.String("some test search metric"),
        Expression: aws.String(searchExp),
    }
    mdq := []types.MetricDataQuery{theExampleMetricDataQuery}
    input := &cloudwatch.GetMetricDataInput{StartTime: aws.Time(metrics.goStartTime), EndTime: aws.Time(metrics.goEndTime), MetricDataQueries: mdq}
    resp, err := metrics.cwClient.GetMetricData(ctx, input)
    k:=1
    common.DL.Infof("%s", searchExp)
    _,_,k=resp, err,k
    if err != nil {
        common.DL.Infof("%v", err.Error())
    } else {
        for i, mdr := range resp.MetricDataResults{
            common.DL.Infof("\n****Metric result inx: %d**\nId: %s**\nLabel: %s\n***Status code: %s**\nNum data points: %d\n***********", i, *mdr.Id, *mdr.Label, mdr.StatusCode, len(mdr.Timestamps))
        }
    }
    return nil, errors.New("getCloudWatchMetricsTest")
}
```

### Possible Solution

Add dimensions and namespace in the results.

### AWS Go SDK V2 Module Versions Used

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/cloudwatch@v1.21.0

### Compiler and Version used

1.18

### Operating System and version

Any

**Comment by RanVaknin** [comment]
Hi @autopticio ,

Thanks for bringing this to our attention. The source of truth for the file you linked is an automatically propagated from the Cloudwatch API model so the SDK team does not have a way to "include" those fields
If you look at the official docs for [`MetricDataResult`](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_MetricDataResult.html), you can see that this object doesn't contain the `metric name`, `namespace` or the `dimensions` fields on it.

Im not sure if that is a documentation issue because those fields are available on the `Metric` object that you get from `ListMetrics`. 

My recommendation would be to contact the Cloudwatch team using the [feedback](https://docs-feedback.aws.amazon.com/feedback.jsp?hidden_service_name=CloudWatch&topic_url=https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricData.html) form for that GetMetricData operation.

I wish I had a better answer for you. 
Let me know if you are running into any other issues. 

Thanks,
Ran~
