### ISSUE TITLE
Should not backfill session-name for SSO Token Provider

### ISSUE THREAD

**Issue by skmcgrail** [aws/aws-sdk-go-v2#1846]
https://github.com/aws/aws-sdk-go-v2/blob/4b5d0ddcae9bb5134c0756befbe12512d9f4d6b7/config/resolve_bearer_token.go#L59-L67

**Comment by isaiahvita** [comment]
specifically, i believe the conditional linked above should be deleted, and an error should be returned if the SSOSession is not set. this is because the SSOTokenProvider is required to rely on a certain format (the existence of the SSOSession). Falling back to a legacy format used by by a different provider (SSOCredentialProvider) is not supported.
