### ISSUE TITLE
S3Disable100Continue config

### ISSUE THREAD

**Issue by 92ppl** [aws/aws-sdk-go-v2#1856]
### Describe the bug

I find the UseAccelerate UsePathStyle in s3.Options. But I can not find param S3Disable100Continue int the s3 service ,where is it ?``

### Expected Behavior

I want use S3Disable100Continue config

### Current Behavior

I find the UseAccelerate UsePathStyle in s3.Options. But I can not find param S3Disable100Continue int the s3 service ,where is it ?``

> 

### Reproduction Steps

cant find S3Disable100Continue by grep 

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/config v1.17.7
github.com/aws/aws-sdk-go-v2/credentials v1.12.20
github.com/aws/aws-sdk-go-v2/service/s3 v1.27.11

### Compiler and Version used

go version go1.18 darwin/amd64

### Operating System and version

Mac os

**Comment by RanVaknin** [comment]
Hi @crystal-lee,

Thanks for opening your first issue in the AWS SDK repos! We appreciate you engaging in the community :)

Regarding your question:
You don't see `S3Disable100Continue` since it lives in the v1 of the SDK. 

Since you are posting this in the V2 repo I assume this is the version of the SDK you are using.
You can edit the bucket configuration to enable Accelerate by doing a [`PutBucketAccelerateConfiguration`](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3#Client.PutBucketAccelerateConfiguration) request.

Let me know if that answers your question!
Thanks,
Ran~

**Comment by RanVaknin** [comment]
Hi @crystal-lee ,

The V2 SDK does no longer send the `expect :100-continue` header by default , so you will not find that property in the V2 SDK. 
I assume you want to disable it, if that is the case - no action is required. 

Please let me know if you need anything else.

Thanks,
Ran~

**Comment by crystal-lee** [comment]
when i use v2 sdk to upload to ali oss，the error Aws MultiChunkedEncoding is not supported .
And now ,i use v1 sdk add S3Disable100Continue true param, it works ok

**Comment by RanVaknin** [comment]
@92ppl ,

Can you provide a code sample of how you are using the SDK so I can better assist you with this issue?

Thank you,
Ran~
