### ISSUE TITLE
No iface for https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/cloudcontrol

### ISSUE THREAD

**Issue by asilverman** [aws/aws-sdk-go-v2#1865]
### Describe the bug

The [`cloudcontrolapiiface`](https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.44.109/service/cloudcontrolapi/cloudcontrolapiiface) is missing in aws-sdk-go-v2 making it harder to test cloudcontrolapi

### Expected Behavior

publish `cloudcontrolapiiface` in `aws-sdk-go-v2`

### Current Behavior

No interface is being published

### Reproduction Steps

Browse to https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/cloudcontrol and look for an iface, it doesn't exist

### AWS Go SDK V2 Module Versions Used

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/cloudcontrol#section-directories

### Compiler and Version used

N\A

### Operating System and version

N\A

**Comment by RanVaknin** [comment]
Hi @asilverman ,

The testing paradigm is different in V2. iface definitions are backwards incompatible since you are required to "implement" every method in each client. When Service APIs update their models it will break customer code.

Instead, the way we do things in V2 is to use mock clients to implement only the methods we are trying to test.
Please check out the [Unit Testing Doc](https://aws.github.io/aws-sdk-go-v2/docs/unit-testing/), and [this discussion](https://github.com/aws/aws-sdk-go-v2/discussions/1536) for more info.

Let me know if you have any other questions. 
Ty,
Ran~

**Comment by asilverman** [comment]
@asilverman ok I guess that I can use the new paradigm, however the `iface` exists for other `aws-sdk-go-v2` services, that is somewhat confusing.

**Comment by RanVaknin** [comment]
Hi @asilverman ,

If you have a suggestion on improving the migration guide to make this clearer, please feel to submit a PR with the necessary doc changes :) 

SDKs are open source and community contribution is highly encouraged! 

Thanks again for engaging the community and bringing this to our attention.

All the best,
Ran~
