### ISSUE TITLE
support regexp in TagFilters

### ISSUE THREAD

**Issue by chrislinan** [aws/aws-sdk-go-v2#1889]
### Describe the feature

Support regexp in github.com/aws/aws-sdk-go-v2/service/resourcegroupstaggingapi -> GetResourcesInput ->TagFilters 

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/resourcegroupstaggingapi#GetResourcesInput

### Use Case

I have many resources tagged with different values but these values have a fixed pattern, I want to get these resources by one API call.

### Proposed Solution

Maybe we can change the string compare part for tag filters, and change it from fixed string to regexp.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/service/resourcegroupstaggingapi v1.13.19

### Go version used

1.18

**Comment by RanVaknin** [comment]
@chrislinan ,

If I understand you correctly, what you're asking is for TagFilters to be able to accept regex and fetch resources based on that regex? 

If thats the case, it's not something we can help with on the SDK level. Since the SDK is a client, we can modify the input but there is no logic server side to handle that filtering. The Resource Groups Tagging API service team is the one that gets to decide which type of inputs they accept and implement the needed logic respective to that input. 

If I misunderstood you please clarify the feature request so we can better evaluate it.
Thanks,
Ran~

**Comment by chrislinan** [comment]
Hi @RanVaknin, You are right, that's what I mean. Thanks for your answer.
