### ISSUE TITLE
Missing Paginator For Eventbridge

### ISSUE THREAD

**Issue by bbernays** [aws/aws-sdk-go-v2#1901]
### Describe the bug

Most services have a `Paginator` that hides the complexities of pagination specific to that service. Some services like Eventbridge do not have a `paginator` which means that users need to handle this themself. 

### Expected Behavior

Keeping in line with other services (AppRunner) all paginated calls should have a paginator

### Current Behavior

No paginator implemented

### Reproduction Steps

Look at documentation

### Possible Solution

How can we go about adding a paginator? It seems like the definition comes from the `api-model` in the codegen directory. If I were to open a PR adding the following attributes under each paginated API for Eventbridge, would that be accepted or does it have to come from the service team?

```
                "smithy.api#paginated": {
                    "inputToken": "NextToken",
                    "outputToken": "NextToken",
                    "pageSize": "MaxResults"
                }
```

https://github.com/aws/aws-sdk-go-v2/blob/08f1f0b3e3d3f09b699c84f1f5b56b026fba6e15/codegen/sdk-codegen/aws-models/apprunner.json#L1479-L1483

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/service/eventbridge v1.16.17

### Compiler and Version used

go version go1.19.1 darwin/arm64

### Operating System and version

MacOS

**Comment by RanVaknin** [comment]
Hi @bbernays ,

Thanks for opening this feature request.

Unfortunately like you probably noticed, the paginators are defined in the codegen part of our codebase. This means that the service team owns that and it cannot be added to the SDK otherwise.

I have opened a feature request internally with them, but in the spirit of transparency I'll say that these internal tickets don't always get responses, and if they do it takes a long while. 

Since there is no action item here for the SDK team, I will close this thread and ask you to check back in the future in case they have accepted the FR and decided to implement.

Thanks again for your engagement in this community!
Ran~

`#P74688309`
