### ISSUE TITLE
Make SigV4a signer public so it can be used directly

### ISSUE THREAD

**Issue by jwineinger** [aws/aws-sdk-go-v2#1935]
### Describe the feature

The v4a signing code lives under an "internal" path which prevents any other golang packages from importing it. I propose that this code be moved into a path where packages are able to import and use it directly.

### Use Case

I'm interested in contributing a change to https://github.com/open-policy-agent/opa so that it can retrieve files (OPA "bundles") from an S3 multi-region access point. The OPA codebase does not use an S3 client since it has a generic HTTP config to retrieve files from any configured URL. However, it does have config to instruct OPA to sign requests for S3, but currently only using SigV4. This is not suitable for retrieving from an MRAP though, and needs to be updated for SigV4a.

It is vastly preferable to me to import a library to do this, and it seems that the code exists here to do exactly what I need. The problem is that it is marked as internal, and so the golang toolchain will not import it.

Some golang additions to https://github.com/aws-samples/sigv4a-signing-examples would be fantastic as well.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/internal/v4a

### Go version used

go version go1.19.3 darwin/arm64

**Comment by RanVaknin** [comment]
Hi @jwineinger ,

Usually service teams define their interfaces for working with the various SDKs. For SigV4a the SDKs never got a formal required interface to work with. We implemented it internally so that when the time comes and there are official requirements, our changes would not be backwards incompatible and break customers' code. 

At this time I'll have close this PR since there's a backlog item for this and when this is implemented it will get standardized across all the available AWS SDKs. I'm sure the team that owns that API is aware but these things take time. 

I wanted to thank you for taking the time and opening a PR. We really appreciate engagement in this community.

All the best,
Ran~

**Comment by AmitKatyal-Sophos** [comment]
Is there a plan to prioritise this request ?

**Comment by lucix-aws** [comment]
#2634

**Comment by prashil-g** [comment]
We are blocked on this. Any ETA for this

**Comment by lucix-aws** [comment]
https://github.com/aws/aws-sdk-go-v2/discussions/2812
