### ISSUE TITLE
Be more consistent with types

### ISSUE THREAD

**Issue by frioux** [aws/aws-sdk-go-v2#197]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?

f401f4e72ca19632543be38c564a063827084a01

### Version of Go (`go version`)?

`go version go1.10.1 linux/amd64`

### What issue did you see?

Creating an instance uses the InstanceType type, but other instance interactions do not, such as `ModifyInstanceAttributeInput` which uses `*AttributeValue`

### Steps to reproduce

```golang
	_, err = svc.ModifyInstanceAttributeRequest(
		&ec2.ModifyInstanceAttributeInput{
			InstanceId:   instanceID,
			InstanceType: InstanceTypeT1Micro, // this is an error, but shouldn't be
		},
	).Send()
```

**Comment by xibz** [comment]
Hey @frioux, thank you for reaching out to us. We definitely to try to enforce API consistency, but it looks like this was not caught. It could also be possible that the enum type was introduced later as well. The best workaround would be to cast it and use the `aws.String` utility function.

```go
_, err = svc.ModifyInstanceAttributeRequest(
		&ec2.ModifyInstanceAttributeInput{
			InstanceId:   instanceID,
			InstanceType: aws.String(string(InstanceTypeT1Micro)),
		},
	).Send()

```

I am going to go ahead and close this as we cannot change the types since that would introduce a breaking change. If you have anymore feedback or concerns please reach out to us again!
