### ISSUE TITLE
SESv2 API should use `io.ReadSeeker` Data type in `RawMessage`(short issue description)

### ISSUE THREAD

**Issue by kayrus** [aws/aws-sdk-go-v2#2013]
### Describe the feature

Big emails (up to 40MB) consume a lot of memory. Considering that AWS SDK retries on errors, this data may last for a long time in memory. I'd suggest to convert `sesv2.RawMessage.Data` from `[]byte` ([see](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sesv2@v1.16.1/types#RawMessage)) to `io.ReadSeeker` (like in `s3.PutObjectInput.Body` [see](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#PutObjectInput)), or add an alternative way to achieve a "stream" way.

### Use Case

Parallel processing of multiple heavy email bodies cause high memory usage.

### Other Information

cross posting from https://github.com/aws/aws-sdk-go/issues/4473

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

general

### Go version used

general

**Comment by RanVaknin** [comment]
Hi @kayrus ,

Thanks for opening this feature request. I have discussed it with the team and raised your concern, however unfortunately we cannot implement the change. 

The issue is that the SDK input types (and 99% of the SDK code) are auto-generated from the API models of the respective AWS service the client interacts with. 

For S3 body:
```json
"Body": {
                    "target": "com.amazonaws.s3#StreamingBlob",
                    "traits": {
                        "smithy.api#default": "",
                        "smithy.api#documentation": "<p>Object data.</p>",
                        "smithy.api#httpPayload": {}
                    }
                },
```

vs SESv2's Data:
```json
        "com.amazonaws.sesv2#RawMessageData": {
            "type": "blob",
            "traits": {
                "smithy.api#documentation": "<p>The raw email message. The message has to meet the following criteria:</p>\n         <ul>\n            <li>\n               <p>The message has to contain a header and a body, separated by one blank\n                    line.</p>\n            </li>\n            <li>\n               <p>All of the required header fields must be present in the message.</p>\n            </li>\n            <li>\n               <p>Each part of a multipart MIME message must be formatted properly.</p>\n            </li>\n            <li>\n               <p>Attachments must be in a file format that the Amazon SES API v2 supports.\n                    </p>\n            </li>\n            <li>\n               <p>The entire message must be Base64 encoded.</p>\n            </li>\n            <li>\n               <p>If any of the MIME parts in your message contain content that is outside of\n                    the 7-bit ASCII character range, you should encode that content to ensure that\n                    recipients' email clients render the message properly.</p>\n            </li>\n            <li>\n               <p>The length of any single line of text in the message can't exceed 1,000\n                    characters. This restriction is defined in <a href=\"https://tools.ietf.org/html/rfc5321\">RFC 5321</a>.</p>\n            </li>\n         </ul>"
            }
        },
```

You can see that SES has modeled `Data` as a regular "blob", while S3 modeled `Body` as "StreamingBlob".  This is not something the SDK team can change, and changes from the service team on the data layer would mean backwards incompatible changes. 

For what it's worth, I think your request is very reasonable. We could implement a conversion plugin of some sort, but historically hand-written implementations are painful to maintain and set an unreasonable expectations that they would exist in future versions (much like other customizations that were present in v1 and don't exist in v2)

I appreciate you taking the time to open the feature request even after I declined it on our v1 repo. I can guarantee that all feature requests are discussed and considered, and I encourage you to reach out if you have any other ideas / problems that we can address.

Thanks again,
Ran~
