### ISSUE TITLE
Get rid of string pointers, int pointers, aws.String(), etc

### ISSUE THREAD

**Issue by veqryn** [aws/aws-sdk-go-v2#205]
The use of pointers (string pointers, integer pointers, etc) all over the SDK really goes against how Golang is supposed to be written.

I realize that pointers (or an optional-type) may still need to be used in places where a value or field is optional and the zero-value is actually meaningfully different than a nil pointer.  However, the vast majority of the time there is no difference between the zero-value and a nil pointer.

This is really ugly:
```go
svc.PutObjectRequest(&s3.PutObjectInput{
	Bucket: aws.String("myBucket"),
	Key:    aws.String("myKey"),
	ACL:    s3.ObjectCannedACLPublicRead,
	Body:   body,
})
```

It should be:
```go
svc.PutObjectRequest(&s3.PutObjectInput{
	Bucket: "myBucket",
	Key:    "myKey",
	ACL:    s3.ObjectCannedACLPublicRead,
	Body:   body,
})
```

**Comment by veqryn** [comment]
I'd like to add that using a pointer communicates something.

In the case of builtin types like strings and integers, using a pointer communicates that there is a difference between `s3.PutObjectInput{ Bucket: aws.String("") }` and `s3.PutObjectInput{}`.
It says that a nil/missing field is perfectly acceptable and legal.
It also says that a nil/missing field and a pointer to an empty string are different and will result in objects being put into different buckets.

If you accepted non-pointer values, you are communicating that there is no difference between `s3.PutObjectInput{ Bucket: "" }` and `s3.PutObjectInput{}`.
This says that an empty string is the same as not filling in this `Bucket` field.
If the `Bucket` field is a required field that must be filled in with something, then an empty string or missing field is not a valid input.

This information gets lost when you make every single string field into a pointer-to-a-string.

It isn't just ugly, its also a lost chance to prevent users from making mistakes and misusing the API.  
This should be fixed/changed for the same reason you're moving towards typed enumerations for other fields.

Any string/scalar field where a nil pointer is not a legal input, or where there is no difference between a nil pointer and an empty string (or whatever), should be changed to not use pointers.

**Comment by shawnsmithdev** [comment]
I suspect this is due to generated code.  The REST API this is backed by obviously doesn't know anything about Go and its default types. We should at least aim to have any required scalar fields as values.  If it is reasonably feasible, we could make optional scalar fields values too, but only if the empty value can be unambiguously ignored because it is invalid.

**Comment by xibz** [comment]
Hello @veqryn, thank you for reaching out to us and providing the feedback. Generally users have an issue with the amount of pointers at first,  but realize that there is a reason for it. Mostly it has to do with `nil` meaning not set. If fields were not pointers, you may be sending an empty value, which may be valid for the request, when it wasn't meant to be sent. Our team has discussed various options other than pointers, but we felt that pointers is the most idiomatic to Golang. When something is optional, use a pointer. I hope you can understand where we are coming from, but if you have any more questions regarding this please let us know.

**Comment by veqryn** [comment]
I strenuously disagree.

>  If fields were not pointers, you may be sending an empty value, which may be valid for the request, when it wasn't meant to be sent.
If a nil pointer is valid, then a string pointer must be kept for that field.

> When something is optional, use a pointer.
I do not disagree with this.  If a field is optional, a pointer is the only way.


However, when the field is required (or a nil pointer and an empty string are equivalent), then the library should not be using pointers for those fields.

**Comment by xibz** [comment]
> If a nil pointer is valid, then a string pointer must be kept for that field.

Was this a response to, `If fields were not pointers, you may be sending an empty value, which may be valid for the request, when it wasn't meant to be sent.`? If so, not really following the comparison there.

> However, when the field is required (or a nil pointer and an empty string are equivalent), then the library should not be using pointers for those fields.

And when something goes from required to optional? This would break users code because it is now a different type. That is something we do our best not to do, breaking users code when using the SDK. If you have an alternative solution to that, please let us know.

**Comment by veqryn** [comment]
> If fields were not pointers, you may be sending an empty value, which may be valid for the request, when it wasn't meant to be sent.

In the case above, it appears that the hypothetical field is optional (a nil pointer is valid), and an empty string is a valid  input that is meaningfully different from a nil pointer.  Therefore, string pointers must be kept for this field.


> And when something goes from required to optional?

In any other library, this would be considered a change in the API.
This is important information that should be communicated to the users of this library through bumping of the major version number (you do appear to have semantic versioning, even though you aren't using it) and properly changing the API from a string to a string pointer to show that it is now optional.

**Comment by xibz** [comment]
@veqryn - While I understand your frustration on using pointers, I want to say we did make this decision with the issues pointed out. I am going to go ahead and close  this issue since any changes now would be a breaking change and again, something we don't do without good reason.

**Comment by veqryn** [comment]
That is too bad.
With this library still in alpha/beta/preview stage, it is a good opportunity and time to get this right.

**Comment by xibz** [comment]
Reopening as got a lot of feedback on this

**Comment by daveadams** [comment]
Having used the Go AWS SDK for a few years now, I had this same initial reaction to all the pointers--it does make working with the API _feel_ messy. But I've come to realize that such is the cost of interfacing across language boundaries with APIs that have existed for over a decade in some cases, while providing a usable module.

Idiomatic Go is nice to insist on when you are interfacing only with Go all compiled into the same binary. But this SDK is an interface between Go and the AWS API. And unfortunately idiomatic Go cannot fully represent the remote API's interface on a one-to-one basis. Some compromises have to be made to provide a consistent and reliable SDK for us to use. This seems like a very minor one, all things considered.

The last thing I'd want to happen is for the few required fields to become plain strings, and everything optional to remain pointers. That's a recipe for massive confusion, IMO.

**Comment by xibz** [comment]
@daveadams - Thanks for the feedback! An idea we've been looking into is optional types. Meaning fields would by optional types in a structure. This idea has come up multiple times and we wanted to get users feedback before we closed this issue! What are your thoughts on something like

```go
type Foo struct
    Bar OptionInt
    Baz *QuxStruct
}

type QuxStruct struct {
    Moo OptionalString
}

func OptionTypes() {
    f := Foo{
        Bar: aws.Int(10),
        Baz: &QuxStruct{
            Moo: aws.String("Hello"),
        },
    }

    if f.Bar.Int64() < 15 {
        fmt.Println("Hello world!")
    }
}
```

**Comment by veqryn** [comment]
@daveadams I get that the aws sdk's must be created in many, quite different, languages.  If aws used grpc, then any of my complaints over the style of generated libraries and their usage would more likely be with the makers of grpc and not really with aws.  Because aws isn't using proto/grpc, and instead is generating their own client libraries, they have quite a bit more control over how something gets generated.  And with their move to a version 2 of the golang sdk, with some of the expresses reasons being stronger typing (enums, etc) and ease of use / discoverability, I think it is good to bring this up and have it addressed.  I am neither new to golang nor the aws sdk, and I believe I have a very valid concern.

When I see an api that takes a struct like this:
```go
type FooRequest struct {
    Name string
    Metadata *string
}
```
I know immediately that `Name` is a required field, and `Metadata` is an optional field.
The API documentation already specifies this, so the actual SDK's API should match.
This isn't just proper golang, it is proper use and communication of an API.



@xibz What would OptionInt and OptionalString actually be?  (I am assuming something similar to `sql.NullString`?)  What would use for required/non-optional fields, just a regular string/int?

**Comment by xibz** [comment]
@veqryn - yes, equivalent to the `sql.NullXxx` types. For required fields, it would still need to be the optional types, due to backward compatibility of things going from required to optional. I know this doesn't sound as nice as it could be, but having a surprise break on a point release would be a horrible user experience. Perhaps go modules may help with that?

**Comment by jasdel** [comment]
Thanks for the feedback @veqryn  and @daveadams. Prior to releasing the developer preview of the V2 SDK we ran an usability study and found that the mixture of pointer vs non-pointer wasn't clear, and confused nearly all of the users we surveyed. This wasn't a scientific study, but this and the following reasons are the reason the SDK has not mixed.

In addition we discovered a few interesting things about mixing value and pointer types.

1.) a value type doesn't necessarily mean the value is required, but instead means that the consumer  (e.g. service) of the value shouldn't distinguish between unset and zero in the message. In this case the consumer should have logic to apply correct behavior to zero values. For Strings this is generally an easier argument because rarely is empty string a valid value. But for other scalar times the argument is much more difficult. With the modeling that is available to the SDKs it is not known if the zero of a value is valid or not. Required only states that a value must be provided, and its up to the service to determine if the zero value for a member is a valid value or not.

2.) value types become impossible to validate for client side. This means the SDK could not detect if the user intentionally left the value as zero, or accidentally. Since the SDK has no way to distinguish the difference this can lead to unexpected and surprising behavior in APIs where a zero value for a field is valid. 

3.) Like @xibz mentions, services are free to change required fields to optional at any time. Using a consistent compatible typing prevents breaking changes to the users of the API.

Here are a few related discussions in the V1 SDK on this topic:  
* aws/aws-sdk-go#294
* aws/aws-sdk-go#363

**Comment by veqryn** [comment]
@jasdel 
1. Yes, I mention this a couple times in my second post.
2. Any field where there is an effective difference between the zero-value and nil, would have to be left as a pointer.  I also mentioned this in my second post.
3. I guess I can appreciate this, given the number of services aws has.

So, this may be of interest to you; many other data interchange formats have had to deal with the same or similar questions posed here.
If you ever used proto2 and proto3 (via GRPC, etc), you will notice that they went from having required and optional fields in proto2 (with pointers in the generated golang code), to not having them in proto3 (and no pointers anywhere).
Having designed and written several API's using proto3 and grpc (and a http rest gateway), I can say that are at least as good as my hand written rest api's.  It takes a second to get over not having null-able fields, though I feel golang's extensive use of value types prepared me a bit for it.

I've having trouble finding the original discussion links, but a decent summary of it can be found here:
https://github.com/protocolbuffers/protobuf/issues/2497#issuecomment-267422550
> We dropped required fields in proto3 because required fields are generally considered harmful and violating protobuf's compatibility semantics. The whole idea of using protobuf is that it allows you to add/remove fields from your protocol definition while still being fully forward/backward compatible with newer/older binaries. Required fields break this though. You can never safely add a required field to a .proto definition, nor can you safely remove an existing required field because both of these actions break wire compatibility. For example, if you add a required field to a .proto definition, binaries built with the new definition won't be able to parse data serialized using the old definition because the required field is not present in old data. In a complex system where .proto definitions are shared widely across many different components of the system, adding/removing required fields could easily bring down multiple parts of the system. We have seen production issues caused by this multiple times and it's pretty much banned everywhere inside Google for anyone to add/remove required fields. For this reason we completely removed required fields in proto3.
> After the removal of "required", "optional" is just redundant so we removed "optional" as well.

https://softwareengineering.stackexchange.com/questions/350443/why-protobuf-3-made-all-fields-on-the-messages-optional
> proto3 makes a number of changes aimed (as I understand it) at making it far more usable in cross-platform scenarios. Explicit tracking of "assigned" vs "not assigned but reporting the default value" can be very hard to implement on some of the target platforms, and can also be confusing to use. As such, proto3 adopts a much simpler approach:
> 1. The implicit default value is the natural zero value (numbers / enums), false (booleans) or the empty string (strings)
> 2. Only the implicit default is allowed; no other default values are permitted
> 3. If a field has that default value, it is not serialized; it doesn't matter whether it was assigned explicitly to zero / false / empty-string vs never assigned
> 4. Because of this, there is no concept of "required", since "explicitly assigned a zero value" and "never assigned a value" look identical
> 
> `In proto3 it is possible to create a half backed but perfectly valid Location by not providing one of the required fields.`
> The other value is: zero. The fact that you didn't explicitly assign it to zero is moot. Whether or not this is desirable is up to you, but it makes sense to me and is how a lot of "initialize a new object / struct" works on a wide range of platforms.
> `Isn't worse to move extra validation code to each client checking that all required fields have valid values?`
> There's nothing to validate! The layout is exactly what it would be if the value zero was explicitly assigned. If that is legal, it is legal. If it is illegal (because zero doesn't make sense to you), it is illegal; but it would be illegal whether it was explicit or implicit. The amount of validation involved doesn't change.
> `Isn't that a big drawback when creating a schema based serialization format for exchanging data between clients?`
> Not usually, no... especially since the schema version is explicit. If you want to use proto2: use proto2. Nothing changes automatically.


@xibz I'm not really sure what that would solve.  The reason `sql.NullString` exists, is so that it can implement the `Scan` function.  There aren't any interfaces I know of that your fields need to fulfill, so it seems like it would just be an extra layer of indirection with no upside.  Nil checks would just get replaced with checks for `IsSet()` or something, which isn't solving anything.
My preferences, in order:
1. Value types for all fields that are either required or where there is no difference between the default/zero value and nil.  Optional fields where there is a difference between nil and the default value, will have to stay pointers.
Alternatively, follow proto3's lead and make everything a value type.  Your API and documentation would then have to be modified to consider the default value and unset/nil as being the same. (Probably too large of a company-wide breaking change, but maybe at least all new services and api's can have this in mind...?)
2. Keep everything as pointers.
3. A mix of pointers and optional types.

**Comment by xibz** [comment]
@veqryn - Except if you didn't care about zero values, it'd clean that code up. Multiple languages follow this pattern as their solution to optional types. However, out of all solutions proposed, this to me seems like it would be the most flexible other than pointers.

For 1, would definitely be a company-wide breaking change, so I really don't think we could be on board with that. If we allow for only new services, it creates an inconsistency along with other major problem :(.

**Comment by shawnsmithdev** [comment]
Given that there's no encoding of "empty is valid/invalid" in the API models (or even what "empty" means), and that required-ness of fields in the model is mutable upstream, the status quo (pointers everywhere) seems unfortunate but unavoidable.

I don't think optional types are useful in this situation relative to plain pointers.

**Comment by daveadams** [comment]
@xibz  I'm also not seeing a big benefit to using Optional types over pointers, at least not from the example given. The forcing functions (eg `.Int64()`) would turn an unset value into Go's zero value for the type, I assume?

There might be some positive side effects to using universal optional types, just in terms of enforcing more discipline on how you feed values into the API. However, my first instinct is that that benefit would not outweigh the extra confusion of replacing all native types with API-specific wrappers.

Ultimately, though, for my own purposes, my top priority would just be for the SDK to be systematic and consistent throughout, whatever approach is chosen. Getting over the initial learning curve was tough, but once I comprehended the system by which the APIs were wrapped for Go, it made using additional APIs much much simpler.

**Comment by veqryn** [comment]
The more I think about it, the more I feel moving in same the direction as proto3 did, with only using value types for scalar values, would be the best and most idiomatic approach.

AWS probably isn't at a place where that can be done right now.  (Though all new services should be forward looking with how they design their api, so that this can one day be done.)

**Comment by jasdel** [comment]
Thanks for the feedback. I can see where proto3 makes sense for API design. With a strict design that there is no difference between unset, and zero value for an API member. With that said, AWS's API design has several existing use cases where unset and zero value are semantically different.

Even if a new AWS service were to be created which embraced the idea of unset and zero value being equivalent I'm don't think the SDK could use an alternative parameter typing pattern for that service. Using an alternative pattern, (e.g. value instead of pointer) for a subset of services would be a similar issue as required vs "optional" parameters being value vs pointer, just at a client instead of API member scope. This would make it harder for users of the SDK to switch between services, or pickup a new service.

**Comment by jasdel** [comment]
To circle back to the original request of this issue to remove pointers from SDK api operations. I am not confident that the SDK could successfully switch away from pointers to value types for API members. We've identified the negative use case of using asymmetric member typing (required:values, optional:pointers), inability to validate require members, and the cognitive complexity non-language provided option types have.

Since SDK doesn't have the metadata stating if the zero value of an API member is valid or not, the SDK must fallback to the most flexible member type, pointers. Enums are the only type the SDK can make this assertion in all cases. The v2 SDK currently uses values for slices, and maps, but this is not a guaranteed contract. We're still evaluating if slices and maps will be required to go back to pointer types.

We'd be glad to review additional design or ideas for how the SDK could improve its user interface, but with the information and discussions we've been having I think the SDK still needs to use pointers for API members.

**Comment by veqryn** [comment]
I don't have any more feedback.

**Comment by mentalisttraceur** [comment]
For the record, I personally don't understand the big deal with making "required became optional" a breaking change at the Go library level.

Why must the code update be backwards compatible just because the API on the wire is backwards compatible?

I know there is a lot of vague cultural resistance across the entire software development industry against major version numbers rapidly rising, but why?

I don't care if the Go SDK is at version 2 or version 42, or if I'm using version 2 while version 42 is available, **so long as** I can easily find a changelog, see visually clear "Breaking Changes" sections for each major version bump, and easily scan those changes to see what changed.

If 39 of those 40 versions have a single "Breaking Changes" bullet point saying

> * Required field became optional: `{{ package }}.{{ function/struct }}.{{ field name }}`

I'd honestly love if more repos did that (so long as the format and word order of the line stayed consistent).

For me personally, it would make it extremely easy to spot which versions actually changed anything other than that, to visually figure out which major version upgrades would actually break my code, and to incrementally keep up with breaking changes with small tightly scoped patches to my code, which are trivial to validate and low-overhead to review.

Bigger-picture, I think if that became the norm across our industry (or even just Go language community more narrowly), it would significantly increase the agility with which the whole industry upgrades code to newer versions of code. 

Especially considering that Go's approach to modules was designed precisely to allow a code base to depend on multiple major versions of a package at the same time anyway.

**Comment by dpantke** [comment]
I found this thread quite interesting to read, and since your comment is recent I felt compelled to kibitz on it. :)

> Why must the code update be backwards compatible just because the API on the wire is backwards compatible?

> I know there is a lot of vague cultural resistance across the entire software development industry against major version numbers rapidly rising, but why?

Because changes in implementations inside the SDK need to move at a different rate than interface changes. The best example I can give is a security vulnerability: A security vulnerability in a part of the library that touches all services has to be fixed, and PRONTO. If the project has been introducing breaking changes in the normal release cadence, and users of the SDK get used the behavior of "use all the versions!", you'll find that the amount of work to implement the security patch to be simply enormous, as patching the security vulnerability requires that you now go to all of the versions you've utilized in the history of the project and deal with all of those breaking changes, or you have to back-port the security fix to all versions that you use (you have to assume that, if the maintainers of the library/SDK take a "rapidly increasing major version" approach, the amount of energy available to back-port to previous major versions will be highly limited ). There are some other ways of handling this problem, but none of them are "good":

- You can adopt a standard in your project of always staying within X distance of the latest major. However, the older the project gets, you do get "cold" code where the energy in updating just to keep up with library changes essentially amounts to waste. After a certain combinatorial point you'll find that you no longer ever actually add new features to the project.
- You can do what distro maintainers do ( and a good chunck of the reason distros exist at all! ): implement a fork of the codebase that is intentionally behind, so the mainline project can break at will, but you won't. The more widespread a technology base gets, the more likely that this will happen, but you have to reach a critical mass point where the amount of old code is SO large that maintaining a team to handle the fork is cheaper than dealing with all the downstream code.
- Split the code up such that the blast radius of these changes is highly limited. Certainly doable, but comes with drawbacks, as you now externalize what used to be internal interfaces across the (new) version boundary: things like the AWS session by itself now needs a more formal definition because the service interfaces don't move in lockstep. And as much as "make the version boundary more precise" has been a very popular design practice in the industry ( witness microservices architectures ) , it has practical limits to it. It also isn't conducive at all to code generation semantics ( you can _start_ with generated boilerplate, but good luck afterwards ).

I've seen a ton of cases where ensuring that the wire protocol is "pristine", and the SDK library is messy with backwards compatibility compromises is the best answer to a hard problem. And eventually AWS will need to deal with the the problem of all of their SDK implementations being so filled with design compromises because of the popularity of adoption that they will have to deal with them in the wire protocol itself, but it appears they don't feel like they have reached that pain point yet. Reference the comments earlier in the thread w.r.t. proto3: Google reached the internal tipping point where they felt it was good to actually solve this impedance mismatch in the wire protocol itself, which requires implementation changes in both the producer and the consumer to adopt. We'll have to wait and see how long it takes for AWS to get to that point, and after that the GO SDK might require less contorting. :)

**Comment by mentalisttraceur** [comment]
@dpantke Thank you, that helped me see the merit in it.

I do still think that many tiny breaking changes could help enable and encourage downstream projects to update their dependencies faster, but that requires culture change and widespread push for regular downstream dependency maintenance (like how at some point in our history humanity had to learn to brush their teeth daily to significantly reduce the odds of dental problems, and now that's just something we mostly accept spending a little time every day on) - it that doesn't happen, the problems you mention are likely.

And your post has done a good job of reminding me of the human reasons that make it unlikely.

**Comment by buddyspike** [comment]
I've been using Go SDK for a couple of months now and I can echo @veqryn concerns here. It makes it somewhat awkward to use SDK. It would be good to hear about some concrete examples of where `""` needed to be treated differently to `nil` in the API. It would at least help the users rationalise this behaviour.

**Comment by avishay28** [comment]
> I've been using Go SDK for a couple of months now and I can echo @veqryn concerns here. It makes it somewhat awkward to use SDK. It would be good to hear about some concrete examples of where `""` needed to be treated differently to `nil` in the API. It would at least help the users rationalise this behaviour.

Think about situations where you want to do partial updates. For example you have entity that have three string fields, you want to allow clients to update only one of the fields, leaving the other two untouched, and in addition you want to allow clients to pass empty values to "reset" the field (I saved middle name in my profile, now I regret and I want to remove it, make it empty again). How would
You do that without pointers?

**Comment by Av1shay** [comment]
> I've been using Go SDK for a couple of months now and I can echo @veqryn concerns here. It makes it somewhat awkward to use SDK. It would be good to hear about some concrete examples of where `""` needed to be treated differently to `nil` in the API. It would at least help the users rationalise this behaviour.

Think about situations where you want to do partial updates. For example you have entity that have three string fields, you want to allow clients to update only one of the fields, leaving the other two untouched, and in addition you want to allow clients to pass empty values to "reset" the field (I saved middle name in my profile, now I regret and I want to remove it, make it empty again). How would
You do that without pointers?
