### ISSUE TITLE
s3 HeadObject still doesn't return types.NotFound error

### ISSUE THREAD

**Issue by sachevl** [aws/aws-sdk-go-v2#2084]
### Describe the bug

issue #1049 claims to add `NotFound` as an error for `HeadBucket` and `HeadObject` methods. However proper error is not returned still

### Expected Behavior

```
_, err := client.HeadObject(ctx, &s3.HeadObjectInput{
  Bucket: aws.String(bucketName),
  Key:    aws.String(key),
})
if err != nil {
  var nf *types.NotFound
  if errors.As(err, &nf) {   // <---------------- Expected to be true on http 404
  }
}
```

### Current Behavior

Current behavior doesn't cast `err` to `types.NotFound` when object doesn't exist

### Reproduction Steps

run the code from expected behavior against non existing s3 object

### Possible Solution

Fix smithy model. Add unit tests to ensure correct error casting

### AWS Go SDK V2 Module Versions Used

the latest

### Compiler and Version used

go version go1.20.3 linux/amd64

### Operating System and version

AL2

**Comment by RanVaknin** [comment]
Hi @sachevl ,

Thanks for opening the issue. I'm able to confirm this is an issue. This occurs because we parse the error type from the request body. Since HeadObject and HeadBucket requests don't return a body, the SDK should check the headers for the error type, and it doesn't do that yet. 

This requires customization. I'll add to the backlog.

Thanks,
Ran~
