### ISSUE TITLE
Grafana Workspace Network Access Control required entries

### ISSUE THREAD

**Issue by gingersnapz** [aws/aws-sdk-go-v2#2123]
### Describe the bug

Grafana resource type NetworkAccessConfiguration requires a value for both **PrefixListIds** and **VpceIds**.

However, in cli and in console, both are not required, only one or both. 

### Expected Behavior

When using the Go SDK with just a prefix list or with just a VPC endpoint id, the workspace should successfully create.

### Current Behavior

 Error: creating Grafana Workspace: InvalidParameter: 1 validation error(s) found.
        - missing required field, CreateWorkspaceInput.NetworkAccessControl.VpceIds.

OR 

 Error: creating Grafana Workspace: InvalidParameter: 1 validation error(s) found.
        - missing required field, CreateWorkspaceInput.NetworkAccessControl.PrefixListIds.

### Reproduction Steps

Attempt to create a Grafana workspace with network access control and include only a prefix list id OR a VPC endpoint id.

### Possible Solution

Remove the logic that requires both as input. Add validation that verifies at least one is provided.

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2@v1.17.4

### Compiler and Version used

go version go1.20.3 darwin/amd64

### Operating System and version

macOS Ventura 13.3.1

**Comment by Blacknight1260** [comment]
I don’t know what the fuck this all is take me off your lists!

**Comment by kellertk** [comment]
Hi @Blacknight1260. As I've mentioned before, please take your concerns to [AWS Support](https://aws.amazon.com/contact-us/). 
 If you are having trouble with GitHub as a platform, you need to [reach out to GitHub](https://support.github.com/).

Please discontinue posting unconstructive comments on AWS GitHub repositories. Further violations of the [AWS Open Source Code of Conduct](https://aws.github.io/code-of-conduct) will result in you being banned from interaction with AWS on GitHub.

**Comment by RanVaknin** [comment]
Hi @gingersnapz,

Based on the documentation for [`NetworkAccessConfiguration`](https://docs.aws.amazon.com/grafana/latest/APIReference/API_NetworkAccessConfiguration.html), both `PrefixListIds` and `VpceIds` are required parameters. 

>However, in cli and in console, both are not required, only one or both.

```console
$ aws grafana create-workspace --account-access-type CURRENT_ACCOUNT --authentication-providers --client-token foo --permission-type CUSTOMER_MANAGED --network-access-control prefixListIds=pl-1a2b3c4d

Parameter validation failed:
Missing required parameter in networkAccessControl: "vpceIds"
```

Can you please check your CLI code? I'm not sure about the console, but maybe its provisioning the missing values on your behalf. According to the API docs of Grafana and their API model, both params are required. 

Thanks,
Ran~

**Comment by gingersnapz** [comment]
I'll retest with cli again. 
It doesn't make any sense that I can enter in one entry in the console but I'm required to enter both for everything else. What "missing values" would it be entering in if there's nothing to enter?

The biggest issue is Terraform can't really support this because then it always has some empty string for a diff.

Here's what it looks like in console with one entry:

[Grafana in Console](https://imgur.com/a/l25oX65)

**Comment by RanVaknin** [comment]
Hi @gingersnapz ,

Thanks for the clarification and explaining your use case.

I can see that Grafana introduced Network Access Configuration param 3 months ago, so Im guessing this is an oversight in terms of how it was implemented in the console vs the actual API.

>And as far as I can tell, the API documentation only says that networkAccessControl is optional, it doesn't specify that both keys need values within the networkAccessControl block are required unless you count their use of "and" as the only signifier.

`networkAccessControl` is an optional parameter, however if you are specifying it, you have to provide both fields (I linked the doc in my previous comment) but here is a screen shot(note the "Required: yes"):

<img width="711" alt="image" src="https://github.com/aws/aws-sdk-go-v2/assets/50976344/e842c1f9-146d-4978-9b23-1f070fed3fae">


Additionally, you can see a copy of the exported [API model](https://github.com/aws/aws-sdk-go-v2/blob/main/codegen/sdk-codegen/aws-models/grafana.json#L2319-L2330) that the SDK uses in the codegen folder. Each of the fields is annotated with the `Required` trait. 


> The biggest issue is Terraform can't really support this because then it always has some empty string for a diff.
I'm not sure how in this case Terraform is injesting the data. 

I have created an internal ticket with the Grafana Console team to try and fix this. I will update you when I have more info.

In the meantime, my suggestion would be to create your workspace using the SDK for now so it will pass all the validations needed. 


Thanks,
Ran~

`P88338106`

**Comment by gingersnapz** [comment]
I'm just not clear why both are required and not having any option to choose _atleast_ one. I don't really care much that the documentation isn't aligned as far as console, cli, or sdk. 

For an internally hosted application with direct connections from our corporate network to AWS, we only want our Grafana dashboards to be accessible via internal routes (vpce). We have no need to grant access to a prefix list. It seems anti-pattern to require an empty string be passed as part of the requirement to enable network access control versus just assuming that if I don't pass anything for one that it knows I don't want to configure it.

In addition, if I were hosting a Grafana workspace and wanting it to be only public but restricted to specific sources, I wouldn't have a need to pass a vpc endpoint id, just a prefix list id. Very rarely would I see the need to specify both.

**Comment by RanVaknin** [comment]
Hi @gingersnapz,

This is because security is one of AWS's topmost priorities, which is why all AWS APIs, especially those related to security aspects such as network access configurations, operate under an 'explicit allow, implicit deny' policy. This means that, while it might seem logical to ignore a field you don't want to pass (for instance, if you don't need to specify PrefixListIds), which is what the console allows you to do, we want customers to understand that if they only provide VpceIds without PrefixListIds, they are essentially blocking all public access to their workspace. This is achieved by making them explicitly pass in an empty array.

Grafana's API is built this way to prevent customers who want to keep their workspace public and limit access to only a few VpceIds from being caught off guard when their workspace becomes inaccessible publicly after they've only entered VpceIds. By requiring customers to specify both PrefixListIds and VpceIds, we ensure that they are aware of the configuration they are setting for their workspace. This is crucial as enabling or disabling certain Ingress routes for a workspace can lead to a previously functioning workspace becoming unexpectedly blocked.

I think it was confusing because the console provisions that empty array on your behalf, making it not obvious.
Since this is not an SDK issue, and the service team will update their docs to avoid further confusion, I feel confident we can close this issue. 

If you have further questions, please feel free to open a discussion, or create another issue.

Thanks,
Ran~
