### ISSUE TITLE
resourcegroupstaggingapi has invalid endpoints for FIPS

### ISSUE THREAD

**Issue by kgeckhart** [aws/aws-sdk-go-v2#2138]
### Describe the bug

Based on the published documentation for tagging API urls there are no FIPs urls for the tagging apis, https://docs.aws.amazon.com/general/latest/gr/arg.html#argtapi. 

Currently, the endpoints definition for resourcegroupstaggingapi includes urls with `-fips` which do not appear to be valid, https://github.com/aws/aws-sdk-go-v2/blob/main/service/resourcegroupstaggingapi/internal/endpoints/endpoints.go#L115-L128

### Expected Behavior

resourcegroupstaggingapi endpoints for the tagging api gives valid urls when fips is enabled

### Current Behavior

resourcegroupstaggingapi endpoints for the tagging api gives urls which generate errors when fips is enabled. Example,

```
request send failed, Post \"https://tagging-fips.us-east-2.amazonaws.com/\": dial tcp: lookup tagging-fips.us-east-2.amazonaws.com on ...: no such host
``` 

### Reproduction Steps

1. Load an AWS config with the `aws_config.WithUseFIPSEndpoint(aws.FIPSEndpointStateEnabled)` option
2. Create a client with `resourcegroupstaggingapi.NewFromConfig(` using the config
3. Call `GetResources` on the client
4. Receive no such host error

### AWS Go SDK V2 Module Versions Used

```
	github.com/aws/aws-sdk-go-v2 v1.18.0
	github.com/aws/aws-sdk-go-v2/config v1.18.25
	github.com/aws/aws-sdk-go-v2/credentials v1.13.24
	github.com/aws/aws-sdk-go-v2/service/amp v1.16.11
	github.com/aws/aws-sdk-go-v2/service/apigateway v1.16.11
	github.com/aws/aws-sdk-go-v2/service/apigatewayv2 v1.13.11
	github.com/aws/aws-sdk-go-v2/service/autoscaling v1.28.7
	github.com/aws/aws-sdk-go-v2/service/cloudwatch v1.26.0
	github.com/aws/aws-sdk-go-v2/service/databasemigrationservice v1.25.5
	github.com/aws/aws-sdk-go-v2/service/ec2 v1.98.0
	github.com/aws/aws-sdk-go-v2/service/resourcegroupstaggingapi v1.14.11
	github.com/aws/aws-sdk-go-v2/service/storagegateway v1.18.10
	github.com/aws/aws-sdk-go-v2/service/sts v1.19.0
```

### Compiler and Version used

1.20.4

### Operating System and version

macos 13.3.1

**Comment by RanVaknin** [comment]
Hi @kgeckhart,

Thanks for opening this issue. Based on the [FIPS compliance doc page](https://aws.amazon.com/compliance/fips/), the Tagging service does not have a FIPS endpoint at all. 

The default endpoint generation logic appends the `-fips` suffix to any service, unless there's a pre-defined pattern. This is done so that new services and new endpoints can work "out-of-the-box" as a measure of forward compatibility.

>resourcegroupstaggingapi endpoints for the tagging api gives valid urls when fips is enabled

When you are asking the SDK to use a fips endpoint on a service that does not have it defined, `no such host` will be returned, which is the correct behavior.

Let us know if you have any other questions.

Thanks,
Ran~

**Comment by kgeckhart** [comment]
Hi @RanVaknin, thanks for the explanation and it makes sense that the SDK won't give working urls for non-fips services. 

Is there a possibility that the sdk could return a more useful error? This way it would help the caller know that the particular service is not fips compatible. It was rather painful trying to figure out why the URLs being generated were not valid.

**Comment by RanVaknin** [comment]
>Is there a possibility that the sdk could return a more useful error? This way it would help the caller know that the particular service is not fips compatible. It was rather painful trying to figure out why the URLs being generated were not valid.

The answer to your question is yes, we can raise an error specific to endpoints being incorrect but in doing so the forward compatibility aspect will disappear. 

The Go v2 SDK is in the midst of migrating to a new endpoint resolution scheme that will solve a lot of the limitations that we have with the current way of generating and resolving endpoints. I can't provide a timeline but this is actively being worked on (all other newer SDKs are already using it).

For this reason customization to the behavior of the older endpoint scheme is currently not a priority.

I appreciate you bringing this up. I hope I was able to shed some light on the process and the limitation.
Since the solution to this is to not use FIPS for Tagging service, and there's no other action item for the Go SDK team, I feel confident we can close this issue.

If you have any other questions / suggestions or any other concern, please consider opening a discussion on our repo.

Thanks!
Ran~
