### ISSUE TITLE
Helper to extract ECS Service, ECS Cluster names from ARNs

### ISSUE THREAD

**Issue by eightnoteight** [aws/aws-sdk-go-v2#2151]
### Describe the feature

currently helper function to extract ecs service name and ecs cluster name is missing. since the List* apis return ARNs, it would be useful to have a helper function that can extract the names from ARNs

### Use Case

even though Describe* APIs support passing ARNs, for my usecase I had to do logging, make custom identifiers using the names. currently I have written a small helper function below, but it would be nice to have it supported in the sdk itself

### Proposed Solution

```go
func ECSClusterFromARN(clusterarn string) (string, error) {
	arnobj, err := arn.Parse(clusterarn)
	if err != nil {
		return "", err
	}
	after, found := strings.CutPrefix(arnobj.Resource, "cluster/")

	if !found {
		return "", fmt.Errorf("invalid ECS cluster ARN: %s", clusterarn)
	}

	return after, nil
}
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

NA

### Go version used

go version go1.20.2 darwin/arm64

**Comment by RanVaknin** [comment]
Hi @eightnoteight ,

Thanks for your suggestion. I see how a utility function like this could be nice to have. However, it's important to note that SDKs are all code-generated from each service's API model. The operations and response elements available for each client exactly mirror the operations that are available in the service's model.

Since the ECS service currently returns ARNs, not names, it means that it's up to the user to parse the returned data to suit their specific needs, like logging in your case. Introducing low-level utility functions that aren't code-generated into the SDK isn't something the team plans on supporting, because the SDK's focus is to maintain a direct relationship with the service's model.

Ideally, this would be a feature request for the ECS team, asking them to return a `name` field in the API responses. Unfortunately, this isn't something the Go SDK team can directly influence or change.

We appreciate you raising this feature request, and hope that with my explanation you better understand the interworking of the SDK. I encourage you to write us in the future for any other issue that might come up. 

Thanks,
Ran~
