### ISSUE TITLE
Refine SDK's debug logging levels

### ISSUE THREAD

**Issue by jasdel** [aws/aws-sdk-go-v2#216]
The SDK's logging levels are not the easiest to understand, and the default level of `LogDebug` includes a lot of information for each request/response (full header info). Any additional log level under debug will force the request/response header info to also be printed. We should reevaluate the LogLevels and their association and behavior.

Possible solution:
* `LogDebug`: log message states a request has been started and when it completes.
   * Includes retry count, and time to complete.
   * If request fails, error message is logged.
* `LogDebugRetries`: Logs the individual request retry attempts with per request retry error messages.

Should LogDebug payloads be per protocol, or for generic concept, e.g HTTPBody vs Body generally? V1 does payload logging per protocol/transport.

**Comment by elv-gilles** [comment]
I'm facing the situation where I'd like to log `LogDebugWithRequestRetries` and `LogDebugWithRequestErrors` (and occasinally `LogDebugWithSigning`) but not the usual `LogDebug`.

1. As a user of the sdk, I would suggest to make `aws.LogLevel` an interface such that I could use my own implementation for functions `Matches` and `AtLeast`.

2. Even with the current 'minimalistic' `Logger` interface the problem is that the sdk always calls it with a single string parameter instead of passing parameters and letting the default logger make the formatting (see example below).

```
// A Logger is a minimalistic interface for the SDK to log messages to. Should
// be used to provide custom logging writers for the SDK to use.
type Logger interface {
	Log(...interface{})
}
```

call example from:

```
func debugLogReqError(r *Request, stage string, retryStr string, err error) {
	if !r.Config.LogLevel.Matches(LogDebugWithRequestErrors) {
		return
	}

	r.Config.Logger.Log(fmt.Sprintf("DEBUG: %s %s/%s failed, %s, error %v",
		stage, r.Metadata.ServiceName, r.Operation.Name, retryStr, err))
}
```

**Comment by jasdel** [comment]
This feature was implemented in https://github.com/aws/aws-sdk-go-v2/pull/872
