### ISSUE TITLE
GetSecretValueOutput SecretBinary encoding documentation

### ISSUE THREAD

**Issue by stephenlacy** [aws/aws-sdk-go-v2#2161]
### Describe the issue

When retrieving a SecretBinary byte array value that was created with `CreateSecret` the code comment refers to the returned value as a base64 encoded byte array:
```
// The decrypted secret value, if the secret value was originally provided as
// binary data in the form of a byte array. The response parameter represents the
// binary data as a base64-encoded (https://tools.ietf.org/html/rfc4648#section-4) string.
```

The actual value returned is a raw byte array, not base64 encoded.

### Links

https://github.com/aws/aws-sdk-go-v2/blob/2b71c0eac6c4f32a20074c9f60b5ad5f93dff490/service/secretsmanager/api_op_GetSecretValue.go#L89

**Comment by RanVaknin** [comment]
Hi @stephenlacy ,

Thanks for opening this issue. 

The documentation you are seeing is auto generated from the [API model documentation](https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_CreateSecret.html#SecretsManager-CreateSecret-request-SecretBinary) so in the docs there wont be a distinction for SDK specific uses. 

Base64 encoding is necessary to transport binary data over HTTP/JSON. The SDK as an abstraction, provides convenience methods like decode the binary for you so you can use it right away without having to decode it manually. 

Since the documentation is not maintained by the SDK team, it is by the service team, we cannot directly make changes to it.
If you have suggestions for better wording. Please feel free to provide feedback using the [Feedback](https://docs-feedback.aws.amazon.com/feedback.jsp?hidden_service_name=Secrets%20Manager&topic_url=https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_CreateSecret.html#API_CreateSecret_RequestSyntax) button at the top right corner of the doc page. 

Thanks again!
Ran~
