### ISSUE TITLE
Cannot use v2.0.0-preview.5 with Go modules

### ISSUE THREAD

**Issue by F21** [aws/aws-sdk-go-v2#221]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
v2.0.0-preview.5

### Version of Go (`go version`)?
Go 1.11 Linux x64

### What issue did you see?
v2.0.0 includes a `go.mod` file, but the import path in the `go.mod` file is `github.com/aws/aws-sdk-go-v2`. This means that Go modules is not able to import the library because the tag is `v2`, but the path in the `go.mod` file is not `v2`. Go modules will only import `v2.0.0-preview.4` due to the import path in `go.mod` being wrong.

To fix this, the import path in `go.mod` should be updated to `github.com/aws/aws-sdk-go-v2/v2` and all references to `github.com/aws/aws-sdk-go-v2` within the library should also be updated to ``github.com/aws/aws-sdk-go-v2/v2`.

**Comment by shawnsmithdev** [comment]
The tags should never have been `v2`, as we changed the repository between SDK "v1" and "v2", so a `v1` of `github.com/aws/aws-sdk-go-v2` has never existed.

A cleaner but build-breaking approach would be to delete all the existing tags and start over with `v0` or `v1`.

**Comment by jasdel** [comment]
Thanks for reporting this issue. We'd created the v2 SDK's repo prior to the go module proposal, and this is why a combination of `v2` tagging along with the repo name being `aws-sdk-go-v2`. 

To workaround this issue temporarily you can do:

```
go get github.com/aws/aws-sdk-go-v2@v2.0.0-preview.5
```

A `aws-sdk-go-v2/v2` isn't a pattern we'd like to use because of its verboseness, and would prefer to either have the v1 and v2 SDK in the same repo (`aws-sdk-go/v2`) (This wasn't viable until go modules were introduced), or keep the v2 SDK in its own repo. Though we'd probably keep the v2 SDK in its own repo. If we keep the v2 SDK in its own repository (`aws-sdk-go-v2`) then the SDK should switch to using `v0` for its preview build tags and switch to `v1` once GA released. I think we'll need to delete the `v2` build tags. I'm not sure how a `v0` and `v2` tag will work with go modules. We'll need to experiment with this.

**Comment by jasdel** [comment]
Thanks for letting us know about the issue with the SDK and Go Models. During the SDK's preview we'll us `v0.<x>.<y>` release tags. This will allow the v2 SDK to work correctly with Go Models. We'll continue this until the SDK's General Availability (GA) release.
