### ISSUE TITLE
ECR Authorization Token encoding

### ISSUE THREAD

**Issue by pete911** [aws/aws-sdk-go-v2#226]
Please fill out the sections below to help us address your issue.

### Steps to reproduce

```
var svc *ecr.ECR
out, _ := svc.GetAuthorizationTokenRequest(&ecr.GetAuthorizationTokenInput{}).Send()
token := aws.StringValue(out.AuthorizationData[0].AuthorizationToken)
```

Token is base64 encoded and with `AWS:` prefix. This is super unclear and not documented. Token should be already decoded and without prefix at this stage. To get decoded token we need to run:

```
func decodeToken(encodedToken string) (string, error) {

	decodedToken, err := base64.StdEncoding.DecodeString(encodedToken)
	if err != nil {
		return "", fmt.Errorf("decode token: %v", err)
	}
	return strings.TrimPrefix(string(decodedToken), "AWS:"), nil
}
```

would be good to run this before struct is created, or at least provide helper method like the one above and document it.

**Comment by samuelkarp** [comment]
The documentation for this field and its encoding is here: https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_AuthorizationData.html

> A base64-encoded string that contains authorization data for the specified Amazon ECR registry. When the string is decoded, it is presented in the format user:password for private registry authentication using `docker login`.

This field contains the username (`AWS`) and temporary password to be used for authenticating using the Docker Registry API.  The username is not guaranteed to be `AWS`, but is guaranteed to be returned by this API.

**Comment by pete911** [comment]
@samuelkarp thanks for quick reply, my bad, completely forgot `AWS` is user. I understand that this is how API returns it, but I would expect client to do a bit more work to help users. Similar to `aws-cli`. Would be nice to return struct with `User` and `Token` fields where token would be already encoded.

What do you think? Or update godoc that response is encoded <user>:<token> string (I would prefer struct though)

**Comment by samuelkarp** [comment]
I think the godoc already has this comment [here](https://godoc.org/github.com/aws/aws-sdk-go-v2/service/ecr#AuthorizationData) (in general, the SDK uses the same source as the API documentation, so they should be in sync with each other).

I'll let the SDK team comment on what they think (I'm involved on the ECS/ECR/Fargate side), but I see value in having the SDK match the way that the API works, since then each of the language SDKs will function the same.  I don't have a major objection to a function that can decode the authorization token beyond increasing the size of the package interface, but I don't really think that the struct should itself be changed.

**Comment by xibz** [comment]
Hello @pete911, thank you for reaching out to us and thanks for the context, @samuelkarp. The SDK will handle the base64 encoding/decoding for you if it was a `[]byte`, but because it is a `string`, we treat it as such. It looks like the CLI decodes in the same [fashion](https://docs.aws.amazon.com/cli/latest/reference/ecr/get-authorization-token.html). I do agree that having the SDK handle this for you would be great, but as it sits now we cannot change the behavior.

Out of curiosity, why is it that you need to parse out the values?

**Comment by xibz** [comment]
@pete911 - I see. I think the best path forward would to use that decode helper function you provided above or just use any environment variable that allows overriding the authorization token. If you have any more questions or suggestions please reach out to us!

**Comment by samuelkarp** [comment]
@pete911 Here are some options that might help too:

* ECR repositories support [resource policies](https://docs.aws.amazon.com/AmazonECR/latest/userguide/RepositoryPolicies.html).  This means that you can grant other accounts the ability to push or pull images in a repository in your account.  The only difference when calling `GetAuthorizationToken` (or `aws ecr get-login`) is to specify the registry as well.
* We have a [credential helper](https://github.com/awslabs/amazon-ecr-credential-helper) for ECR that can be used with the Docker CLI.  When configured, the credential helper will take care of obtaining the correct credentials on-demand when you run `docker push` or `docker pull`.  The credential helper supports accessing repositories in different accounts (via the resource policies above) and supports loading AWS credentials from the shared credentials file (`AWS_PROFILE=myprofile docker pull ...`).

**Comment by pete911** [comment]
@samuelkarp , @xibz thanks a lot guys, I'll have a look at credentials helper.
