### ISSUE TITLE
Generate APIClient interfaces for all operations

### ISSUE THREAD

**Issue by jeevanragula** [aws/aws-sdk-go-v2#2264]
### Describe the bug

In the AWS V2 Kinesis client, DescribeStreamSummary doesn't have any interface. Some of the other methods have an interface defined but not all of them.

Below is an example where the method is wrapped in an interface.
We can't mock methods while writing unit tests.

```
type DescribeStreamAPIClient interface {
	DescribeStream(context.Context, *DescribeStreamInput, ...func(*Options)) (*DescribeStreamOutput, error)
}
```

### Expected Behavior

The method should be part of an interace.

### Current Behavior

DescribeStreamSummary method is only part of kinesis Client struct. 

### Reproduction Steps

Navigate to kinesis Client Struct.

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2 v1.21.0
github.com/aws/aws-sdk-go-v2/service/kinesis v1.18.5

### Compiler and Version used

1.20

### Operating System and version

Mac

**Comment by RanVaknin** [comment]
Hi @jeevanragula,

The testing paradigm is different in V2. iface definitions are backwards incompatible since you are required to "implement" every method in each client. When Service APIs update their models it will break customer code.

Instead, the way we do things in V2 is to use mock clients to implement only the methods we are trying to test.
Please check out the [Unit Testing Doc](https://aws.github.io/aws-sdk-go-v2/docs/unit-testing/), and https://github.com/aws/aws-sdk-go-v2/discussions/1536 for more info.

Let me know if you have any other questions.
Ty,
Ran~

**Comment by jeevanragula** [comment]
@RanVaknin Yes, I see in V2, there are individual interfaces within each client.
Even in kinesis package, there is an interface for DescribeStream method.
But DescribeStreamSummary doesn't have any interface defined. So the approach has to be consistent for all the methods.

This behavior is observed in multiple other packages as well. 

https://github.com/aws/aws-sdk-go-v2/blob/main/service/kinesis/api_op_DescribeStream.go#L171

```
type DescribeStreamAPIClient interface {
	DescribeStream(context.Context, *DescribeStreamInput, ...func(*Options)) (*DescribeStreamOutput, error)
}
```

**Comment by lucix-aws** [comment]
This "selective" generation of `*APIClient` is actually intentional. See [OperationInterfaceGenerator](https://github.com/aws/smithy-go/blob/main/codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/OperationInterfaceGenerator.java) - we basically only do so when other code needs to depend on that operation (in this case, for generated waiters and paginators, which consume that API).

We also tend to do this manually in HLL code such as in the s3 transfer manager.

The lack of completeness shouldn't be _preventing_ you from doing anything per se given implicit interface satisfaction - you can just declare the missing interface in your own code:

```go
// sdk DOES have a type for this, use it directly
func DescribeStreamCaller(client kinesis.DescribeStreamAPIClient) {
    // ...
}

// sdk DOES NOT have a type for this, define our own
func DescribeStreamSummaryCaller(client DescribeStreamSummaryAPIClient) {
    // ...
}

type DescribeStreamSummaryAPIClient interface {
    DescribeStreamSummary(context.Context, *kinesis.DescribeStreamSummaryInput, ...func(*kinesis.Options)) (*kinesis.DescribeStreamSummaryOutput, error)
}
```

That said I think it's probably reasonable for us to always generate an operation's interface such that people don't have to do so themselves. Pursuant to that I'm going to convert this to a feature request.

**Comment by lucix-aws** [comment]
Updated title accordingly.

**Comment by lucix-aws** [comment]
FYI there _is_ technically language guidance that suggests we _shouldn't_ be doing this - https://tt.amazon.com/P99813334/communication.

That said I'm not really convinced this is a hard and fast rule, nor that it necessarily applies to us in this SDK for a few extenuating circumstances-

* We're already in a sort of hybrid state - we are both the producer _and_ consumer of the interfaces, given that we need to generate some of them to re-use for waiting/pagination. Being in this hybrid state where some are generated and others not has evidently caused confusion given this FR.
* All of this code is generated. There's no operational overhead per se for us to maintain these interfaces other than to own the (trivial) codegen component which

**Comment by lucix-aws** [comment]
FYI there _is_ technically language guidance that suggests we _shouldn't_ be doing this - https://github.com/golang/go/wiki/CodeReviewComments#interfaces.

That said I'm not really convinced this is a hard and fast rule, nor that it necessarily applies to us in this SDK for a few extenuating circumstances-

* We're already in a sort of hybrid state - we are both the producer _and_ consumer of the interfaces, given that we need to generate some of them to re-use for waiting/pagination. Being in this hybrid state where some are generated and others not has evidently caused confusion given this FR.
* All of this code is generated. There's no operational overhead per se for us to maintain these interfaces other than to own the (trivial) codegen component which generates them.

**Comment by lucix-aws** [comment]
I've decided against this for now. Closing.
