### ISSUE TITLE
service/iam: AssumeRolePolicyDocument is a JSON string and requires unescaping

### ISSUE THREAD

**Issue by pete911** [aws/aws-sdk-go-v2#227]
### Version of Go (`1.11`)

Assume role policy document response from `iam.GetRoleRequest` is url encoded

### Steps to reproduce

```
out, _ := svc.GetRoleRequest(&iam.GetRoleInput{RoleName: aws.String(roleName)}).Send()
document := aws.StringValue(out.Role.AssumeRolePolicyDocument)
// document is url encoded need to decode it
decodedDocument, _ := url.PathUnescape(document)
```

Decoding/unescaping should be done before the struct is returned. User should NOT know/care about these things.

**Comment by pete911** [comment]
I don't mind creating PR, but need some pointers, because `service/iam/api.go` (where the code needs to be added) says `Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.`
But cannot find what is calling that `main.go`. I had a quick look at `Makefile` ... Can you point me to some docs about project structure etc.

**Comment by jasdel** [comment]
Thanks for the feature request @pete911. The SDK does not currently have the metadata available to know that the `AssumeRolePolicyDocument` member's value is a JSON string. I suggest using [strconv.Unqoute](https://golang.org/pkg/strconv/#Unquote) instead of `url.PathUnescape`. I think this will ensure consistent results without any side effects.

**Comment by pete911** [comment]
@jasdel is this because the library is generated from templates? quicker/easier to keep multiple libraries written in different languages up to date? Because to me this seems like quick fix.

**Comment by jasdel** [comment]
The AWS SDKs for Go (v1 and v2) are generated from models defined by the API service teams. The SDK will consume these models to generate the SDK's API clients, operation methods, and types. Given the current model information the `AssumeRolePolicyDocument` field is a string value, and the SDK doesn't have a way to know that the value should be unescaped, and is a document. I'll forward this issue onto the service team.

I think what one way we'd like to solve this issue is for fields like `AssumeRolePolicyDocument` to be decorated in a way that allow the SDK to know they are a JSON document, or at a minimum that the SDK should unescape the field's value during unmarshal. 

Also, I mistakenly suggested `strconv.Unquote`. `url.PathUnescape` does look to be best workaround for this issue.
