### ISSUE TITLE
Change to INI file parsing in `config@v1.22.0` and `config@v1.21.0`

### ISSUE THREAD

**Issue by gdavison** [aws/aws-sdk-go-v2#2349]
### Describe the bug

In previous versions, leading whitespace before keys in INI files would be ignored during parsing. A file with leading whitespace such as

```ini
	[default]
	retry_mode = standard
```

would successfully use the `RetryMode` `standard`

Staring in v1.21.0 this file would not be parsed and configuration would silently fail.

### Expected Behavior

One of two options is expected:

1. Leading whitespace would continue to be ignored
2. If the file is not parseable, an error should be returned, or at least a warning should be logged

### Current Behavior

The SDK silently ignores the parsing failure

### Reproduction Steps

In the test `TestParser` (https://github.com/aws/aws-sdk-go-v2/blob/71819e89f49838daa36cf5b2ec5bbc4176490770/internal/ini/ini_parser_test.go#L11), add a case

```go
		{
			name: "section statement leading whitespace",
			r: bytes.NewBuffer([]byte(
				`	[default]
	region="us-west-2"`)), // Ensure there is leading whitespace on this line
			expectedStack: []AST{
				newCompletedSectionStatement(
					defaultProfileStmt,
				),
				newExprStatement(regionEQRegion),
			},
		},
```

This will fail with

> expected:
        	0: {completed_stmt {0 NONE 0 []} false [{section_stmt {1 STRING 0 [100 101 102 97 117 108 116]} true []}]}
        	1: {expr_stmt {0 NONE 0 []} false [{ {4 NONE 0 [61]} true [{expr {1 STRING 0 [114 101 103 105 111 110]} true []} {expr {1  0 [34 117 115 45 119 101 115 116 45 50 34]} true []}]}]}
>        
> received:

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/config v1.22.0

### Compiler and Version used

go version go1.21.0 darwin/arm64

### Operating System and version

macOS 13.4.1

**Comment by lucix-aws** [comment]
Almost certainly a regression from #2226

**Comment by isaiahvita** [comment]
@gdavison i just put up a PR to resolve this issue. While we would have liked the maintain the old behavior of ignoring the extra whitespace in front of a property definition, this will not be possible to support this feature https://github.com/aws/aws-sdk/issues/229

This is because leading whitespace in front of a property definition is now defined as a "sub-property" and subproperties are used to support the feature above. So, we will be throwing a new error as shown in https://github.com/aws/aws-sdk-go-v2/pull/2359

The added changelog will reflect this breakfix.
