### ISSUE TITLE
Accessing Possible Values of an enum Without an Instance

### ISSUE THREAD

**Issue by ChihweiLHBird** [aws/aws-sdk-go-v2#2388]
### Describe the feature

It would be nice if enum values can be accessed without an instance of it.

For example, to get all possible values of [BucketLocationConstraint](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3/types#BucketLocationConstraint.Values), I have to do:

```go
types.BucketLocationConstraintCaCentral1.Values()
```

This is not very intuitive because the `Values` are all available values, not just for a single one. I think a standalone function can be better:

```go
types.BucketLocationConstraintValues()
```

### Use Case

Any case where enum needs to be validated

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2 v1.23.1

### Go version used

go version go1.21.4 darwin/arm64

**Comment by lucix-aws** [comment]
There's an existing idiomatic way to get the desired behavior here - when you need to call some method on a type where the receiver doesn't matter, you can do so on a typecast of the underlying zero value:

```go
types.BucketLocationConstraint("").Values()
```

I don't see us going the suggested route since there's no value add compared to the above.

I'd also point out that it's in generally in our interest to **not** introduce our own derived names into codegenned packages since they could conflict with future service updates.

**Comment by ChihweiLHBird** [comment]
Hi @lucix-aws,
Thanks for the response. The main problem of this is that it's ugly, but I would respect your decision.
