### ISSUE TITLE
LoadDefaultAWSConfig: Automatically get REGION from EC2 metadata

### ISSUE THREAD

**Issue by condemil** [aws/aws-sdk-go-v2#244]
More info can be found from the same issue on v1: https://github.com/aws/aws-sdk-go/issues/1103

**Comment by jasdel** [comment]
Thanks for the feature request @condemil. We'll investigate adding this feature to the SDK. At the minimum the v2 SDK needs to have a better way to enable this functionality.

Currently the v2 SDK has [WithEC2MetadataRegion] but this helper is awkward to use because it requires constructing the EC2 Instance metadata client. Most likely this functionality would be best by creating another `RegionResolver` which can resolve the region from EC2 Metadata if the region has not already been found.

**Comment by ikthorn** [comment]
Is it possible to get the TODO on that struct in the docs with an example of how to do so?  
I expected to generate my aws config and have this provide region but this ec2metadata.New requires a config... since it's just making an HTTP call I don't understand that.
