### ISSUE TITLE
Directconnect FIPS endpoint wrong for US-GOV regions

### ISSUE THREAD

**Issue by brucedewald** [aws/aws-sdk-go-v2#2445]
### Describe the bug

when UseFIPSEndpoint is set, the wrong endpoint is returned for Directconnect in us-gov regions.

### Expected Behavior

Per https://docs.aws.amazon.com/general/latest/gr/dc.html endpoints should be 
directconnect.us-gov-east-1.amazonaws.com & 
directconnect.us-gov-west-1.amazonaws.com

however 

### Current Behavior

they're set to directconnect-fips.us-gov-east-1.amazonaws.com & directconnect-fips.us-gov-west-1.amazonaws.com which do not exist

### Reproduction Steps

I am using this SDK indirectly via the AWS terraform provider, so in terraform provider we have use_fips_endpoint set to true and get the following error: RequestError: send request failed
│ caused by: Post "https://directconnect-fips.us-gov-west-1.amazonaws.com/": dial tcp: lookup directconnect-fips.us-gov-west-1.amazonaws.com: no such host

### Possible Solution

Fix code here: https://github.com/aws/aws-sdk-go-v2/blob/0c7b7e4e24c2e52b6beec87e928196f04af937bd/service/directconnect/internal/endpoints/endpoints.go#L432-L462

### AWS Go SDK V2 Module Versions Used

I do not work for Hashicorp but looks like this should be the accurate source of truth https://github.com/hashicorp/aws-sdk-go-base/blob/main/go.mod

### Compiler and Version used

N/A

### Operating System and version

N/A

**Comment by RanVaknin** [comment]
Hi @brucedewald,

The reason why you see the SDK is unable to resolve a gov cloud + fips for directConenct is because that service does not have a FIPS endpoint for gov regions. Please refer to [AWS FIPS Endpoints by Service
](https://aws.amazon.com/compliance/fips)

<img width="500" alt="image" src="https://github.com/aws/aws-sdk-go-v2/assets/50976344/e74f6823-055b-446e-b1e3-a2a5e74360c1">

Please refer to my explanation of why this is happening [here](https://github.com/aws/aws-sdk-go-v2/issues/2336#issuecomment-1781797308), and let me know if you have any other questions.

All the best,
Ran~

**Comment by brucedewald** [comment]
Thanks for the info @RanVaknin - I made the incorrect assumption that if any region would have FIPS it would be GovCloud and assumed that the endpoints without "fips" in the name were in fact FIPS enabled.
