### ISSUE TITLE
missing Authentication Token

### ISSUE THREAD

**Issue by zaki1991** [aws/aws-sdk-go-v2#2454]
### Describe the bug

I'm trying to use IAM Role to call BatchMeterUsage API, But I have encountered some problems.

```go
package main

import (
	"context"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/sts"
)

const (
	RegionID = "xxxx"
	RoleArn = "arn:aws-cn:iam::xxxx"
	RoleSessionName = "test"
)

func main() {
       cfg := &aws.Config{
		Region: RegionID,
	}

	stsClient := sts.NewFromConfig(*cfg)

	assumeRoleInput := &sts.AssumeRoleInput{
		RoleArn: aws.String(RoleArn),
		RoleSessionName: aws.String(RoleSessionName),
	}

	response, reErr := stsClient.AssumeRole(context.Background(), assumeRoleInput)
	if reErr != nil {
		panic("AssumeRole error, " + reErr.Error())
	}
}
```

### Expected Behavior

Successfully returned AssumeRoleOutput Object.

### Current Behavior

Got an error:
panic: AssumeRole error, operation error STS: AssumeRole, https response error StatusCode: 403, RequestID: c38b4605-add3-42d6-99cb-5dc5020cb0a7, api error MissingAuthenticationToken: Request is missing Authentication Token

### Reproduction Steps

Use AWS SDK for Go (v2)
Try to use IAM Role to call BatchMeterUsage API.

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2@v1.24.1
github.com/aws/aws-sdk-go-v2/service/sts@v1.26.7

### Compiler and Version used

go version go1.17.7 darwin/amd64

### Operating System and version

Mac OS 10.13.6

**Comment by RanVaknin** [comment]
Hi @zaki1991 ,

Thanks for reaching out. 

>Reproduction Steps
Use AWS SDK for Go (v2)
Try to use IAM Role to call BatchMeterUsage API.

The code and error description for what you have here is unrelated to `BatchMeterUsage`, and is related to your assumeRole command. 

The problem here is that your `config` object does not seem to have been initialized with any credential provider. For you to be able to call `AssumeRole`, your application needs to be able to first load credentials, and then using those initial credentials assume the role. 

So should look something like this:
```go
cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion("us-east-1"))
if err != nil {
	log.Fatalf("unable to load SDK config, %v", err)
}

stsClient := sts.NewFromConfig(cfg)

out, err := stsClient.AssumeRole(context.TODO(), &sts.AssumeRoleInput{
	RoleArn:         aws.String("arn:aws:iam::123456789012:role/foo"),
	RoleSessionName: aws.String("bar"),
})
if err != nil {
	panic(err)
}
// rest of your code
```
For more info please refer to our [developer guide](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/).

Let me know if you need anything else.
Ran~

**Comment by zaki1991** [comment]
I have resolved this problem

**Comment by stgleb** [comment]
> I have resolved this problem

could you please share, how did you solved this problem?
