### ISSUE TITLE
DynamoDB TransactionCanceledException documentation out of date

### ISSUE THREAD

**Issue by krzysztofgb** [aws/aws-sdk-go-v2#2457]
### Describe the issue

The AWS SDK Go V2 documentation is out of date for `TransactionCanceledException`.

The documentation says:
> If using Java, DynamoDB lists the cancellation reasons on the CancellationReasons property. This property is not set for other languages.

However, this does not seem accurate based on local debugging (see below) and https://github.com/aws/aws-sdk-go-v2/issues/663#issuecomment-725685931.

![SCR-20240116-nafb](https://github.com/aws/aws-sdk-go-v2/assets/24556218/4987e154-b537-4bc7-aed1-f782043d7697)

### Links

https://github.com/aws/aws-sdk-go-v2/blob/service/dynamodb/v1.26.8/service/dynamodb/types/errors.go#L891

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/service/dynamodb v1.26.6

**Comment by RanVaknin** [comment]
Hi @krzysztofgb ,

Thanks for reaching out. This doc string is coming directly from the documentation model and can only change upstream with the Dynamodb service team as well. 

If you go to the official Docs:
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_ExecuteTransaction.html

You can click on the [Feedback](https://docs-feedback.aws.amazon.com/feedback.jsp?hidden_service_name=DynamoDB&topic_url=https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_ExecuteTransaction.html) button at the top right, fill in the form and that would cut a ticket directly to the Dynamodb team so they can fix it. 

I'm going to close this issue since its not actionable by the SDK team, but I wanted to thank you again for taking the time and submitting the issue. If anything else comes up please let us know.

All the best,
Ran~
