### ISSUE TITLE
Incorrect state returned in VPCEndpoint Object

### ISSUE THREAD

**Issue by gilbahat** [aws/aws-sdk-go-v2#2496]
### Describe the bug

VPCEndpoint object reports its state as "available" (lowercase). this does not conform to the state types in the ec2 types package, and thus vpcEndpoint.State == types.StateAvailable will always fail.

### Expected Behavior

VPCEndpoint state should conform to state types in the ec2 types, including capitalization so that comparisons will work as expected

### Current Behavior

VPCEndpoint object reports its state as "available" (lowercase). this does not conform to the state types in the ec2 types package.

### Reproduction Steps

```

// not sure how to do this with all the SDK init stuff. this is as close as I can get for now.

import (
	ec2Types "github.com/aws/aws-sdk-go-v2/service/ec2/types"
	"github.com/aws/aws-sdk-go/aws"
)

func main() {

input := &ec2.DescribeVpcEndpointsInput{
			for paginator.HasMorePages() {
				page, err := paginator.NextPage(ctx)
				if err != nil {
					return fmt.Errorf("failed to describe VPC endpoint: %w", err)
				}
				if len(page.VpcEndpoints) != 0 {
					vpcEndpoint = &page.VpcEndpoints[0]
					if vpcEndpoint != nil && vpcEndpoint.State == ec2Types.StateAvailable {
						return "found"
					}
				}
			}
}
```

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/service/ec2@v1.142.0 github.com/aws/aws-sdk-go-v2@v1.24.0

### Compiler and Version used

go version go1.21.6 darwin/amd64

### Operating System and version

Darwin heka 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64 x86_64

**Comment by RanVaknin** [comment]
Hi @gilbahat ,

Thanks for reaching out. Unfortunately this is a known issue with the EC2 API model itself, and not something we can fix on the SDK side. We have an internal ticket with the EC2 service team about this(`#P70319347`) , but currently there is no ETA for fix. 

The workaround is to change your `if` statement to check the Endpoint's state as a string value rather than to rely on the incorrectly modeled enum:

```go
if vpcEndpoint != nil && vpcEndpoint.State == "available" {
      return "found"
}
```

Since there is already a [cross SDK ticket](https://github.com/aws/aws-sdk/issues/116) tracking this here. I'll close this one. 

Thanks again, 
Ran~
