### ISSUE TITLE
I Can not retrieve Security Group Name(short issue description)

### ISSUE THREAD

**Issue by whitewhale1075** [aws/aws-sdk-go-v2#2546]
### Describe the feature

In ec2  api call, DescribeSecurityGroupRules doesn't retrieve the name of Security Group.
Is there any reason the name is not possible to retrieve? or I can't find the right output variable that stores the name

### Use Case

To get the name of security group name that related with security group id

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

	github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream v1.6.0 // indirect
	github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.14.5 // indirect
	github.com/aws/aws-sdk-go-v2/internal/configsources v1.3.3 // indirect
	github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.6.3 // indirect
	github.com/aws/aws-sdk-go-v2/internal/ini v1.7.1 // indirect
	github.com/aws/aws-sdk-go-v2/internal/v4a v1.3.0 // indirect
	github.com/aws/aws-sdk-go-v2/service/eks v1.37.1 // indirect
	github.com/aws/aws-sdk-go-v2/service/elasticache v1.34.7 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.11.1 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/checksum v1.3.0 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.11.5 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/s3shared v1.17.0 // indirect
	github.com/aws/aws-sdk-go-v2/service/redshift v1.43.1 // indirect
	github.com/aws/aws-sdk-go-v2/service/s3 v1.50.1 // indirect
	github.com/aws/aws-sdk-go-v2/service/sso v1.17.3 // indirect
	github.com/aws/aws-sdk-go-v2/service/ssooidc v1.20.1 // indirect
	github.com/aws/aws-sdk-go-v2/service/sts v1.25.4 // indirect

### Go version used

1.20.2

**Comment by RanVaknin** [comment]
Hi @whitewhale1075,

To clarify, The AWS SDK mirrors the functionality offered by AWS APIs. The `DescribeSecurityGroupRules` API is designed to return info on security group *rules*, not the security groups themselves, which likely reflects its intended use case. However, we can't be certain about the API team's specific reasons for this design, as we are not privy to their design choices.

For retrieving security group names, you can use the `DescribeSecurityGroups` operation. This operation allows you to query security groups and their details, including names, by various filters such as security group IDs.

While I understand this may not directly address the convenience aspect of your request, it's important to note that extending the `DescribeSecurityGroupRules` operation to include security group names would involve changes to the AWS EC2 API itself, which is beyond the scope of updates we can make within the SDK.

Since this is not actionable by the SDK team, I'm going to close this.

All the best,
Ran~
