### ISSUE TITLE
Include  imitation  of 10 message attributes field for sns.PublishInput in godoc

### ISSUE THREAD

**Issue by rengas** [aws/aws-sdk-go-v2#2608]
### Describe the issue

From the docs I quote 

>Amazon SNS supports delivery of message attributes, which let you provide structured metadata items (such as timestamps, geospatial data, signatures, and identifiers) about the message. For SQS subscriptions, a maximum of 10 message attributes can be sent when [Raw Message Delivery](https://docs.aws.amazon.com/sns/latest/dg/sns-large-payload-raw-message-delivery.html) is enabled. To send more than 10 message attributes, Raw Message Delivery must be disabled. Messages with more than 10 message attributes directed towards Raw Message Delivery enabled Amazon SQS subscriptions will be discarded as client side errors.

Please consider adding this limitation to [godoc](https://github.com/aws/aws-sdk-go-v2/blob/main/service/sns/api_op_Publish.go#L80) of sns.PublishInput or at least the link should be added

### Links

https://docs.aws.amazon.com/sns/latest/dg/sns-message-attributes.html

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2 v1.21.0

**Comment by RanVaknin** [comment]
Hi @rengas ,

Thanks for reaching out. What you are asking for makes sense, but the SDK docs are code generated from the API models of each AWS service. Because of that, the SDK team cannot change / add / remove documentation from service or operation specific constructs. 
Instead, You can [submit feedback](https://docs-feedback.aws.amazon.com/feedback.jsp?feedback_destination_id=305d62cc-394c-4440-b5ae-1c821f5a4ec4&topic_url=https://docs.aws.amazon.com/sns/latest/api/API_Publish.html) directly to the service team by pressing on the `Feedback` button found on the top right corner of every API reference page. 

Since this is not actionable by the SDK team, Im going to go ahead and close this issue.
Thanks again for taking the time and submitting the request.

All the best,
Ran~
