### ISSUE TITLE
No paginator for DescribeLockedSnapshots?

### ISSUE THREAD

**Issue by sourcefrog** [aws/aws-sdk-go-v2#2611]
### Describe the bug

The [DescribeLockedSnapshots API](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeLockedSnapshots.html) returns paginated results, with a `nextToken`.

Other paginated APIs have paginator helpers, such as https://github.com/aws/aws-sdk-go-v2/blob/service/ec2/v1.156.0/service/ec2/api_op_DescribeSnapshots.go#L241.

### Expected Behavior

It would be nice if there was a paginator for locked snapshots, created by e.g. `NewDescribeLockedSnapshotsPaginator`.

### Current Behavior

There is no paginator API; you can fetch results one page at a time I presume.

### Reproduction Steps

n/a, it doesn't crash, the feature just isn't there

### Possible Solution

It would be nice if there was a paginator for locked snapshots, created by e.g. `NewDescribeLockedSnapshotsPaginator`.

### SDK version used

v1.156.0

### Environment details (Version of Go (`go version`)? OS name and version, etc.)

go version go1.22.1 darwin/arm64

**Comment by RanVaknin** [comment]
Hey @sourcefrog ,

Thanks for reaching out. The reason this paginator is missing is because the API model of EC2 doesn't define this operation as a paginatable operation. In theory this should be a really easy fix, but this is not something the SDK team can directly address. Since the SDK is code generated from the various AWS services' API models, all of the model changes need to be fixed upstream with the service team itself.

I have created an internal ticket on your behalf to address this `P126629878`.

Since this is not actionable by the Go SDK team I will close this issue, but I will update the thread once I hear back. 

Thanks again!
Ran~
