### ISSUE TITLE
Add support for Prometheus compatible APIs in amp service

### ISSUE THREAD

**Issue by zoonage** [aws/aws-sdk-go-v2#2658]
### Describe the feature

To do https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-APIReference-RemoteWrite.html at the moment we'd need to sign requests manually, implement retry logic, and other things that the SDK gives us out of the box

### Use Case

We have a Lambda function that needs to write directly to Prometheus, as we can't use our normal setup with the otel collector that we have for ECS we are sending the metrics directly to it.

The alternative is doing Lambda -> CloudWatch EMF -> Metrics stream -> AMP which is a lot of extra hops to avoid a single API call

### Proposed Solution

Add a `Client.RemoteWrite` method (and I guess `RemoteRead` might as well be there?)

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

v1.25.8

### Go version used

go version go1.22.2 darwin/arm64

**Comment by RanVaknin** [comment]
Hi @zoonage ,

Thanks for reaching out. 
The AWS SDKs are all code generated from the various API models of each AWS service. This means that if an AWS service didn't model `RemoteWrite` and `RemoteRead` operations on their API, they will not exist in the SDK and the SDK team cannot directly add them.

Admittedly, I'm not familiar with Prometheus, but based on the documentation [here](https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-onboard-ingest-metrics-existing-Prometheus.html), `RemoteWrite` is configured directly within Prometheus itself, rather than through API calls that could be made via the SDK. This would also explain why `RemoteWrite` and non of the other [AMP’s Prometheus-compatible APIs](https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-APIReference-Prometheus-Compatible-Apis.html) have been included in the public API model for AMP. 

Thanks,
Ran~

**Comment by zoonage** [comment]
Hi @RanVaknin 

Is there a separate repo to raise this to the relevant service team or is it best raised via our aws account team as a feature request?

You're correct in that the request is made against the specific instance as opposed to the typical endpoint, however services like Neptune have a similar model for the neptunedata API where you configure the endpoint URL for the client which was where my line of thinking was going

**Comment by RanVaknin** [comment]
Hi @zoonage ,

I have raised a feature request on your behalf (internal ticket ID `P132973119`). If you have access to AWS support via the developer console you can create another support ticket and reference that ticket ID, an assigned account manager would be able to drive this forward on your behalf.

Otherwise if I hear back anything I will update this thread, but in the meantime, since its not actionable by the SDK team, Im going to close it.

Thanks again for reaching out.
Ran~

**Comment by RanVaknin** [comment]
@zoonage  heard back from the prometheus team:

> Prometheus compatible API are not compatible with AWS SDK model and there is no plan to make it available in the SDK.
> 
> 1. use ADOT as a layer to write to AMP
> 2. use the open-source Prometheus client to remote_write to AMP: https://github.com/prometheus/prometheus/blob/efbd6e41c59ec8d6b7a0791c1fb337fdac53b4f2/storage/remote/client.go#L140
>
