### ISSUE TITLE
Support for paginators in the apigatewayv2 service

### ISSUE THREAD

**Issue by jvdb-eurobase** [aws/aws-sdk-go-v2#2660]
### Acknowledgements

- [X] I have searched (https://github.com/aws/aws-sdk/issues?q=is%3Aissue) for past instances of this issue
- [X] I have verified all of my SDK modules are up-to-date (you can perform a bulk update with `go get -u github.com/aws/aws-sdk-go-v2/...`)

### Describe the bug

Listing APIs in the apigatwayV2 service is a paginated operation but the apigatewayv2 sdk doesn't provide paginators.

### Expected Behavior

Apigatewayv2 provides paginator functions similar to the apigateway package.

### Current Behavior

No paginators in the apigatewayv2 package

### Reproduction Steps

-

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/service/apigateway v1.23.10
github.com/aws/aws-sdk-go-v2/service/apigatewayv2 v1.20.8

### Compiler and Version used

go version go1.22.2 linux/amd64

### Operating System and version

linux/amd64

**Comment by RanVaknin** [comment]
Hi @jvdb-eurobase,

Thanks for reaching out. The reason the Go SDK doesn't have paginators for APIGWv2 is because the internal API model for this service does not have any paginator definitions. Since the AWS SDKs are code-generated from those models, the SDK team cannot add them directly.

I have created an internal ticket with the APIGW team (ticket ID `P133517160`) and have asked them to add those paginator definitions.

Since this is not directly actionable by the SDK team, I'm going to close this issue. If you have access to support via the AWS developer console, you can create a support ticket and reference the ticket ID I shared above to get updates from the service team directly. Otherwise you'll need to keep an eye out for our release notes to know when its fixed.

Thanks again for taking the time and writing us.

All the best,
Ran~
