### ISSUE TITLE
Add support to create git tags

### ISSUE THREAD

**Issue by praveenk007** [aws/aws-sdk-go-v2#2670]
### Describe the feature

As a developer, I want to create new git tags through the SDK. Currently, I need to clone the repo on a file storage or in-memory (using go-git), create a tag off a branch and push it. This is problematic for a couple of reasons:
1. The client's codebase can be in Mbs
2. There can be thousands of such requests per minute, causing the app to slow down and crash

The SDK should have a provision to create such tags through below details passed in request
```
RepositoryName
SourceBranchName
TagName
AuthorName
CommitMessage
Email
```

### Use Case

We have a CRUD platform-service written in Golang, and sits on top of AWS CodeCommit abstracting the same from end-users. The service is responsible to create/delete/update repo details, create/delete branches. And now we have a new requirement to cut tags as well.
Workaround is to use go-git for this use-case, but that may cost us performance issues later as that involves cloning the repo in-mem or in-disk.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2 v1.26.1
github.com/aws/aws-sdk-go-v2/service/codecommit v1.22.5

### Go version used

1.22.3

**Comment by aBurmeseDev** [comment]
Hi @praveenk007 - appreciate you for reaching out. 

This's actually a feature service team (CodeCommit) need to review/implement rather than SDK. I've submitted an internal request to CodeCommit team on your behalf. (_P134088191_) Feel free to add any other information you'd like to include in the request. 

Since this repo is dedicated for SDK related, it's going to auto-close in a few days. 
Best,
John
