### ISSUE TITLE
support item op for Dax client

### ISSUE THREAD

**Issue by xxu3-sc** [aws/aws-sdk-go-v2#2693]
### Describe the feature

thanks for making the v2 Dax client, however I notice I can't use it for GetItem/PutItem/Delete/Query etc 

### Use Case

I need it cause we already have dynamodb client, and now we need Dax for better read performance

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

v1.30.0

### Go version used

go1.22.0

**Comment by RanVaknin** [comment]
Hi @xxu3-sc,

The DAX client we have in the v2 SDK is the control plane client for creating / deleting / updating the DAX cluster itself. What you are looking for is a DAX data plane client that lets you interact with your table that are fronted by the DAX cluster. 

That package was never a part of the SDK. Instead it was the DynamoDB team that published their own data plane package that integrated with the Go SDK v1. The DynamoDB team has a backlog item to implement a new DAX client that would integrated with v2, but we don't have visibility / cant commit to a timeline. 

Please see: https://github.com/aws/aws-sdk/issues/743

Since this is not actionable by our team I'm going to close this.
Thanks,
Ran~
