### ISSUE TITLE
elasticloadbalancingv2 AddTags func is taking as input a list of ResourceArns but can only process one at a time

### ISSUE THREAD

**Issue by marie-linet** [aws/aws-sdk-go-v2#2715]
### Acknowledgements

- [X] I have searched (https://github.com/aws/aws-sdk/issues?q=is%3Aissue) for past instances of this issue
- [X] I have verified all of my SDK modules are up-to-date (you can perform a bulk update with `go get -u github.com/aws/aws-sdk-go-v2/...`)

### Describe the bug

When I'm performing 
`
	_, err := s.elasticloadbalancingClient.AddTags(ctx, &elasticloadbalancingv2.AddTagsInput{
			ResourceArns: []string{resource1, resource2},
			Tags:         tagsToApply,
		})
`
with a list of resources for the `ResourceArns` input parameters, I have this error message:

`operation error Elastic Load Balancing v2: AddTags, https response error StatusCode: 400, RequestID: 9fceac96-3839-4d08-bdae-..., api error ValidationError: Only one resource can be tagged at a time
exit status 1`

### Expected Behavior

Having the possibility to set a list of resources as input for `ResourceArns` should allow me to tags a list of load balancer (as we do for the ec2.CreateTag func for instance of volume with a limited number of resources). 

### Current Behavior

When I put a list of resources, I have this error:
`operation error Elastic Load Balancing v2: AddTags, https response error StatusCode: 400, RequestID: 9fceac96-3839-4d08-bdae-... api error ValidationError: Only one resource can be tagged at a time
exit status 1`

### Reproduction Steps

Try to tag multiple load balancer by putting a list of multiple resources as input for `ResourceArns`

### Possible Solution

- allow to tag multiple resources at the same time
- update the API to only handle one string and not a list of string as signature of `ResourceArns`
- update the description of the func to precise that it's possible to only tag one resource at the time

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/service/elasticloadbalancingv2 v1.31.3

### Compiler and Version used

go version go1.22.3 linux/amd64

### Operating System and version

Ubuntu 22.04.1 LTS

**Comment by RanVaknin** [comment]
Hi @marie-linet ,

The behavior you are witnessing is an issue with the ELB API itself, and not the SDK. All of the AWS SDKs are code generated from the API models of each AWS service. The SDK team cannot change the function signature because that is defined upstream. 

I have created a internal feature request (`#P141414069`) with the ELB service team and asked them to do one of the following:

-    allow to tag multiple resources at the same time
-    update the documentation that it's possible to only tag one resource at the time

Regarding this one `update the API to only handle one string and not a list of string as signature of ResourceArns` 
This cannot be a solution since changing the function signature would be considered a breaking change.

Since this is not actionable by the SDK team, Im going to close this.
Thanks,
Ran~
