### ISSUE TITLE
add pagination for data lifecycle manager 

### ISSUE THREAD

**Issue by AmitOttenheimer** [aws/aws-sdk-go-v2#2727]
### Describe the feature

there is no built in pagination for dlm package  in the sdk

### Use Case

handle multiple dlm policies in aws region  

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

1.16.11

### Go version used

1.22.4

**Comment by RanVaknin** [comment]
Hi @AmitOttenheimer ,

Thanks for reaching out. 

The AWS SDK clients are all code-generated from the API models of each AWS service which they interact with. The reason DLM does not have paginator methods, is because the DLM API model did not define the I/O needed for pagination for the SDKs codegen system to hook into and generate them.

Looking at the API operations for DLM I see the following:
[CreateLifecyclePolicy](https://docs.aws.amazon.com/dlm/latest/APIReference/API_CreateLifecyclePolicy.html)
    [DeleteLifecyclePolicy](https://docs.aws.amazon.com/dlm/latest/APIReference/API_DeleteLifecyclePolicy.html)
    [GetLifecyclePolicies](https://docs.aws.amazon.com/dlm/latest/APIReference/API_GetLifecyclePolicies.html)
    [GetLifecyclePolicy](https://docs.aws.amazon.com/dlm/latest/APIReference/API_GetLifecyclePolicy.html)
    [ListTagsForResource](https://docs.aws.amazon.com/dlm/latest/APIReference/API_ListTagsForResource.html)
    [TagResource](https://docs.aws.amazon.com/dlm/latest/APIReference/API_TagResource.html)
    [UntagResource](https://docs.aws.amazon.com/dlm/latest/APIReference/API_UntagResource.html)
    [UpdateLifecyclePolicy](https://docs.aws.amazon.com/dlm/latest/APIReference/API_UpdateLifecyclePolicy.html)
    
Out of the operations in this list, the only two operations that might be able to support pagination are `ListTagsForResource` and `GetLifecyclePolicies`. However looking at the input parameters for these, they do no support pagination on the API level - specifically there is no `nextToken`/	`Marker` or `max_results` /`pageSize` for the SDK to hook into.

I have created an internal feature request (`P144890533`) with the service team to add these, but since the API itself does not support pagination for these methods, the SDK cannot support it either. Since this is not actionable by the SDK team I'm going to close this and ask that you check our changelog for any changes pertaining to adding these in the future. 

Thanks,
Ran~

**Comment by RanVaknin** [comment]
Update: The service team does not have a plan to introduce pagination for this operation.
