### ISSUE TITLE
Support for IPC (Greengrass Core interprocess communication)

### ISSUE THREAD

**Issue by bartolsthoorn** [aws/aws-sdk-go-v2#2729]
### Describe the feature

IPC is a common way for different Greengrass components to communicate and to talk with IoT core.

See for example: https://github.com/aws/aws-iot-device-sdk-python-v2/blob/main/samples/ipc_greengrass.py

### Use Case

We use IPC to communicate between Greengrass components. For us this is a blocker to switch from Python to Golang with our Greengrass/IoT solution.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

2024-07-29

### Go version used

1.22.3

**Comment by RanVaknin** [comment]
Hi @bartolsthoorn ,

Thanks for reaching out. 
The repo you linked is a package owned by the IOT team at AWS, not the SDK team. 
The AWS SDK is code generated from the API models of each AWS service it interacts with. From what I can tell the package you linked is some sort of data plane client that interacts with Greengrass, whereas the AWS SDKs generally only offer control plane clients like https://github.com/aws/aws-sdk-go-v2/tree/main/service/greengrassv2

This feature request should be directed at the Greengrass service team. You can either reach them by creating a support ticket through your AWS console, or by opening a [feature request](https://github.com/aws/aws-iot-device-sdk-python-v2/issues/new?assignees=&labels=feature-request%2Cneeds-triage&projects=&template=feature-request.yml&title=%28short+issue+description%29) on the repo you linked.

Since this is not actionable by the SDK team, Im going to close this.
Thanks again,
Ran~

**Comment by lucix-aws** [comment]
Per @RanVaknin 's statement above - the "IoT" SDKs (such as aws-iot-device-sdk-python) are a separate family apart from the main AWS SDKs that vend APIs for AWS services. To my knowledge, there is not presently an IoT SDK for Go.
