### ISSUE TITLE
Lack of VaultState attribute on Describe/List operations for Backup Vault

### ISSUE THREAD

**Issue by aristosvo** [aws/aws-sdk-go-v2#2738]
### Describe the feature

Due to the launch of Logically Air-Gapped Backup Vaults, I tried to implement this resource in Terraform.

However, the `VaultState` which is given back in https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/backup#CreateLogicallyAirGappedBackupVaultOutput is not available in the other actions of the SDK yet, making it impossible to check for status.

### Use Case

Wait until the LAG Backup Vault is available and execute follow up actions

### Proposed Solution

Expose VaultStatus in DescribeBackupVault and/or ListBackupVaults

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

1.36.3

### Go version used

1.22.6

**Comment by RanVaknin** [comment]
Hi @aristosvo ,

Thanks for reaching out. 

I'm not entirely sure what you mean by "is not available in the SDK yet", since you linked the exact point where it _does_ exist in the SDK.

Based on the rest of the description of the issue, it seems to me that what you are really asking for, is for `VaultState` to be available in the response of `DescribeBackupVault` so you can poll for a change in status. Like a waiter, is that correct?

If so, this is not something the SDK team can add. This would have to be a feature request to the backup service team itself because there must be server side support first, for us to be able to add this.

Can you please clarify what you meant here?

Thanks,
Ran~

**Comment by aristosvo** [comment]
Hi @RanVaknin!

Thanks for your reply. I meant indeed the latter, that de Describe action doesn't disclose it yet, and indeed something we'd implement in a waiter.

I have checked via the browser, and at least in the List action the VaultState was returned, so it seems the data is there but not published via de API/SDK definition.

**Comment by RanVaknin** [comment]
Hi @aristosvo ,

Thanks for the clarification. 

>I have checked via the browser, and at least in the List action the VaultState was returned, so it seems the data is there but not published via de API/SDK definition.

Can you please add some more logs showcasing this? That would make it easier to submit that feature request to that service team on your behalf.

Thanks,
Ran~

**Comment by aristosvo** [comment]
Hi @RanVaknin!

Sure, here they are. Screenshotted from the console network inspection, hope this is good enough?

ListBackupVaults:
<img width="748" alt="Screenshot 2024-08-13 at 04 46 29" src="https://github.com/user-attachments/assets/9d46f01d-f9d0-4e21-beec-5c10862ff361">
<img width="740" alt="Screenshot 2024-08-13 at 04 45 56" src="https://github.com/user-attachments/assets/8afa8b4a-4133-499c-b3c8-3c00828dd341">

DescribeBackupVault:
<img width="548" alt="Screenshot 2024-08-13 at 04 47 25" src="https://github.com/user-attachments/assets/2b2323c4-314e-4fb9-a892-64c012c52149">

<img width="546" alt="Screenshot 2024-08-13 at 04 47 01" src="https://github.com/user-attachments/assets/2de74bfc-fae3-465f-a5cf-85c82d3b611e">

**Comment by RanVaknin** [comment]
Hi, 

Thank you for the additional info. I was able to get in touch with the backup service team, and have confirmed that this was not properly released. I have asked them to prioritize this in order to unblock you (internal ticket `P148107395`), but at the moment I don't have an ETA. 

I will post updates on this internal inquiry as soon as I have any additional info.

Thanks again,
Ran~

**Comment by aristosvo** [comment]
Hi @RanVaknin!

I will close this issue as the [release of 2024-08-30](https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2024-08-30) contains the fields I was waiting for.

Thanks for the support and raising it to the backup service team! 🙏🏽

**Comment by RanVaknin** [comment]
My pleasure, and thank _you_ for your feedback.
