### ISSUE TITLE
aws service-quotas get-service-quota to show current utlization

### ISSUE THREAD

**Issue by simtcrom** [aws/aws-sdk-go-v2#2744]
### Describe the feature

Currently aws service-quotas get-service-quota will not display current utlization.
For eg ```aws service-quotas get-service-quota --service-code elasticloadbalancing --quota-code L-9365A611``` will not display current utilization 
If we can enable that, that would be useful for some automations.

### Use Case

Currently aws service-quotas get-service-quota will not display current utlization.
For eg ```aws service-quotas get-service-quota --service-code elasticloadbalancing --quota-code L-9365A611``` will not display current utilization 
If we can enable that, that would be useful for some automations.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

> aws --version
aws-cli/2.13.15 Python/3.11.4 Windows/10 exe/AMD64 prompt/off

### Go version used

1.21.1

**Comment by RanVaknin** [comment]
Hi @simtcrom,

I understand you're looking to extend the functionality of the Service Quotas API to include current utilization, as seen in the console. The console actually retrieves utilization data using [Cloudwatch's Get Metric Data API](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricData.html). This functionality is not part of the Service Quotas API itself.

Additionally, it's important to note that SDKs and CLI are _clients_ and act as an interface to AWS services and do not influence their underlying features. The SDKs and CLI are directly code-generated from the service APIs, and only the respective AWS service teams have the ability to modify API functionalities.

Since the capability you require is available through the CloudWatch API and this issue is outside the scope of the Go SDK team, I will close this issue.

Thanks,
Ran~
