### ISSUE TITLE
Add support for `dualStackIPv6` ECS account setting

### ISSUE THREAD

**Issue by diogoazevedos** [aws/aws-sdk-go-v2#2772]
### Describe the feature

Add support for `dualStackIPv6` ECS account setting.

### Use Case

Enable `dualStackIPv6` using Terraform [`aws_ecs_account_setting_default`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_account_setting_default).

### Proposed Solution

I think it's matter of adding the `dualStackIPv6` to: https://github.com/aws/aws-sdk-go-v2/blob/31c2861732d68954e5941053c22644f77ae71661/service/ecs/types/enums.go#L970-L999

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

None

### Go version used

1.23.0

**Comment by bhavya2109sharma** [comment]
Hello @diogoazevedos 

I've looked into your issue and can confirm that the enum is not being correctly modeled by the service team. This has also been reported by other SDK customers.

There is an existing internal ticket (P146481495) with the EC2 service team to update their model with the missing enum. Since the AWS SDKs are code-generated from these API models, the SDK team cannot add the missing enum directly. The service team will need to make the change on the backend.

As a workaround, you can directly pass the string value instead of using the enum. This is already documented [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-account-settings.html#:~:text=Resource%20name%3A-,dualStackIPv6,-Amazon%20ECS%20supports), so you can use the string value and it should work as expected.

Since this is a duplicate, Im going to close this issue and ask you to track the [existing one](https://github.com/aws/aws-sdk/issues/800) for updates.

Thanks
~Bhavya
