### ISSUE TITLE
S3 Event Notification Filter Rule Names changing string value from case insensitive to case sensitive 

### ISSUE THREAD

**Issue by ge0Aja** [aws/aws-sdk-go-v2#2849]
### Describe the bug

I'm using [FilterRuleNames](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3/types#FilterRuleName) to have a prefix filter when creating an event notification for an S3 bucket. 
I'm using the const enum values provided by the SDK to create the filter. However, when I query back the created event notification and match against the filter rule name I get empty values. 
I've checked on the created event notification and the rule seem to be there, but with a different name i.e. `Prefix` instead of `prefix`.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

I expect to find the created rule using the filter rule name consts provided by the SDK.

### Current Behavior

If we iterate over the created filter names we won't be able to match any of the const names provided by the SDK

### Reproduction Steps

Create an event notification on an S3 bucket with a filter rule to target a specific prefix for example

```Go
var itemId = "ID"
var lambdaArn = "arn"
var prefix = "prefix"

_, err = s3Client.PutBucketNotificationConfiguration(context.Background(), &s3.PutBucketNotificationConfigurationInput{
		Bucket: &bucketName,
		NotificationConfiguration: &types.NotificationConfiguration{
			LambdaFunctionConfigurations: []types.LambdaFunctionConfiguration{
				types.LambdaFunctionConfiguration{
					Id:                &itemId,
					LambdaFunctionArn: &lambdaArn,
					Events:             []types.Event{types.EventS3ObjectCreated, types.EventS3ObjectRemoved},
					Filter: &types.NotificationConfigurationFilter{
						Key: &types.S3KeyFilter{
							FilterRules: []types.FilterRule{
								{
									Name:  types.FilterRuleNamePrefix,
									Value: &prefix,
								},
							},
						},
					},
				},
			},
		},
	})
```

Try to query it back again and switch case match using the prefix enum value

```Go
var prefix string
var suffix string

out, err := s3Client.GetBucketNotificationConfiguration(context.Background(), &s3.GetBucketNotificationConfigurationInput{
		Bucket: &bucketName,
})

if err != nil {
    return err
}

lfcs := out.LambdaFunctionConfigurations

for _, lfc := range lfcs.LambdaFunctionConfigurations {
	for _, rule := range lfc.Filter.Key.FilterRules {
		if rule.Value == nil {
			continue
		}

		switch rule.Name {
		case types.FilterRuleNamePrefix:
			prefix = *rule.Value
		default:
		}
	}
}
```

`prefix` will always be `""`

### SDK version used

v1.32.2

### Environment details (Version of Go (`go version`)? OS name and version, etc.)

go 1.23.1 / ubuntu 22.04

**Comment by RanVaknin** [comment]
Hi @ge0Aja ,

Thanks for reaching out. If I understand you correctly, your concerns is that when creating an event notification filter the filter name is `prefix` but when you are getting the result back from S3 using `GetBucketNotificationConfiguration` you get the filter name as `Prefix`. 

The AWS SDKs are code generated from the API model of each AWS service it interacts with. The reason why the SDK is generated with the Filter Rule names as `prefix` and `suffix` (lower cased) is because this is how they are modeled in the [S3 API model](https://raw.githubusercontent.com/aws/aws-sdk-go-v2/refs/heads/main/codegen/sdk-codegen/aws-models/s3.json):

```json
      "com.amazonaws.s3#FilterRuleName": {
            "type": "enum",
            "members": {
                "prefix": {
                    "target": "smithy.api#Unit",
                    "traits": {
                        "smithy.api#enumValue": "prefix"
                    }
                },
                "suffix": {
                    "target": "smithy.api#Unit",
                    "traits": {
                        "smithy.api#enumValue": "suffix"
                    }
                }
            }
        },
```

In addition, the [S3 docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-how-to-filtering.html) also showcase that to create those filter rules those names should be lower cased.

While I agree that this is confusing, the SDK team cannot do anything to change it since model changes must be changed upstream with the S3 service team itself, not on the SDK side. Even if the service decides to change the casing here, from a backwards compatibility standpoint, we wont be able to roll out the change since code that is reliant on the lower cased value will start breaking.

Let me know if I understood your concern, and if you have any questions that we can further assist with.

Thanks,
Ran~
