### ISSUE TITLE
Go SDK: Guardrail wordsConfig required (should be optional)

### ISSUE THREAD

**Issue by dabounds** [aws/aws-sdk-go-v2#2855]
When adding a BedrockGuardrail via Go/Terraform, the wordsConfig is listed as optional, but gives the following error when omitted:

Error: AWS SDK Go Service Operation Unsuccessful
Calling Cloud Control API service UpdateResource operation returned:
operation error CloudControl: UpdateResource https response error
StatusCode: 400, RequestID: <omitted>, api error
ValiationException: Model valudation failed
(#/WordPolicyConfig/WordsConfig: expected minimum item count: 1, found: 0)

**Comment by RanVaknin** [comment]
Hi @dabounds,

I understand that you are consuming the Go SDK through Terraform which is why you are getting this validation. 
When I tried using the SDK directly to interact with bedrock I got this error:

> ValidationException: This Word policy must have at least one configuration.

Which makes sense. `WordPolicyConfig` expects at least one of it's params (`ManagedWordListsConfig` or `WordsConfig`) to be provided. Because its an either / or situation you cannot model them as required fields and they have to be modeled as optional. 

This should have been clarified via the [documentation](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_GuardrailWordPolicyConfig.html). If you wish to provide feedback to the AWS Bedrock team on adding clarifying information to that documentation page you can do that by clicking on the [Feedback](https://docs-feedback.aws.amazon.com/feedback.jsp?hidden_service_name=Bedrock-AI&topic_url=https://docs.aws.amazon.com/bedrock/latest/APIReference/API_GuardrailWordPolicyConfig.html) button in the top right corner.

Please let me know if there's anything else I can help you with. 

Thanks,
Ran~
