### ISSUE TITLE
s3manager max_bandwidth

### ISSUE THREAD

**Issue by yiguo-wish** [aws/aws-sdk-go-v2#2875]
### Describe the feature

Hello,

We have s3 download/upload bandwidth ratelimit in aws-cli https://github.com/aws/aws-cli/pull/2997.
It could be great to have this feature in golang sdk.

Thanks!

### Use Case

In a shared env, limiting each individual's bandwidth could reduce bandwidth impacts to other services sitting in the same node.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

1.35.24

### Environment details (Version of Go (`go version`)? OS name and version, etc.)

go version go1.16.3 linux/amd64, Ubuntu 18.04.4 LTS

**Comment by zshzbh** [comment]
I have submitted the Feature Request to the service team, closing this ticket.

**Comment by nantiferov** [comment]
@zshzbh does it mean that it's not actually yet implemented and there is no way to track another issue on GitHub to get updates when this will be released?

So basically we need to check https://github.com/aws/aws-sdk-go-v2/releases from time to time trying to catch this feature release?

**Comment by zshzbh** [comment]
Hey @nantiferov , 

Apologies if there's any confusion. 

The feature you're requesting requires a modification to the service model. Service models are controlled and generated by the respective service teams within AWS. Since this is not directly actionable by the SDK team and this repo is dedicated for SDK related, I'm going to close this issue.

I have asked the team to mention this github issue if they release this feature request. So no worries! You will know if there's any updates of this feature request when this issue is mentioned. The official ways to get the latest updates would be through AWS  blogs and release info.

Let me know if you have any other questions.

Best,
Maggie
