### ISSUE TITLE
iot: For consistency, CreateCertificateFromCsrRequest should be CreateCertificateFromCSRRequest

### ISSUE THREAD

**Issue by alexkohler** [aws/aws-sdk-go-v2#303]
This is a minor stylistic issue. The Go authors [recommend consistent casing of acronyms](https://github.com/golang/go/wiki/CodeReviewComments#initialisms). Methods such as CreateCertificateFromCsrRequest should be CreateCertificateFromC**SR**Request. This paradigm seems to be followed throughout the rest of the iot interface in methods such as `GetOTAUpdateRequest`, `DeleteCACertificateRequest`, etc.

**Comment by jasdel** [comment]
Thanks for reaching out @alexkohler. The SDK doesn't have a clean method to enforce inflections like this. The names for these operation, types, and members are sourced from a model file that the SDK will code generate from. These models are used by all of the AWS SDKs, and are defined by the respective AWS service team. Unfortunately this means that the SDKs are fairly limited in the naming scheme they can enforce.

The prior to GA, the v1 SDK did have a method for attempting to enforce inflections, but it was limited to guessing against a dictionary of know strings that should be inflected. This feature was [later removed](https://github.com/aws/aws-sdk-go/pulls?q=is%3Apr+inflection+is%3Aclosed), because it became unmaintainable, and introduced the risk of wrong inflections being released because the initialism wasn't in the dictionary.

**Comment by alexkohler** [comment]
Ah, I figured the APIs might have been generated. Thanks for letting me know. Feel free to close if you feel this isn't realistically fixable.

**Comment by jasdel** [comment]
Thanks for the feature request, even though we were not able to take it. Let us know about additional feature requests, issues, or questions you run into with the SDK.
