### ISSUE TITLE
Service specific configuration from config file

### ISSUE THREAD

**Issue by laverboy** [aws/aws-sdk-go-v2#345]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
v0.9.0

### Version of Go (`go version`)?
go1.13beta1

### What issue did you see?
I am unable to set service specific configuration through the .aws/config file

### Steps to reproduce
Default behaviour

I wish to use the .aws/config file to specify the path style for S3:

```
[profile default]
aws_access_key_id=foo
aws_secret_access_key=bar
s3 =
  addressing_style = path
```

This is honoured in the aws cli, it would be nice if it was usable here as well.

**Comment by jasdel** [comment]
Thanks for reaching out to us @laverboy. Marking this as a feature request for the SDK to add support for these style fields.

These fields (service specific configuration) are specific to the AWS CLI, and possibly supported by the AWS SDK for Python since its based on the same core. I don't think any of the AWS SDKs support service specific due to the nature of a application SDK vs a CLI. A CLI has no other method to provide configuration options other than a configuration flag/file. Where as SDKs, being based in a programming language can be extended and configured in code based on use case.

The `.aws/config` file can contain several CLI specific options that I don't think translate well to a SDK. There are a generic set of options the SDKs have added support for that are focused on initial configuration of the SDK such as region and credentials. Support for additional options such as service specific configuration isn't currently planned.

**Comment by laverboy** [comment]
Thank you for your response and for marking this a feature request.

I understand your comments but it would be nice to be able to set these config values via something more global because we only need to override them when they are not being run on AWS infrastructure.

But I understand your comments.

Thanks
