### ISSUE TITLE
Infrequently Receiving "Access Denied" for GetObject

### ISSUE THREAD

**Issue by jayd3e** [aws/aws-sdk-go-v2#346]
### Version of AWS SDK for Go?
1.20.1

### Version of Go (`go version`)?
Go 1.9

### What issue did you see?
We recently integrated with AWS SDK for Go and have been using it in production for the past two weeks.  We have seen a number of requests to `S3.GetObject` complete successfully, validating that we are authenticating with AWS correctly.  However, we have received the following "Access Denied" error from the SDK twice:

```
*s3err.RequestFailure
AccessDenied: Access Denied status code: 403, request id: 03B863B8110F81F2, host id: FhXCJS1vfS/jmUQcHAMRb+aQNrJoO7lTNOpTlsdpMMsNOWCMLBQhoDKsLxZicN/8ArJZMRBdpg0=
```

It is occurring for apparently no reason, and we are trying to understand what could possibly be going wrong.

### Steps to reproduce

From what we can see, the two failed requests are no different than the other successful requests. Here is the output we are receiving from the library's DEBUG logging:

```
2019/07/26 19:18:42 DEBUG: Request s3/GetObject Details: 
---[ REQUEST POST-SIGN ]----------------------------- 
GET <key> HTTP/1.1  
Host: <bucket> 
User-Agent: aws-sdk-go/1.20.16 (go1.9.7; linux; amd64) S3Manager  
Authorization: AWS4-HMAC-SHA256 Credential=<credential>, SignedHeaders=host;range;x-amz-content-sha256;x-amz-date, Signature=<signature>  
Range: bytes=0-5242879  
X-Amz-Content-Sha256: <content>  
X-Amz-Date: 20190726T191842Z  
----------------------------------------------------- 
2019/07/26 19:18:44 DEBUG: Response s3/GetObject Details: 
---[ RESPONSE ]-------------------------------------- 
HTTP/1.1 403 Forbidden  
Transfer-Encoding: chunked  
Content-Type: application/xml  
Date: Fri, 26 Jul 2019 19:18:44 GMT  
Server: AmazonS3  
X-Amz-Id-2: <content>
X-Amz-Request-Id: 03B863B8110F81F2  
----------------------------------------------------- 
status code: 403, request id: 03B863B8110F81F2, host id: FhXCJS1vfS/jmUQcHAMRb+aQNrJoO7lTNOpTlsdpMMsNOWCMLBQhoDKsLxZicN/8ArJZMRBdpg0= request_id=a0610123-47d2-44ae-bfa5-0e661a794ed3 user=<user>
status code: 403, request id: 03B863B8110F81F2, host id: FhXCJS1vfS/jmUQcHAMRb+aQNrJoO7lTNOpTlsdpMMsNOWCMLBQhoDKsLxZicN/8ArJZMRBdpg0= request_id=a0610123-47d2-44ae-bfa5-0e661a794ed3 user=<user>
status code: 403, request id: 03B863B8110F81F2, host id: FhXCJS1vfS/jmUQcHAMRb+aQNrJoO7lTNOpTlsdpMMsNOWCMLBQhoDKsLxZicN/8ArJZMRBdpg0= request_id=a0610123-47d2-44ae-bfa5-0e661a794ed3 user=<user>
```

**Comment by jasdel** [comment]
Thanks for reaching out to us @jayd3e. Is there any component of your system that is modifying the bucket or object policy for the Bucket/object being requested? In addition, could you provide more information about how your application retrieves its credentials for the GetObject request?

S3 will return an Access Denied error when the credentials being used for the GetObject call could be caused by issues such as the credentials are not correct, or a policy on the bucket/object blocks access.

* https://aws.amazon.com/premiumsupport/knowledge-center/s3-access-denied-bucket-policy/
* https://aws.amazon.com/premiumsupport/knowledge-center/s3-troubleshoot-403/

It looks like it is also possible for a GetObject operation to return an Access Denied error if the object key does not exist, and the requesting user or role does not have permissions to list the objects in a bucket.

* https://forums.aws.amazon.com/thread.jspa?threadID=56531

**Comment by jayd3e** [comment]
We are calling `GetObject` like so:

```
awsConfig := &aws.Config{
	Region:      aws.String(config.FileStorage.S3.Region),
	Credentials: credentials.NewStaticCredentials(config.FileStorage.S3.AccessKey, config.FileStorage.S3.SecretAccessKey, ""),
}
awsConfig.WithLogLevel(aws.LogDebug)

sess, err := session.NewSession(awsConfig)
if err != nil {
	return nil, err
}

downloader := s3manager.NewDownloader(sess)

buffer := &aws.WriteAtBuffer{}

if _, err := downloader.Download(buffer, &s3.GetObjectInput{
	Bucket: aws.String(config.FileStorage.S3.BucketName),
	Key:    aws.String(document.Key),
}); err != nil {
	return nil, err
}
```

The credentials are stored in the configuration and map to an IAM user.  They work for 99% of requests, but we are seeing requests fail occasionally with different network conditions.  The AWS user/role is the same for all requests.

**Comment by diehlaws** [comment]
Thanks for the additional information @jayd3e. Given the sporading nature of this behavior it seems like this stems from something with the service itself rather than anything specific to the AWS SDK for Go. As a result, the best avenue for guidance on this topic would be to reach out to our Premium Support team by opening a [new technical support case](https://console.aws.amazon.com/support/cases#/create) under the S3 service for further support on the service end. The AWS Premium Support team has access to support tools that allow them to dive deeper into the service side of requests, providing the `X-Amz-Request-Id` (Request ID) and `X-Amz-Id-2` (Host ID / S3 Extended Request ID) values for S3 requests that fail unexpectedly will allow them to review these requests in further detail to determine why S3 unexpectedly returned a 403 Forbidden response for these requests.

**Comment by jayd3e** [comment]
Thanks for the information!  I signed up for a support plan.  Will loop back to this when I find out what is going on for posterity.

**Comment by jayd3e** [comment]
The issue ended up being that in some cases our interface was allowing users to proceed with a process before fully finishing an upload to S3.  Therefore, the file did not exist.  S3 returns a 403 Access Denied in cases where the file does not exist, but the user does not have privileges to view/list buckets.

**Comment by tlehn** [comment]
Should this ticket be closed?

**Comment by jayd3e** [comment]
Yup, the issue was solved for us last year 👍 .  Feel free to close.
