### ISSUE TITLE
ses.Client doesn't implement sesiface.ClientAPI interface

### ISSUE THREAD

**Issue by zhashkevych** [aws/aws-sdk-go-v2#527]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
ses.Client doesn't implement sesiface.ClientAPI interface which makes imposisble to cover code with unit tests. To be more accurate, here what my IDE says: `Cannot use 'sesClient' (type *Client) as type sesiface.ClientAPI Type does not implement 'sesiface.ClientAPI' need method: CloneReceiptRuleSetRequest(*ses.CloneReceiptRuleSetInput) ses.CloneReceiptRuleSetRequest have method: CloneReceiptRuleSetRequest(input *CloneReceiptRuleSetInput) CloneReceiptRuleSetRequest `

**Version of AWS SDK for Go?**
v0.20.0

**Version of Go (`go version`)?**
go 1.14

![image](https://user-images.githubusercontent.com/24574014/78787446-09dff300-79b3-11ea-9da4-f6c61f483a2b.png)

![image](https://user-images.githubusercontent.com/24574014/78787491-19f7d280-79b3-11ea-8e30-195d6c32bd03.png)

**Comment by jasdel** [comment]
Hi @zhashkevych thanks for reaching out. It sounds like there might be a issue with your Go cache, that might be out of sync with either a vendored version of the SDK, or a cached version.  

If the issue is due to caching you can clear your cache.

```sh
# cd into your application's root directory that is using the SDK.
go clean --cache --modcache
```

If the issue is due to vendoring, it could be because a package exports functions or types that reference to the SDK. If that package or project vendors the SDK the version it vendors will be different from the version your application may be using.  Here is a Go issue discussing the problems that can occur when vendored library usage are exported, https://github.com/golang/go/issues/12432.
