### ISSUE TITLE
No documentation for the Retryer which changed in v0.20.0

### ISSUE THREAD

**Issue by skyzyx** [aws/aws-sdk-go-v2#543]
**Describe the issue with documentation**
There is no documentation for this. See #218.

**To Reproduce (observed behavior)**
Look for documentation and not find it.

**Expected behavior**
To have documentation.

**Additional context**
The retryer (retrier?) logic changed in v0.20.0. The old pattern wasn't documented either, but I was able to reverse-engineer how it worked by reading through the test code and tracing line-by-line through the SDK and the panic messages.

You used to be able to customize the number of retries on an `aws.Config` object, then share that config with the instantiation of each new service client. It worked something like this:

```go
config, err = external.LoadDefaultAWSConfig()
config.Retryer = aws.NewDefaultRetryer(func(d *aws.DefaultRetryer) {
	d.NumMaxRetries = 20
})
```

That doesn't work anymore post-v0.20.0. After spending about 90 minutes today digging through the source code line-by-line in the same manner as 6 months ago, I found something that compiled on v0.21.0:

```go
config, err = external.LoadDefaultAWSConfig()
config.Retryer = retry.AddWithMaxAttempts(config.Retryer, 20)
```

But as soon as I ran it, I got a nil pointer error. (The rest of the program was unchanged.) OK. So, I dug around some more. There appears to be `Retryer` defined on both `aws.Config` as well as `aws.Client`. Since `aws.Config` gives me a nil pointer error, let's see about tweaking `aws.Client`.

```go
client := s3.New(*config)
client.Retryer = retry.AddWithMaxAttempts(client.Retryer, 20)
```

This appears to work. So I'm creating this ticket so that (a) y'all can write some non-API reference documentation, and (b) so that the next person who goes searching for this can find it.

**Comment by skyzyx** [comment]
Actually, I'm still getting the following error message after setting max-retries to `30`:

```
Error: retry quota exceeded, 0 available, 5 requested
```

This message isn't very useful in helping me understand what's wrong.

**Comment by jasdel** [comment]
Thanks for reporting this issue @skyzyx. The updated retry behavior does need additional documentation. The following are a couple items that need to be documented about the new behavior.

* Documentation for [aws#Config.Retryer](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws/?tab=doc#Config.Retryer) needs additional details to cover this behavior.

* aws#Config.Retryer will be nil when `LoadDefaultAWSConfig` returns the `Config` value. The intention here is so that client's can know that a user's application have not specified a custom Retryer, and the client should create its own.

* A client's Client.Retryer should never be nil, and will either have the user application's custom Retryer, or the client's default Retryer as its value.

* The updated retry behavior added a [retry](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws/retry?tab=doc) package to the SDK, with a [Standard](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws/retry?tab=doc#Standard) Retryer implementation. This replaces the previous retry style's `DefaultRetryer` implementation.

* When a `Standard` Retryer is created you can modify its behavior with the [StandardOptions](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws/retry?tab=doc#StandardOptions) functional options.

* The [StandardOptions.RateLimiter](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws/retry?tab=doc#StandardOptions.RateLimiter) is what is causing the `Error: retry quota exceeded, 0 available, 5 requested` error. The rate limiter is a cross operation limiter on the number of subsequent retry attempts that can be made by a client. The intention for this rate limiter is to catch cases where a service is having availability issues, or the client is experiencing significant throttle or connection issues.

* It probably is helpful for the `retry` or `ratelimit` package to define a `NopRateLimiter` implementation to disable the retry rate limiting behavior.

* The `Standard` Retryer's default retry rate limiter is [ratelimit.TokenRateLimit](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws/ratelimit?tab=doc#TokenRateLimit). If no `RateLimiter` is specified when a `Standard` Retryer is created, it will default to limiting retry rate to 5 retry attempts.

* The retry rate limiter allows the operation request to initially be made, but limits if the client may retry failed attempts.  With the token bucket model, the client can only start retrying failed attempts, after requests have successfully completed, refilling the retry token bucket.  This is the reason setting MaxRetries to 30 fails with the retry quota error. For this to work the retry quota would need to be greater than the maximum number of expected retry attempts across all concurrent operations. Though in a situation like `MaxRetries` of 20, you probably don't want a rate limiter at all, and can disable that behavior by specifying an NoOp implementation of `RateLimiter` that does nothing.

```go
type NoOpRateLimit struct {}
func (NoOpRateLimit) AddTokens(uint) error { return nil }
func (NoOpRateLimit) GetToken(context.Context, uint) (func() error, error) {
     return noOpToken, nil
}
func noOpToken() error { return nil }
```

The retry behavior would be configured like so:

```go
cfg, err := external.LogDefaultAWSConfig()
if err != nil {
     log.Fatalf("failed to load config, %v", err)
}

cfg.Retryer = retry.NewStandard(func(o *retry.StandardOptions) {
     o.MaxAttempts = 20
     o.RateLimiter = NoOpRateLimit{}
})

client := s3.New(cfg)
// use client
```

**Comment by jasdel** [comment]
We should also take a look at if `cfg.Retryer` be `nil` after `LoadDefaultAWSConfig` is the best use case. Alternatives would be some kind of sentinel "default indicator" value that clients use to know they can replace the `cfg.Retryer` with their own default Retryer. It would prevent the case of nil value confusion. But this may create confusion on its own since this sentinel value wouldn't actually be used.

**Comment by jasdel** [comment]
Documentation added in https://github.com/aws/aws-sdk-go-v2/pull/1033
