### ISSUE TITLE
The aws/endpoints documentation still lists functions and types that were removed in 0.21

### ISSUE THREAD

**Issue by cure** [aws/aws-sdk-go-v2#637]
**Describe the issue with documentation**
The file https://github.com/aws/aws-sdk-go-v2/blob/v0.23.0/aws/endpoints/doc.go has an example called "Enumerating Regions and Endpoint Metadata" that relies on functions and types that were removed in 0.21

**To Reproduce (observed behavior)**
Visit https://docs.aws.amazon.com/sdk-for-go/v2/api/aws/endpoints/ and read.

**Expected behavior**
The documentation should reflect the code. An updated example would be very nice.

**Comment by dustin-decker** [comment]
Indeed. How do we enumerate regions for a service now?

https://github.com/aws/aws-sdk-go-v2/pull/593/files seems to suggest that it is no longer possible. I cannot find a way.

**Comment by jasdel** [comment]
Thanks for reporting this issue. With v0.25.0 update to the v2 preview SDK, the `endpoints` package has been removed. Due to this, we can close this issue.

Also to clarify the v2 preview SDK's behavior. It does not provide values to enumerate the AWS regions. This was removed because these regions become stale if the SDK is not updated in an application and the endpoints have been moved as internal behaviors of the API clients. The best way to enumerate AWS regions is either a static list maintained by the application, or using Amazon Elastic Compute Cloud's [DescribeRegions](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2#Client.DescribeRegions) operation.
