### ISSUE TITLE
Larger (1Gb) file copying errors even though it succeeds

### ISSUE THREAD

**Issue by laverboy** [aws/aws-sdk-go-v2#712]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
We use CopyObjectRequest which works fine unless the file size is larger. At which point we can see the file was successfully uploaded to the correct bucket but we get the following error back from S3:

```
exceeded maximum number of attempts, 3, request send failed, Put \"https://<bucket>.s3.eu-west-1.amazonaws.com/<filename>\": net/http: timeout awaiting response headers
```

**Version of AWS SDK for Go?**
v0.24.0

**Version of Go (`go version`)?**
1.14

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

```go
input := s3.CopyObjectInput{
		CopySource:        aws.String(strings.TrimPrefix(source, "s3://")),
		Bucket:            aws.String(location.Bucket),
		Key:               aws.String(location.Key),
		ContentType:       aws.String(contentType),
		MetadataDirective: s3.MetadataDirectiveReplace,
		ACL:               s3.ObjectCannedACLBucketOwnerFullControl,
	}
	request := s.Svc.CopyObjectRequest(&input)
	_, err := request.Send(ctx)
	return err
```

**Expected behavior**
We expect the copy to return with a successful api call to show that the copy was successful.

**Additional context**
If the copy fails we drop to a read/write approach and this always works, no matter the file size.

**Comment by jasdel** [comment]
Thanks for reporting this issue @laverboy. Are you able to share how your application configures the s3 client? the SDK shouldn't be setting a response header timeout by default, but from the error message it looks like that was the error that was encountered.

In addition was the request called with a context that had a deadline, or timeout?

**Comment by laverboy** [comment]
There is no deadline on the context and the sdk's http client is configured with the following timeouts:

```go
        http.Transport{
		ResponseHeaderTimeout: 15 * time.Second,
		Proxy:                 http.ProxyFromEnvironment,
		DialContext: (&net.Dialer{
			KeepAlive: 0,
			Timeout:   2 * time.Second,
		}).DialContext,
		MaxIdleConns:        0,
		IdleConnTimeout:     30 * time.Second,
		TLSHandshakeTimeout: 2 * time.Second,
		MaxIdleConnsPerHost: 0,
	}
```

As you can see they are very generous and are the same ones that we use on the proceeding read and write requests which work every time.

When you say `the SDK shouldn't be setting a response header timeout` is it best practice to have the ResponseHeaderTimeout be infinite? That seems very dangerous. Or am I missing something.

**Comment by jasdel** [comment]
I think the issue that you're running into is that the `ResponseHeaderTimeout` option will tell the HTTP client to cancel the request if the headers are not received within the 15 second timeout. The `CopyObject` operation can take several second to complete, or more depending on the size of the object. The `CopyObject` won't send back its headers until the API has completed copying the object from the source to destination. Due to this the client's `15s` timeout for headers can easily be triggered. You'd see a similar issue with AWS Lambda's `Invoke` operation. Where response headers are not returned for a non0-trival period of time.

One workaround is to increase the `ResponseHeaderTimeout` to a significantly larger value, or not set at all, for these CopyObject operations.  An alternative to the header timeout configuration is to pass in a [timeout context](https://golang.org/pkg/context/#WithTimeout) with a value configured based on the kind of operation being invoked. Operations that are expected to return without delay can have a small timeout, and operations like CopyObject that potentially have large delay, can have an appropriately large timeout.

**Comment by laverboy** [comment]
I see what you are saying, but we can see in the console that the copy has succesfully happened and yet the copy request does not return successfully. And as we said the read-write request, which you would expect to be slower, is working just fine with the same timeout settings.

It seems that somewhere along the line the 'copy finished' response is just not being sent back to the client.

**Comment by jasdel** [comment]
What you're seeing in the console and SDK behavior is correct. Even though the API client has timed out due to the response header, the server is still processing this request on its side. This does not prevent the service from completing the operation, even though the client has disconnected.
