### ISSUE TITLE
SDK's Request type is too generic

### ISSUE THREAD

**Issue by jasdel** [aws/aws-sdk-go-v2#80]
The SDK's `aws.Request` type is too generic and does too much. We want to break this apart. Specifically decouple the `http.Request`/`Response` from the the SDK's request structure. In v1 SDK having the HTTP request built early on made it difficult to extend and modify how the SDK handled requests. e.g HTTP Body value couldn't be fixed to be set to nil when there wasn't actually a request body.

One way this could be done is to abstract the Transport from the SDK's API request. This potentially could manifest as a `Sender`, or `Transport` interface that all SDK's service clients have as a member. This type could be responsible for the protocol (un)marshaling, and round tripping the request over  the wire. This pattern would more easily allow the SDK to support other transport protocols. Such as TCP and MQTT.

**Comment by Skarlso** [comment]
@jasdel You are talking about this guy, right? [Request.go](https://github.com/aws/aws-sdk-go-v2/blob/master/aws/request.go).

I have to read through it completely yet to fully grasp what it does. 

If I could rig up the response that comes back for a request that I also have canned, that would be better. Because I might be running different scenarios which are dependent on some environment change in AWS. Like a CloudFormation stack which was supposed to be running but is instead Rolled back.

Could you elaborate how we would be able to extend the SDK by using the `Sender` interface?
