### ISSUE TITLE
SDK Validation rejects a valid ChangeResourceRecordSetsInput

### ISSUE THREAD

**Issue by muvaf** [aws/aws-sdk-go-v2#803]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**

It's related to https://github.com/crossplane/provider-aws/issues/372

When I look at the example [here](https://aws.amazon.com/premiumsupport/knowledge-center/alias-resource-record-set-route53-cli/), I see that a `ChangeBatch` with no elements in its `ResourceRecords` array is a valid one. However, SDK rejects to make the call and returns the following:
```
InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, ChangeResourceRecordSetsInput.ChangeBatch.Changes[0].ResourceRecordSet.ResourceRecords.
```

In the code, I found that there is a [validation check](https://github.com/aws/aws-sdk-go-v2/blob/v0.23.0/service/route53/api_types.go#L2404) in the SDK.

**Version of AWS SDK for Go?**
Example: v0.23.0
* get SDK version by printing the output of `aws.SDKVersion` in your code after importing `"github.com/aws/aws-sdk-go-v2/aws"`

**Version of Go (`go version`)?**
go1.13.6

**To Reproduce (observed behavior)**

Create an object equivalent of the json [example](https://aws.amazon.com/premiumsupport/knowledge-center/alias-resource-record-set-route53-cli/) here and try making the call.

**Expected behavior**

Call to be made to AWS API.

**Comment by skmcgrail** [comment]
This issue is no longer present in versions since `v0.25.0` since we don't have validation on minimum length member traits from the model. Alternative to upgrading is that it would appear that the slice being assigned to `ResourceRecords` is being assigned as an empty value `[]*ResourceRecords{}` rather then being set to `nil`. This is a subtle distinction but changes the behavior of how the message is serialized and set to the service. I would recommend crossplane should be updated to not initialize the slice until there is a valid item to be added to it.

**Comment by muvaf** [comment]
Thank you @skmcgrail ! I pushed a fix to send `nil` array in case it's empty and we'll make sure to update the SDK to the latest version as soon as possible.
