### ISSUE TITLE
Shutdown/Dispose of a service client

### ISSUE THREAD

**Issue by rfc2119** [aws/aws-sdk-go-v2#815]
I could not find a method for service clients similar to Java's [shutdown()](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/creating-clients.html#client-lifecycle). What should I do to free up resources used by a client ?

**Comment by jasdel** [comment]
Hi @rfc2119 thanks for reaching out. The AWS SDK for Go does not have any background behavior, and does not need to be disposed of or shutdown when no longer needed. When no longer needed ensure your application does not reference the client value and the Go garbage collector will automatically remove it from memory.

The AWS SDK for Java has a dispose/shutdown because it has behavior running in the background with a request queue.

**Comment by rfc2119** [comment]
Alright. Thank you for the explanation. In my use-case, I have multiple clients around (with only one client used) and I feared that Go's garbage collector might not pick the old clients up.
