### ISSUE TITLE
The v2 SDK requires a minimum version of Go 1.9.

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk-go-v2#82]
Could you please provide instructions to update https://amazonlinux.com/ to a >=1.9 release?

`sudo yum install go` attempts to install 1.8.3-1.amzn2 currently. 

Thanks!

**Comment by Doug-AWS** [comment]
According to the yum docs, you can just append a version # to the command, if the version exists. Since you must supply the full version #, you first need to run the following command to see which versions area available:

yum --showduplicates list go

After you do that, so the following *should* work, where VERSION is the version you want:

sudo yum install go-VERSION

**Comment by jasdel** [comment]
Let us know if you still have additional questions, or feedback. The final minimum version for v2 SDK hasn't been finalized yet, but we're using Go 1.9 as a starting point for the developer preview.

**Comment by kaihendry** [comment]
No 1.9 in Amazonlinux 2 btw!

```
[ec2-user@ip-10-0-0-119 ~]$ yum --showduplicates list golang
Loaded plugins: langpacks, priorities, update-motd
Available Packages
golang.x86_64                                                             1.8.3-1.amzn2                                                              amzn2-core
```
