### ISSUE TITLE
[documentation] example code is invalid (pricing.NewGetAttributeValuesPaginator)

### ISSUE THREAD

**Issue by skyzyx** [aws/aws-sdk-go-v2#839]
**Describe the issue with documentation**

The example code is invalid in <https://pkg.go.dev/github.com/aws/aws-sdk-go-v2@v0.24.0/service/pricing#NewGetAttributeValuesPaginator>

```go
// Example iterating over pages.
req := client.GetAttributeValuesRequest(input)
p := pricing.NewGetAttributeValuesRequestPaginator(req)

for p.Next(context.TODO()) {
    page := p.CurrentPage()
}

if err := p.Err(); err != nil {
    return err
}
```

`pricing.NewGetAttributeValuesRequestPaginator` should be `pricing.NewGetAttributeValuesPaginator`.

**Comment by jasdel** [comment]
Thanks for reaching out @skyzyx  with this. I think we can mark this as a duplicate of https://github.com/aws/aws-sdk-go-v2/issues/439 since paginators are not available in the v2 preview SDK, after the v0.25.0 update.

This documentation is for v0.24.0 of the SDK, before the refactor, and once we release paginator's feature they will be contain the correct documentation.
