### ISSUE TITLE
Pricing API still returning aws.JSONValue objects.

### ISSUE THREAD

**Issue by skyzyx** [aws/aws-sdk-go-v2#841]
Extracted from #218, from September 2018 (just over 2 years ago):

> So when I come across something like [`aws.JSONValue`](https://godoc.org/github.com/aws/aws-sdk-go-v2/aws#JSONValue), and I see:
> 
> > “JSONValue is a representation of a grab bag type that will be marshaled into a json string. This type can be used just like any other map.”
> 
> That seems to be great, except that how do you navigate through the deeply-nested `map[string]interface{}` objects which are children of the `aws.JSONValue` object?
> 
> ```go
> type PriceResponse struct {
> 	InstanceType map[string]interface{}
> }
> // make request and handle pagination…
> 
> results := []PriceResponse{}
> 
> for _, entry := range page.PriceList {
> 	results = append(results, PriceResponse{
> 		InstanceType: entry["product"].(map[string]interface{})["attributes"],
> 		// …
> 	})
> }
> ```
> 
> Examples would be very, very nice. While many users of this SDK may be well-versed in Golang, some of us are not quite there yet. There's a lot of trial and error when you're learning a new language and SDK at the same time. :)

Same issue, re-posted. The contents of the Pricing API are still using the `aws.JSONValue` datatype instead of being modeled as a struct, so we still have to do that nasty unknown-type traversal.

If the Pricing API team hasn't yet stabilized and committed to a software contract for this blob of data, please ask them to so that we can get a struct to unmarshal the data into.

If they already have, then please just give us a struct to unmarshal the data into.

Please and thank you. Hearts and sunshine.

**Comment by jasdel** [comment]
Thanks for posting this comment. The v0.25.0 refresh of the v2 preview SDK will expose the concept of `aws.JSONValue` significantly different than the v1 (and v0.24.0 v2 preview SDK) did. We're planning on changing the concept so that when API parameters that contain dynamic document data (e.g. `application/json`), the SDK will generate those members as their base types, such as string or blob (aka `[]byte`). To assist with unmarshaling these member values the SDK would generate an unmarshal method on the structure, such as`UnmarshalPriceList`.

Members like `PriceList` are intentionally left as dynamic JSON data, because their response is not fixed, and most likely never will be. In the case of this specific API, the dynamic JSON data in the response will be driven by the filter, and other parameters relevant to the use case.

Other use cases for dynamic JSON data are members used by APIs may also be arbitrary JSON documents provided by the user's application that has no defined scheme by the API.

I created https://github.com/aws/aws-sdk-go-v2/issues/845 to track this issue. Lets use that one for further discussion and tracking of the SDK's support for dynamic document data embedded within API parameters.
