### ISSUE TITLE
ExpiredToken: The security token included in the request is expired

### ISSUE THREAD

**Issue by Shivam9268** [aws/aws-sdk-go-v2#853]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
I have a container in EKS that reads from an SQS queue. After few hours, I see a bunch of ExpiredToken errors. The SDK should automatically refresh the tokens.

**Version of AWS SDK for Go?**
v0.24.0
**Version of Go (`go version`)?**
1.14.5
**To Reproduce (observed behavior)**
```
config, err := external.LoadDefaultAWSConfig(external.WithRegion(awsRegion))
if err != nil {
	panic(err)
}
sqsClient := sqs.New(config)
```
**Expected behavior**
The SDK should auto-refresh the credentials.

**Comment by jasdel** [comment]
Thanks for reaching out @Shivam9268. The SDK saw a significant update in release v0.25.0, and now on v0.27.0. The SDK's behavior and implementation with regard to credential refreshing has had substantial updates since v0.24.0.  

Are you able to migrate to the latest version of the SDK and attempt to reproduce this issue?
